import { EDITORIAL_ACTIONS } from "./schemas.js";

const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
export const DEFAULT_SELECTION_WEIGHTS = Object.freeze({ novelty: .16, relevance: .14, causal: .12, significance: .12, visual: .1, informationGain: .1, resolution: .1, continuity: .06, duplication: .12, load: .07, interruption: .09, uncertainty: .08, movement: .06 });

export class DeferredOpportunityQueue {
  constructor({ maximum = 200 } = {}) { this.maximum = maximum; this.items = []; }
  add(item) { this.items.push({ ...item }); this.items.sort((a, b) => (b.priority || 0) - (a.priority || 0)); this.items = this.items.slice(0, this.maximum); }
  take(tick) { this.items = this.items.filter(item => !Number.isFinite(item.expiresAtTick) || item.expiresAtTick >= tick); return this.items.shift() || null; }
}

export class EditorialCandidateGenerator {
  generate({ situations = [], audience, nowMs = 0, currentFocus = null, questions = [] } = {}) { const candidates = []; for (const situation of situations) { const same = currentFocus?.situationId === situation.situationId, proposition = situation.propositions?.at(-1), propositionIds = (situation.communicablePropositionIds || situation.propositionIds || []).slice(-4), novelty = proposition ? audience.novelty(proposition, nowMs) : .7; if (!propositionIds.length || novelty < .72) continue; candidates.push({ candidateId: `${same ? "follow" : "switch"}:${situation.situationId}`, action: same ? "FOLLOW_THREAD" : "SWITCH_THREAD", situationId: situation.situationId, propositionIds, novelty, relevance: situation.importance, causal: situation.type.includes("ENVIRONMENT") ? .7 : .45, significance: situation.importance, visual: .7, informationGain: .6, resolution: situation.phase === "RESOLUTION" ? 1 : .2, continuity: same ? 1 : .25, duplication: 1 - novelty, load: .4, interruption: same ? 0 : .5, uncertainty: .2, movement: same ? .1 : .45 }); }
    for (const question of questions) { const situation = situations.find(item => item.situationId === question.situationId), resolving = situation?.phase === "RESOLUTION", proposition = situation?.propositions?.at(-1), propositionIds = (situation?.communicablePropositionIds || []).slice(-3), novelty = proposition ? audience.novelty(proposition, nowMs) : 0; if (!propositionIds.length || novelty < .72 || question.spoken && !resolving) continue; candidates.push({ candidateId: `${resolving ? "resolve" : "ask"}:${question.questionId}`, action: resolving ? "RESOLVE_QUESTION" : "ASK_QUESTION", questionId: question.questionId, situationId: question.situationId, propositionIds, novelty, relevance: .8, causal: .7, significance: .65, visual: .5, informationGain: .9, resolution: resolving ? 1 : .25, continuity: .7, duplication: 1 - novelty, load: .5, interruption: .25, uncertainty: .3, movement: .2 }); }
    candidates.push({ candidateId: "silence", action: "REMAIN_SILENT", situationId: currentFocus?.situationId || null, propositionIds: [], novelty: .3, relevance: .2, causal: 0, significance: .2, visual: .8, informationGain: .1, resolution: 0, continuity: 1, duplication: 0, load: 0, interruption: 0, uncertainty: 0, movement: 0, silence: { breathingRoom: .65, ambientStrength: .55, toneProtection: .45, audienceGap: situations.length ? .35 : .05 } }); return candidates; }
}

export function scoreEditorialCandidate(candidate, weights = DEFAULT_SELECTION_WEIGHTS) { if (!EDITORIAL_ACTIONS.includes(candidate.action)) throw new TypeError(`Unknown editorial action ${candidate.action}`); if (candidate.action === "REMAIN_SILENT") { const s = candidate.silence; return { total: clamp01(.35 * s.breathingRoom + .28 * s.ambientStrength + .22 * s.toneProtection - .3 * s.audienceGap), breakdown: { ...s } }; } const positive = weights.novelty * candidate.novelty + weights.relevance * candidate.relevance + weights.causal * candidate.causal + weights.significance * candidate.significance + weights.visual * candidate.visual + weights.informationGain * candidate.informationGain + weights.resolution * candidate.resolution + weights.continuity * candidate.continuity, negative = weights.duplication * candidate.duplication + weights.load * candidate.load + weights.interruption * candidate.interruption + weights.uncertainty * candidate.uncertainty + weights.movement * candidate.movement; return { total: clamp01(positive - negative), breakdown: { positive, negative } }; }

export class CommitmentManager {
  constructor({ baseThreshold = .12, maximumTicks = 30 } = {}) { this.baseThreshold = baseThreshold; this.maximumTicks = maximumTicks; this.current = null; }
  choose(scored, tick, { speechActive = false, nearResolution = false, critical = false } = {}) { const ranked = [...scored].sort((a, b) => b.score.total - a.score.total), best = ranked[0]; if (!this.current || critical || tick - this.current.startedAtTick > this.maximumTicks) return this.commit(best, tick, critical ? "critical-override" : "best-eligible"); const incumbent = ranked.find(item => item.candidate.situationId === this.current.situationId) || { score: { total: 0 } }, threshold = this.baseThreshold + (speechActive ? .18 : 0) + (nearResolution ? .15 : 0); return best.score.total - incumbent.score.total > threshold ? this.commit(best, tick, "utility-margin") : incumbent;
  }
  commit(item, tick, reason) { this.current = { situationId: item?.candidate?.situationId || null, candidateId: item?.candidate?.candidateId || "silence", startedAtTick: tick, reason }; return item; }
}
