const clean = value => String(value ?? "").replaceAll("_", " ").trim();
const subjectName = (proposition, entities) => { const id = proposition.subjectIds[0]; return entities?.get(id)?.name || entities?.get(id)?.label || id || "this part of the world"; };

export class AuthoredUnitRegistry {
  constructor() { this.units = new Map(); this.registerDefaults(); }
  register(unit) { if (!unit?.unitId || !unit?.realises || !unit?.clauses) throw new TypeError("invalid authored unit"); this.units.set(unit.unitId, Object.freeze({ ...unit })); return this; }
  eligible(proposition, functionName = "EXPLANATION") { return [...this.units.values()].filter(unit => (unit.realises === proposition.predicate || unit.realises === "*") && (!unit.functions || unit.functions.includes(functionName)) && (!unit.epistemicClasses || unit.epistemicClasses.includes(proposition.epistemicClass))); }
  registerDefaults() {
    this.register({ unitId: "generic.authoritative.v1", realises: "*", functions: ["EXPLANATION", "OBSERVATION", "RESOLUTION", "CORRECTION"], epistemicClasses: ["DIRECT_OBSERVATION", "AUTHORITATIVE_STATE", "DETERMINISTIC_DERIVATION"], clauses: { observation: "{subject} is showing {predicate}.", consequence: "That change may alter what remains possible next." }, wordingFamily: "authoritative-observation" });
    this.register({ unitId: "generic.qualified.v1", realises: "*", functions: ["EXPLANATION", "OBSERVATION", "RESOLUTION"], epistemicClasses: ["STRONG_ASSOCIATION", "EDITORIAL_HYPOTHESIS", "BOUNDED_PREDICTION", "REPORTED_BY_ENTITY_SIGNAL"], clauses: { observation: "The evidence suggests {predicate} around {subject}.", consequence: "The next verified change will test that interpretation." }, wordingFamily: "qualified-observation" });
    this.register({ unitId: "generic.unknown.v1", realises: "*", functions: ["EXPLANATION", "OBSERVATION"], epistemicClasses: ["UNKNOWN"], clauses: { observation: "What will the next observation reveal about {subject}?" }, wordingFamily: "bounded-question" });
    this.register({ unitId: "physiology.condition.v1", realises: "physiological_condition_observed", functions: ["EXPLANATION", "OBSERVATION"], clauses: { observation: "{subject}'s physical state has changed.", consequence: "Its available fuel and current debts now constrain the next action." }, wordingFamily: "physiology-change" });
    this.register({ unitId: "environment.condition.v1", realises: "environmental_conditions_observed", functions: ["EXPLANATION", "OBSERVATION"], clauses: { observation: "The landscape is carrying a measurable change.", consequence: "Water, ground and vegetation will determine where its effects appear next." }, wordingFamily: "world-process" });
  }
}

export class DeterministicSurfaceRealiser {
  constructor({ registry = new AuthoredUnitRegistry() } = {}) { this.registry = registry; this.recentStrings = []; this.recentFamilies = []; }
  special(proposition, entities) { const subject = subjectName(proposition, entities), args = proposition.arguments || {}; if (proposition.predicate.startsWith("scene_")) return [args.detail || args.title, args.context ? `This is part of the ${clean(args.context)} now unfolding.` : null].filter(Boolean); if (proposition.predicate.startsWith("behaviour_")) return [`${subject} is now ${clean(args.actionKey || proposition.predicate.slice(10))}.`, args.priority ? `That action serves the current priority of ${clean(args.priority)}.` : null].filter(Boolean); if (proposition.predicate === "physiological_condition_observed") { const values = [["health", args.health], ["hydration", args.hydration], ["available energy", args.energy]].filter(([, value]) => Number.isFinite(Number(value))).map(([label, value]) => `${label} ${Math.round(Number(value))}`); return values.length ? [`For ${subject}, the verified physiological record shows ${values.join(", ")}.`] : [`${subject}'s physical state is constraining what remains possible.`]; } if (proposition.predicate === "environmental_conditions_observed") return [`Here, ${clean(args.terrain || args.landCover || "the local terrain")} carries the current water and vegetation conditions.`, Number.isFinite(args.biomass) ? `Recorded biomass is ${Number(args.biomass).toFixed(2)} in this cell.` : null].filter(Boolean); return null; }
  realise(contract, propositions, { entities = new Map() } = {}) { const sentences = [], usedUnits = [], families = []; for (const proposition of propositions.slice(0, contract.maximumSentences)) { const special = this.special(proposition, entities); if (special) { sentences.push(...special); usedUnits.push(`semantic:${proposition.predicate}`); families.push(proposition.predicate); continue; } const eligible = this.registry.eligible(proposition, contract.function).sort((a, b) => Number(b.realises === proposition.predicate) - Number(a.realises === proposition.predicate)); const unit = eligible.find(item => !this.recentFamilies.slice(-4).includes(item.wordingFamily)) || eligible[0]; if (!unit) continue; const values = { subject: subjectName(proposition, entities), predicate: clean(proposition.predicate) }; const fill = template => template.replaceAll("{subject}", values.subject).replaceAll("{predicate}", values.predicate); const clauses = [unit.clauses.observation, contract.maximumSentences > 1 ? unit.clauses.consequence : null].filter(Boolean).map(fill); sentences.push(...clauses); usedUnits.push(unit.unitId); families.push(unit.wordingFamily); }
    if (contract.function === "PREDICTION" && contract.questionIntent) sentences.push("What will the next verified change reveal?"); const unique = [...new Set(sentences)].slice(0, contract.maximumSentences), text = unique.join(" "); this.recentStrings = [...this.recentStrings, text].slice(-80); this.recentFamilies = [...this.recentFamilies, ...families].slice(-80); return { text, propositionIds: propositions.map(item => item.propositionId), evidenceIds: [...new Set(propositions.flatMap(item => item.support))], usedUnits, wordingFamilies: families, fallback: false };
  }
}
