import { SITUATION_STATES } from "./schemas.js";

const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
const patterns = Object.freeze({ hunt: "HUNT", predation: "HUNT", flee: "THREAT_RESPONSE", recovery: "RECOVERY", rest: "RECOVERY", drink: "RESOURCE_JOURNEY", water: "RESOURCE_JOURNEY", courtship: "COURTSHIP", mate: "COURTSHIP", care: "PARENTAL_CARE", birth: "PARENTAL_CARE", group: "GROUP_CHANGE", hydrology: "HYDROLOGICAL_CHANGE", environment: "ENVIRONMENTAL_PROCESS", vegetation: "VEGETATION_PRESSURE", weather: "ENVIRONMENTAL_PROCESS" });

export function inferSituationType(proposition) { const text = `${proposition.predicate} ${Object.values(proposition.arguments || {}).join(" ")}`.toLowerCase(); for (const [word, type] of Object.entries(patterns)) if (text.includes(word)) return type; return proposition.subjectIds.length ? "ENTITY_EPISODE" : "WORLD_PROCESS"; }

export class SituationManager {
  constructor({ maximum = 500, idFactory, dormancyTicks = 30, archiveTicks = 600 } = {}) { this.maximum = maximum; this.idFactory = idFactory; this.dormancyTicks = dormancyTicks; this.archiveTicks = archiveTicks; this.items = new Map(); this.byKey = new Map(); this.activeIds = new Set(); this.revision = 0; this.snapshotCache = null; }
  ingest(proposition, claim) { const type = inferSituationType(proposition), key = `${type}:${[...proposition.subjectIds].sort().join("|") || proposition.predicate}`, existingId = this.byKey.get(key); let situation = existingId && this.items.get(existingId); if (!situation) { situation = { situationId: this.idFactory.next("situation"), identityKey: key, type, phase: "DISCOVERY", state: "CANDIDATE", roles: Object.fromEntries(proposition.subjectIds.map((id, index) => [index ? `participant${index + 1}` : "primary", id])), objectives: [], tensions: [], openedAtTick: proposition.validity.fromTick, lastChangedAtTick: proposition.validity.fromTick, propositionIds: [], communicablePropositionIds: [], claimIds: [], openQuestions: [], possibleTransitions: [], importance: proposition.materiality }; this.items.set(situation.situationId, situation); this.byKey.set(key, situation.situationId); } situation.propositionIds = [...situation.propositionIds, proposition.propositionId].slice(-96); if (!proposition.predicate.startsWith("archive_")) situation.communicablePropositionIds = [...situation.communicablePropositionIds, proposition.propositionId].slice(-48); situation.claimIds = [...situation.claimIds, claim.claimId].slice(-96); situation.lastChangedAtTick = proposition.validity.fromTick; situation.importance = clamp01(Math.max(situation.importance, proposition.materiality)); situation.state = situation.state === "CANDIDATE" ? "DEVELOPING" : situation.state === "DORMANT" ? "RETURN_READY" : "ACTIVE"; this.#refreshActive(situation); while (this.items.size > this.maximum) { const id = this.items.keys().next().value, removed = this.items.get(id); this.items.delete(id); this.activeIds.delete(id); if (removed && this.byKey.get(removed.identityKey) === id) this.byKey.delete(removed.identityKey); } this.#changed(); return situation; }
  update(tick) { let changed = false; for (const situation of this.items.values()) { const age = tick - situation.lastChangedAtTick, before = situation.state; if (age >= this.archiveTicks && ["RESOLVED", "INVALIDATED", "DORMANT"].includes(situation.state)) situation.state = "ARCHIVED"; else if (age >= this.dormancyTicks && ["ACTIVE", "DEVELOPING", "RETURN_READY"].includes(situation.state)) situation.state = "DORMANT"; if (before !== situation.state) { changed = true; this.#refreshActive(situation); } } if (changed) this.#changed(); }
  transition(id, state, phase, tick) { const item = this.items.get(id); if (!item || !SITUATION_STATES.includes(state)) return null; item.state = state; if (phase) item.phase = phase; item.lastChangedAtTick = tick; this.#refreshActive(item); this.#changed(); return item; }
  active() { return [...this.activeIds].map(id => this.items.get(id)).filter(Boolean); }
  snapshot() { if (this.snapshotCache?.revision === this.revision) return this.snapshotCache.value; const active = Object.freeze(this.active().map(item => Object.freeze({ ...item }))), byId = new Map(active.map(item => [item.situationId, item])), value = Object.freeze({ revision: this.revision, situations: active, get: id => byId.get(id) || null }); this.snapshotCache = { revision: this.revision, value }; return value; }
  #refreshActive(item) { if (["DEVELOPING", "ACTIVE", "RETURN_READY"].includes(item.state)) this.activeIds.add(item.situationId); else this.activeIds.delete(item.situationId); }
  #changed() { this.revision += 1; this.snapshotCache = null; }
}
