import { CAUSAL_LEVELS, THREAD_PHASES, THREAD_STATES } from "./schemas.js";

const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
const boundedPush = (array, value, maximum) => { array.push(value); if (array.length > maximum) array.splice(0, array.length - maximum); return array; };

export class EvidenceRegistry {
  constructor({ maximum = 6000, idFactory } = {}) { this.maximum = maximum; this.idFactory = idFactory; this.items = new Map(); }
  add({ claim, level = "UNKNOWN", sourceEventIds = [], subjectIds = [], validFromMs = 0, validUntilMs = null, metadata = {} }) { if (!CAUSAL_LEVELS.includes(level)) throw new TypeError(`Unknown causal level ${level}`); const evidenceId = this.idFactory.next("evidence"), item = Object.freeze({ evidenceId, claim: String(claim), level, sourceEventIds: [...sourceEventIds], subjectIds: [...subjectIds], validFromMs, validUntilMs, metadata: { ...metadata } }); this.items.set(evidenceId, item); while (this.items.size > this.maximum) this.items.delete(this.items.keys().next().value); return item; }
  get(id) { return this.items.get(id) || null; }
  active(id, atMs) { const item = this.get(id); return Boolean(item && item.validFromMs <= atMs && (item.validUntilMs == null || item.validUntilMs >= atMs)); }
}

export class CharacterBiographyStore {
  constructor({ maximumSubjects = 1200, maximumEntries = 32 } = {}) { this.maximumSubjects = maximumSubjects; this.maximumEntries = maximumEntries; this.subjects = new Map(); this.evictionQueue = []; this.evictionHead = 0; }
  observe(subject, event) { if (!subject?.id) return null; let biography = this.subjects.get(subject.id); if (!biography) { biography = { subjectId: subject.id, label: subject.label || subject.name || subject.id, speciesId: subject.speciesId || null, lineage: {}, affiliations: [], entries: [], summary: "", lastSeenMs: 0 }; this.subjects.set(subject.id, biography); } biography.lastSeenMs = event.recordingTimeMs || biography.lastSeenMs; this.evictionQueue.push({ subjectId: subject.id, lastSeenMs: biography.lastSeenMs }); boundedPush(biography.entries, { eventId: event.recordId, type: event.payload?.type, timeMs: event.recordingTimeMs, importance: clamp01(event.payload?.importance), evidence: [...(event.evidence || [])] }, this.maximumEntries); if (subject.motherId) biography.lineage.motherId = subject.motherId; if (subject.fatherId) biography.lineage.fatherId = subject.fatherId; if (subject.groupId && !biography.affiliations.includes(subject.groupId)) boundedPush(biography.affiliations, subject.groupId, 12); biography.summary = `${biography.label}: ${biography.entries.slice(-5).map(item => item.type).join(", ")}`; this.trim(); return biography; }
  get(subjectId) { return this.subjects.get(subjectId) || null; }
  trim() { while (this.subjects.size > this.maximumSubjects && this.evictionHead < this.evictionQueue.length) { const candidate = this.evictionQueue[this.evictionHead++], current = this.subjects.get(candidate.subjectId); if (current?.lastSeenMs === candidate.lastSeenMs) this.subjects.delete(candidate.subjectId); } const liveQueueLength = this.evictionQueue.length - this.evictionHead, compactAt = Math.max(1024, this.subjects.size * 4); if (this.evictionHead > 1024 && this.evictionHead * 2 > this.evictionQueue.length || liveQueueLength > compactAt) { this.evictionQueue = [...this.subjects.values()].map(item => ({ subjectId: item.subjectId, lastSeenMs: item.lastSeenMs })).sort((left, right) => left.lastSeenMs - right.lastSeenMs); this.evictionHead = 0; } }
}

export class PromiseLedger {
  constructor({ idFactory, recorder, maximum = 500 } = {}) { this.idFactory = idFactory; this.recorder = recorder; this.maximum = maximum; this.items = new Map(); }
  open({ threadId, question, dueMs = null, sourceId = null }) { const promise = { promiseId: this.idFactory.next("promise"), threadId, question, status: "OPEN", openedAtMs: this.recorder.time(), dueMs, sourceId, updates: [] }; this.items.set(promise.promiseId, promise); this.recorder.write("promise", { ...promise }); this.trim(); return promise; }
  update(promiseId, status, detail = null) { const item = this.items.get(promiseId); if (!item) return null; item.status = status; item.updatedAtMs = this.recorder.time(); boundedPush(item.updates, { timeMs: item.updatedAtMs, status, detail }, 20); this.recorder.write("promise", { ...item }); return item; }
  overdue(atMs = this.recorder.time()) { return [...this.items.values()].filter(item => item.status === "OPEN" && Number.isFinite(item.dueMs) && item.dueMs < atMs); }
  trim() { while (this.items.size > this.maximum) this.items.delete(this.items.keys().next().value); }
}

export class PredictionTracker {
  constructor({ idFactory, recorder, maximum = 500 } = {}) { this.idFactory = idFactory; this.recorder = recorder; this.maximum = maximum; this.items = new Map(); }
  create({ threadId, statement, confidence, horizonMs, evidenceIds = [], outcomes = [] }) { const prediction = { predictionId: this.idFactory.next("prediction"), threadId, statement, confidence: clamp01(confidence), horizonMs, evidenceIds: [...evidenceIds], outcomes: [...outcomes], status: "OPEN", createdAtMs: this.recorder.time(), resolvedOutcome: null }; this.items.set(prediction.predictionId, prediction); this.recorder.write("prediction", { ...prediction }, { evidence: evidenceIds }); while (this.items.size > this.maximum) this.items.delete(this.items.keys().next().value); return prediction; }
  resolve(predictionId, outcome, evidenceIds = []) { const item = this.items.get(predictionId); if (!item || item.status !== "OPEN") return null; item.status = "RESOLVED"; item.resolvedOutcome = outcome; item.resolvedAtMs = this.recorder.time(); item.resolutionEvidenceIds = [...evidenceIds]; this.recorder.write("prediction", { ...item }, { evidence: evidenceIds }); return item; }
  expire(atMs = this.recorder.time()) { for (const item of this.items.values()) if (item.status === "OPEN" && item.createdAtMs + item.horizonMs < atMs) { item.status = "EXPIRED"; item.resolvedAtMs = atMs; this.recorder.write("prediction", { ...item }); } }
}

const DEFAULT_SCORE_WEIGHTS = Object.freeze({ activity: .13, stakes: .16, uncertainty: .11, causalSignificance: .09, novelty: .1, relationshipRelevance: .08, historicalSignificance: .07, audienceInvestment: .08, readiness: .06, visualClarity: .06, productionFeasibility: .06 });

export function scoreStoryThread(thread, weights = DEFAULT_SCORE_WEIGHTS, nowMs = 0) {
  let total = 0; const breakdown = {};
  for (const [key, weight] of Object.entries(weights)) { const contribution = clamp01(thread.scores?.[key]) * weight; breakdown[key] = contribution; total += contribution; }
  const recency = Math.exp(-Math.max(0, nowMs - (thread.lastDevelopedAtMs || nowMs)) / 120000), switchingPenalty = clamp01(thread.switchingCost) * .12, repetitionPenalty = clamp01(thread.repetition) * .08;
  breakdown.recency = recency * .08; breakdown.switchingPenalty = -switchingPenalty; breakdown.repetitionPenalty = -repetitionPenalty;
  return { total: clamp01(total + breakdown.recency - switchingPenalty - repetitionPenalty), breakdown };
}

export class StoryThreadManager {
  constructor({ idFactory, recorder, maximum = 160, inactivityMs = 90000, archiveMs = 600000 } = {}) { this.idFactory = idFactory; this.recorder = recorder; this.maximum = maximum; this.inactivityMs = inactivityMs; this.archiveMs = archiveMs; this.threads = new Map(); this.eventToThread = new Map(); this.byCorrelationKey = new Map(); this.bySubject = new Map(); this.revision = 0; this.rankedCache = null; }
  createFromEvent(event, overrides = {}) { const now = event.recordingTimeMs, subjectIds = [...new Set(event.payload.subjectIds || [])], key = overrides.correlationKey || `${event.payload.type}:${subjectIds.slice().sort().join("|")}`, existing = this.threads.get(this.byCorrelationKey.get(key)); if (existing && !["ARCHIVED", "INVALIDATED"].includes(existing.status)) return this.develop(existing.threadId, event, overrides);
    const thread = { threadId: this.idFactory.next("thread"), correlationKey: key, title: overrides.title || event.payload.title || event.payload.type.replaceAll("_", " "), question: overrides.question || event.payload.question || `How will ${event.payload.type.replaceAll("_", " ")} develop?`, subjectIds, status: "CANDIDATE", phase: "DISCOVERY", originEventId: event.recordId, recentEventIds: [event.recordId], evidenceIds: [...event.evidence], hypotheses: [], causalLinks: [], promiseIds: [], predictionIds: [], scores: { activity: .4, stakes: clamp01(event.payload.importance), uncertainty: .6, causalSignificance: .3, novelty: clamp01(event.payload.novelty ?? .5), relationshipRelevance: subjectIds.length > 1 ? .6 : .2, historicalSignificance: .2, audienceInvestment: 0, readiness: .35, visualClarity: clamp01(event.payload.visualClarity ?? .6), productionFeasibility: clamp01(event.payload.productionFeasibility ?? .7) }, switchingCost: 0, repetition: 0, createdAtMs: now, firstShownAtMs: null, lastShownAtMs: null, lastDevelopedAtMs: now, minimumReturnByMs: null, summary: overrides.summary || event.payload.summary || "" }; this.threads.set(thread.threadId, thread); this.byCorrelationKey.set(key, thread.threadId); for (const id of subjectIds) addIndex(this.bySubject, String(id), thread.threadId); this.eventToThread.set(event.recordId, thread.threadId); this.#changed(); this.record(thread); this.trim(); return thread;
  }
  develop(threadId, event, overrides = {}) { const thread = this.threads.get(threadId); if (!thread) return null; boundedPush(thread.recentEventIds, event.recordId, 48); thread.evidenceIds = [...new Set([...thread.evidenceIds, ...(event.evidence || [])])].slice(-96); const previousSubjects = new Set(thread.subjectIds), nextSubjects = [...new Set([...thread.subjectIds, ...(event.payload.subjectIds || [])])]; thread.subjectIds = nextSubjects; for (const id of nextSubjects) if (!previousSubjects.has(id)) addIndex(this.bySubject, String(id), thread.threadId); thread.lastDevelopedAtMs = event.recordingTimeMs; if (["CANDIDATE", "DORMANT", "RETURN_READY"].includes(thread.status)) thread.status = thread.status === "CANDIDATE" ? "DEVELOPING" : "RETURN_READY"; if (overrides.phase && THREAD_PHASES.includes(overrides.phase)) thread.phase = overrides.phase; for (const [key, value] of Object.entries(overrides.scores || {})) thread.scores[key] = clamp01(value); this.eventToThread.set(event.recordId, thread.threadId); this.#changed(); this.record(thread); return thread; }
  transition(threadId, status, phase = null, reason = "deterministic-transition") { const thread = this.threads.get(threadId); if (!thread || !THREAD_STATES.includes(status) || phase && !THREAD_PHASES.includes(phase)) return null; thread.status = status; if (phase) thread.phase = phase; thread.transitionReason = reason; thread.transitionedAtMs = this.recorder.time(); this.#changed(); this.record(thread); return thread; }
  markShown(threadId) { const thread = this.threads.get(threadId); if (!thread) return null; const now = this.recorder.time(); thread.firstShownAtMs ??= now; thread.lastShownAtMs = now; thread.scores.audienceInvestment = clamp01(thread.scores.audienceInvestment + .08); thread.status = "ACTIVE"; this.#changed(); this.record(thread); return thread; }
  update(atMs = this.recorder.time()) { for (const thread of this.threads.values()) { const age = atMs - thread.lastDevelopedAtMs; if (["ACTIVE", "DEVELOPING", "RETURN_READY"].includes(thread.status) && age > this.inactivityMs) this.transition(thread.threadId, "DORMANT", null, "inactivity"); if (["RESOLVED", "CONSEQUENCE", "DORMANT"].includes(thread.status) && age > this.archiveMs) this.transition(thread.threadId, "ARCHIVED", null, "archive-window"); } }
  ranked(nowMs = this.recorder.time()) { const key = `${this.revision}|${nowMs}`; if (this.rankedCache?.key === key) return this.rankedCache.value; const value = [...this.threads.values()].filter(thread => !["ARCHIVED", "INVALIDATED"].includes(thread.status)).map(thread => ({ thread, ...scoreStoryThread(thread, DEFAULT_SCORE_WEIGHTS, nowMs) })).sort((a, b) => b.total - a.total); this.rankedCache = { key, value }; return value; }
  rankedOnce(nowMs = this.recorder.time()) { return this.ranked(nowMs); }
  topRanked(maximum = 1, nowMs = this.recorder.time()) { const limit = Math.max(0, Math.floor(Number(maximum) || 0)); if (!limit) return []; const top = []; for (const thread of this.threads.values()) { if (["ARCHIVED", "INVALIDATED"].includes(thread.status)) continue; const candidate = { thread, ...scoreStoryThread(thread, DEFAULT_SCORE_WEIGHTS, nowMs) }; let index = top.findIndex(item => candidate.total > item.total); if (index < 0) index = top.length; top.splice(index, 0, candidate); if (top.length > limit) top.pop(); } return top; }
  top(maximum = 1, nowMs = this.recorder.time()) { return this.topRanked(maximum, nowMs); }
  forSubject(subjectId) { return [...(this.bySubject.get(String(subjectId)) || [])].map(id => this.threads.get(id)).filter(Boolean); }
  get(threadId) { return this.threads.get(threadId) || null; }
  record(thread) { this.recorder.write("story_thread", { ...thread, scores: { ...thread.scores } }, { evidence: thread.evidenceIds }); }
  trim() { while (this.threads.size > this.maximum) { let candidate = null; for (const item of this.threads.values()) if (item.status !== "ACTIVE" && (!candidate || item.lastDevelopedAtMs < candidate.lastDevelopedAtMs)) candidate = item; if (!candidate) break; this.#remove(candidate); } }
  #remove(thread) { this.threads.delete(thread.threadId); if (this.byCorrelationKey.get(thread.correlationKey) === thread.threadId) this.byCorrelationKey.delete(thread.correlationKey); for (const id of thread.subjectIds) deleteIndex(this.bySubject, String(id), thread.threadId); this.#changed(); }
  #changed() { this.revision += 1; this.rankedCache = null; }
}

function addIndex(index, key, value) { let values = index.get(key); if (!values) { values = new Set(); index.set(key, values); } values.add(value); }
function deleteIndex(index, key, value) { const values = index.get(key); if (!values) return; values.delete(value); if (!values.size) index.delete(key); }
