import { BoundedTimeline, DocumentaryClock, DocumentaryEventBus, DocumentaryIdFactory, DocumentaryRecorder, RangeTracker, simulationTimeSnapshot } from "./core.js";
import { CharacterBiographyStore, EvidenceRegistry, PredictionTracker, PromiseLedger, StoryThreadManager } from "./story.js";
import { DocumentaryPortfolioDirector, EditorialWindowTracker, MetadataReplayBuffer, ShotStateMachine } from "./editorial.js";
import { NarrationQueue, TopicMemory, buildNarrationPacket, fallbackNarration, validateNarrationResult } from "./narration.js";
import { CompanionClient } from "./persistence.js";
import { PredictiveDocumentaryAuthor } from "../documentary-author/index.js";
import { ACSSPredictiveAuthor } from "../documentary-author-v3/index.js";

const sessionId = seed => `run-${new Date().toISOString().replace(/[:.]/g, "-")}-${String(seed ?? "world")}`;
const createAuthor = (mode, flags = {}) => String(mode).startsWith("V3_") ? new ACSSPredictiveAuthor({ mode }) : new PredictiveDocumentaryAuthor({ mode, flags });
const AUTHOR_RECORD_TYPES = new Set(["author_evidence_batch", "author_belief_revision", "author_situation_transition", "author_model_graph", "author_forecast_opened", "author_forecast_resolved", "author_plan_proposed", "author_decision_executed", "author_shadow_comparison", "author_presentation_outcome", "author_learning_attribution", "author_profile_delta", "author_profile_commit"]);

export class DocumentarySystem {
  constructor({ simulation = () => ({}), companion = {}, timelineMaximum = 4000, authorMode = "V3_SHADOW", authorFlags = {} } = {}) { this.simulation = simulation; this.events = new DocumentaryEventBus(); this.clock = new DocumentaryClock(); this.ids = new DocumentaryIdFactory("idle"); this.timeline = new BoundedTimeline({ maximum: timelineMaximum, onRecord: record => { this.replay?.push(record); this.client?.enqueue(record); this.events.emit("record", record); } }); this.client = new CompanionClient(companion); this.active = false; this.capabilities = new Map(); this.authorMode = authorMode; this.authorFlags = authorFlags; this.author = createAuthor(authorMode, authorFlags); }
  setAuthorMode(mode) { const familyChanged = String(this.author?.mode || "").startsWith("V3_") !== String(mode).startsWith("V3_"); this.authorMode = mode; if (familyChanged) this.author = createAuthor(mode, this.authorFlags); else if (typeof this.author.setExecutionMode === "function") this.author.setExecutionMode(mode); else this.author.mode = mode; return this.author; }
  async initialise() { if (!this.clientSubscribed) { this.clientSubscribed = true; this.client.on(message => this.handleCompanion(message)); } await this.author.hydrateProfile?.().catch(() => null); const connected = await this.client.connect().catch(() => false); if (connected && String(this.author.mode).startsWith("V3_")) try { const remote = await this.client.requestAndWait("AUTHOR_PROFILE_LOAD", { profileId: this.author.profileStore?.profileId || "default" }, { responseType: "AUTHOR_PROFILE_LOADED", timeoutMs: 5000 }); if (remote.snapshot) this.author.importLearningProfile?.(remote.snapshot); } catch {} return this; }
  async start({ title = "Living Laboratory documentary", recordingMode = "manual", metadata = {} } = {}) {
    if (this.active) return this.manifest;
    const sim = this.simulation(), id = sessionId(sim.seed), requestedMode = metadata.configuration?.authorMode || this.authorMode;
    this.ids = new DocumentaryIdFactory(id); this.setAuthorMode(requestedMode); this.clock.start(0);
    this.recorder = new DocumentaryRecorder({ sessionId: id, clock: this.clock, simulationTime: () => simulationTimeSnapshot(this.simulation()), timeline: this.timeline, idFactory: this.ids });
    this.author.setRecordSink?.(trace => { const recordType = AUTHOR_RECORD_TYPES.has(trace.type) ? trace.type : "production_event", payload = recordType === "production_event" ? { type: "ACSS_INTERNAL_RECORD", authorRecordType: trace.type, authorTraceId: trace.traceId, authorTick: trace.tick, payload: trace.payload } : { ...trace.payload, authorTraceId: trace.traceId, authorTick: trace.tick }; this.recorder?.write(recordType, payload, { evidence: trace.payload?.evidenceIds || [] }); if (trace.type === "author_profile_commit" && this.client.connected && trace.payload?.snapshot) this.client.request("AUTHOR_PROFILE_COMMIT", { profileId: trace.payload.profileId || "default", snapshot: trace.payload.snapshot }); });
    this.ranges = new RangeTracker({ idFactory: this.ids, record: this.recorder }); this.evidence = new EvidenceRegistry({ idFactory: this.ids }); this.biographies = new CharacterBiographyStore(); this.promises = new PromiseLedger({ idFactory: this.ids, recorder: this.recorder }); this.predictions = new PredictionTracker({ idFactory: this.ids, recorder: this.recorder }); this.stories = new StoryThreadManager({ idFactory: this.ids, recorder: this.recorder }); this.director = new DocumentaryPortfolioDirector({ idFactory: this.ids, recorder: this.recorder }); this.editorial = new EditorialWindowTracker({ idFactory: this.ids, recorder: this.recorder }); this.replay = new MetadataReplayBuffer(); this.shots = new ShotStateMachine(); this.narration = new NarrationQueue(); this.topics = new TopicMemory();
    const authorSession = this.author.beginSession?.({ sessionId: id, simulationSeed: sim.seed, tick: sim.tick || 0 }), authorHealth = this.author.health?.() || {};
    this.manifest = { title, status: "RECORDING", recordingMode, simulationSeed: sim.seed ?? null, simulationVersion: metadata.simulationVersion || "browser", configuration: { ...(metadata.configuration || {}), authorMode: this.author.mode }, authorProfileRevision: authorHealth.learningRevision || 0, authorRegistryVersion: this.author.learning?.registryVersion || null, authorProfileChecksum: authorSession?.profileChecksum || null, authorLifecycle: authorHealth.lifecycle || null, authorControlActive: authorHealth.controlActive || false, audienceProfileRevision: authorHealth.audience?.revision || 0, startedAtUtc: new Date().toISOString(), sessionId: id };
    this.active = true; this.recorder.write("session_manifest", this.manifest); if (this.client.connected) await this.client.requestAndWait("START_SESSION", { sessionId: id, metadata: this.manifest }, { responseType: "SESSION_STARTED" }); return this.manifest;
  }
  stop(reason = "operator-stop", { timeoutMs = 20000 } = {}) { if (!this.active) return this.finalization || null; this.ranges.closeAll(reason); this.editorial.close(); this.predictions.expire(); const sim = this.simulation(), authorSession = this.author.endSession?.({ reason, tick: sim.tick || 0 }); if (authorSession) this.recorder.write("production_event", { type: "AUTHOR_SESSION_ENDED", reason, authorSession }); const elapsedMs = this.clock.stop(); this.manifest = { ...this.manifest, status: "FINALIZING", stoppedAtUtc: new Date().toISOString(), elapsedMs, reason }; this.recorder.write("session_manifest", this.manifest); const sessionId = this.manifest.sessionId; this.active = false; this.finalization = (async () => { await this.author.flushPersistence?.(); if (this.client.connected && String(this.author.mode).startsWith("V3_")) await this.client.requestAndWait("AUTHOR_PROFILE_COMMIT", { profileId: this.author.profileStore?.profileId || "default", snapshot: this.author.learning.snapshot() }, { responseType: "AUTHOR_PROFILE_COMMITTED", timeoutMs: Math.min(timeoutMs, 10000) }).catch(() => null); await this.client.flush(); if (!this.client.connected) { this.manifest = { ...this.manifest, status: "COMPLETE", finalizationMode: "local-metadata" }; return this.manifest; } const response = await this.client.requestAndWait("STOP_SESSION", { sessionId, reason }, { responseType: "SESSION_STOPPED", timeoutMs }); this.manifest = { ...this.manifest, status: "COMPLETE", finalizationMode: "companion" }; return response; })(); this.finalization.status = this.client.connected ? "FINALIZING" : "COMPLETE"; return this.finalization; }
  stopBestEffort(reason = "page-unload") { if (!this.active) return false; const sessionId = this.manifest?.sessionId; this.active = false; return this.client.bestEffort({ schemaVersion: 1, type: "STOP_SESSION", requestId: `unload-${Date.now()}`, sessionId, reason }); }
  observe(type, { state = "CONFIRMED", subjectIds = [], title = null, question = null, importance = .5, novelty = .5, visualClarity = .6, productionFeasibility = .7, facts = [], metadata = {} } = {}) { if (!this.active) return null; const evidence = facts.map(fact => this.evidence.add({ claim: fact.claim, level: fact.level || "DIRECT", sourceEventIds: [], subjectIds, validFromMs: this.recorder.time(), metadata: fact.metadata })).map(item => item.evidenceId); const event = this.recorder.write("documentary_event", { type, state, subjectIds, title, question, importance, novelty, visualClarity, productionFeasibility, metadata }, { evidence }); const thread = this.stories.createFromEvent(event, { title, question, correlationKey: metadata.correlationKey }); for (const id of subjectIds) { const subject = (this.simulation().animals || []).find(animal => animal.id === id); if (subject) this.biographies.observe(subject, event); } this.events.emit("event", { event, thread }); return { event, thread }; }
  tick({ editorial = null } = {}) { if (!this.active) return null; const now = this.recorder.time(); this.stories.update(now); this.predictions.expire(now); this.narration.expire(now); if (editorial) this.editorial.sample(editorial, now); const ranked = this.stories.rankedOnce(now); if (now - (this.lastCheckpointMs || 0) >= 60000) { this.lastCheckpointMs = now; const checkpoint = { checkpointId: this.ids.next("checkpoint"), sessionId: this.manifest.sessionId, recordingTimeMs: now, simulationTime: simulationTimeSnapshot(this.simulation()), recordCount: this.timeline.records.length, activeThreadIds: ranked.slice(0, 12).map(item => item.thread.threadId), health: this.health() }; this.recorder.write("session_checkpoint", checkpoint); this.client.request("CHECKPOINT", { sessionId: this.manifest.sessionId, checkpoint }); } return this.director.choose(ranked, { nowMs: now }); }
  cameraDecision(status, payload) { if (!this.active) return null; return this.recorder.write("camera_decision", { decisionId: payload.decisionId || this.ids.next("camera"), status, reason: payload.reason || "movie-director", ...payload }, { evidence: payload.evidence || [] }); }
  manualMarker(kind, note = "", extra = {}) { if (!this.active) return null; return this.recorder.write("manual_marker", { markerId: this.ids.next("marker"), kind, note, ...extra }); }
  makeNarrationRequest(input) { if (!this.active || this.narration.nowPlaying || this.narration.ready.length) return null; const requestId = this.ids.next("narration-request"), packet = buildNarrationPacket({ ...input, requestId }); if (!this.narration.begin({ requestId, packet, expiresAtMs: packet.deadlineMs })) return null; this.recorder.write("narration_request", packet, { evidence: packet.verifiedFacts.flatMap(item => item.evidenceIds) }); this.recorder.write("production_event", { type: "CONTROLLED_FACTUAL_ACCOUNT", requestId, function: packet.function, chapterWindow: packet.chapterWindow, controlledAccount: packet.controlledAccount, perspective: packet.perspective }); this.client.request("NARRATION_REQUEST", { sessionId: this.manifest.sessionId, packet }); return packet; }
  approveNarration(result, packet, knownSubjects = new Map()) { const validation = validateNarrationResult(result, packet, { nowMs: this.recorder.time(), knownSubjects }), approved = validation.valid ? result : fallbackNarration(packet); this.recorder.write("narration_result", { requestId: packet.requestId, text: approved.text, claims: approved.claims, validation, fallback: Boolean(approved.fallback) }, { evidence: approved.claims.flatMap(claim => claim.supportIds || []) }); this.narration.readyItem(packet.requestId, { ...approved, validation, expiresAtMs: packet.deadlineMs }); return { approved, validation }; }
  authorCycle(input = {}) { const sim = this.simulation(), result = this.author.cycle({ ...input, simulation: input.simulation || sim, tick: input.tick ?? sim.tick ?? 0, simulationTimeMinutes: input.simulationTimeMinutes ?? sim.ecologicalMinute ?? 0, recordingTimeMs: input.recordingTimeMs ?? (this.active ? this.recorder.time() : performance.now()), entities: input.entities || new Map((sim.animals || []).map(animal => [animal.id, animal])) }); if (this.active) this.recorder.write("production_event", { type: "PREDICTIVE_AUTHOR_DECISION", mode: result.mode, decision: result.decision, narrationContract: result.narration, cameraIntention: result.camera, validation: result.validation, realised: result.realised }, { evidence: result.realised?.evidenceIds || [] }); return result; }
  selectAuthorPresentation(input = {}) { if (typeof this.author.selectPresentation !== "function") return null; const result = this.author.selectPresentation({ ...input, simulation: input.simulation || this.simulation(), tick: input.tick ?? this.simulation().tick ?? 0 }); if (result && this.active) this.recorder.write("production_event", { type: "ACSS_PRESENTATION_SELECTED", mode: this.author.mode, decision: result.contract?.decision, contract: result.contract, modelGraph: result.plan?.ensemble ? { rootModelId: result.plan.ensemble.rootModelId, confidence: result.plan.ensemble.confidence, dependencies: result.contract?.dependencies } : null }); return result; }
  observeAuthorSnapshot(input = {}) { return this.author.observe?.(input.simulation || this.simulation(), { scenes: input.scenes || [], tick: input.tick ?? this.simulation().tick ?? 0 }) || null; }
  completeAuthorPresentation(input = {}) { const marked = this.author.markPresented?.(input, { tick: input.tick ?? this.simulation().tick ?? 0 }); const beat = this.author.completeCurrentBeat?.({ outcomeChanged: input.outcomeChanged, shown: input.shown !== false, narratedClaimIds: input.claimIds || input.propositionIds || [], tick: input.tick ?? this.simulation().tick ?? 0, skipReason: input.skipReason || null }); return { marked, beat }; }
  registerAudiencePresentation(input = {}) { const result = this.author.registerAudiencePresentation?.(input); if (result && this.active) this.recorder.write("production_event", { type: "AUDIENCE_PRESENTATION_REGISTERED", presentation: result }); return result; }
  recordAudienceFeedback(input = {}) { const result = this.author.audienceFeedback?.(input); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-feedback"), kind: "AUDIENCE_FEEDBACK", feedback: result }); return result; }
  retractAudienceFeedback(feedbackId) { const result = this.author.retractAudienceFeedback?.(feedbackId); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-feedback-retraction"), kind: "AUDIENCE_FEEDBACK_RETRACTED", feedback: result }); return result; }
  recordImplicitAudienceSignal(input = {}) { const result = this.author.audienceImplicit?.(input); if (result && this.active) this.recorder.write("production_event", { type: "AUDIENCE_IMPLICIT_SIGNAL", signal: result }); return result; }
  recordAudienceFault(input = {}, metrics = {}) { const result = this.author.audienceFault?.(input, metrics); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-fault"), kind: "AUDIENCE_FAULT", report: result.report || result }); return result; }
  interpretAudienceFeedback(text) { return this.author.audienceWritten?.(text) || null; }
  confirmAudienceWrittenFeedback(parsed, tags, presentationId, options = {}) { const result = this.author.audienceConfirmWritten?.(parsed, tags, presentationId, options); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-written"), kind: "AUDIENCE_WRITTEN_FEEDBACK", feedback: result }); return result; }
  requestAudiencePrompt(context = {}) { return this.author.audiencePrompt?.(context) || null; }
  answerAudiencePrompt(question, answer, options = {}) { const result = this.author.audienceAnswerPrompt?.(question, answer, options); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-prompt-answer"), kind: "AUDIENCE_PROMPT_ANSWER", answer: result }); return result; }
  primeAudience(answers = {}, options = {}) { const result = this.author.audiencePriming?.(answers, options); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-priming"), kind: "AUDIENCE_PRIMING", result }); return result; }
  compareAudiencePreference(input = {}) { const result = this.author.audienceComparison?.(input); if (result && this.active) this.recorder.write("manual_marker", { markerId: this.ids.next("audience-comparison"), kind: "AUDIENCE_PAIRWISE_PREFERENCE", result }); return result; }
  skipAudiencePriming() { return this.author.skipAudiencePriming?.() || null; }
  clearAudienceSession() { return this.author.clearAudienceSession?.() || null; }
  audienceProfiles() { return this.author.audienceProfiles?.() || []; }
  createAudienceProfile(displayName, options = {}) { return this.author.createAudienceProfile?.(displayName, options) || null; }
  selectAudienceProfile(profileId) { return this.author.selectAudienceProfile?.(profileId) || null; }
  handleCompanion(message) { if (message.type === "CLOCK_SYNC" && this.active) this.clock.applySync(message.serverElapsedMs); if (message.type === "NARRATION_READY" && this.active) { const generating = this.narration.generating.find(item => item.requestId === message.requestId); if (generating) this.approveNarration(message.result, generating.packet, new Map((this.simulation().animals || []).map(animal => [animal.id, animal]))); } if (message.type === "SESSION_STOPPED") this.client.close(); this.events.emit("companion", message); }
  health() { return { active: this.active, sessionId: this.manifest?.sessionId || null, companion: this.client.connected, connectionState: this.client.state, finalizing: Boolean(this.finalization && this.manifest?.status === "FINALIZING"), timelineRecords: this.timeline.records.length, timelineDropped: this.timeline.dropped, activeRanges: this.ranges?.active.size || 0, threads: this.stories?.threads.size || 0, narration: { generating: this.narration?.generating.length || 0, ready: this.narration?.ready.length || 0, playing: Boolean(this.narration?.nowPlaying) }, predictiveAuthor: this.author.health() }; }
}

export * from "./schemas.js";
export * from "./core.js";
export * from "./story.js";
export * from "./editorial.js";
export * from "./narration.js";
export * from "./persistence.js";
