import test from "node:test";
import assert from "node:assert/strict";
import { captureDocumentarySnapshot } from "../src/documentary-author/evidence/snapshot-adapter.js";
import { communicationEvidenceAdapter } from "../src/documentary-author/evidence/adapters.js";
import { ObservationTransactionRuntime } from "../src/documentary-author/runtime/observation-transaction.js";
import { PerformanceBudgetTracker } from "../src/documentary-author/runtime/performance-budget.js";
import { compileDocumentaryPolicy, policyAllowsScene } from "../src/documentary-author/planning/policy-compiler.js";
import { validatePresentationContract } from "../src/documentary-author/presentation/contract-validator.js";
import { CameraHorizonPlanner, CameraPresentationSession } from "../src/documentary-author/presentation/camera-horizon-planner.js";
import { CameraMetricAccumulator } from "../src/documentary-author/presentation/camera-metric-accumulator.js";
import { observableSpeakerFocus, realiseDeterministicContract } from "../src/documentary-author/presentation/deterministic-narration-adapter.js";
import { DocumentaryAudienceMemory } from "../src/documentary-author-v3/audience-memory.js";
import { ACSSPredictiveAuthor, AuthorLearningProfile, BrowserAuthorProfileStore, PredictionModelRegistry } from "../src/documentary-author-v3/index.js";

const entity = (id = "A") => ({ id, name: `Animal ${id}`, alive: true, x: 2, z: 3, energy: 70, hydration: 60, fatigue: 10, actionState: { key: "travel", targetId: "water-1" }, needDependencyPlan: { needId: "water", satisfierId: "drink", methodId: "drink-confirmed-shoreline", phase: "travel" }, memories: [{ kind: "water", confidence: .8 }] });
const scene = { id: "activity:A", kind: "activity", ids: ["A"], semanticRoleIds: ["A"], focus: { x: 2, z: 3 }, importance: 70, actionKey: "travel" };

test("documentary snapshots detach every authored read from mutable simulation objects", () => { const source = { tick: 1, animals: [entity()], corpses: [{ id: "corpse-B", sourceId: "B", sourceName: "Animal B", x: 4, z: 5, stage: "skeleton" }] }, snapshot = captureDocumentarySnapshot(source, { scenes: [scene] }); source.animals[0].name = "Mutated"; source.animals[0].memories[0].confidence = 0; source.corpses[0].sourceName = "Lost"; assert.equal(snapshot.entities.get("A").name, "Animal A"); assert.equal(snapshot.entities.get("A").memories[0].confidence, .8); assert.equal(snapshot.corpses.get("corpse-B").name, "Animal B"); assert.throws(() => { snapshot.entities.get("A").position.x = 99; }, TypeError); });

test("Cinema evidence captures the canonical observable face and only a current public call", () => {
  const animal = { ...entity(), fear: 86, socialSignal: { kind: "threat", urgency: 91, sourceId: "A", since: 8, until: 20 }, vocalUntil: 14 };
  const current = captureDocumentarySnapshot({ tick: 12, animals: [animal] }), subject = current.entities.get("A");
  assert.deepEqual(subject.expression, { kind: "fear", observable: true });
  assert.deepEqual(subject.calls.emitted, { kind: "threat", urgency: 91, sourceId: "A", targetId: null, inferredTargetId: null, since: 8, until: 20, channel: null, vocal: true });
  const communication = communicationEvidenceAdapter.observe(current).filter(row => row.subjectIds.includes("A"));
  assert.ok(communication.length >= 2);
  assert.ok(communication.every(row => row.epistemicClass === "OBSERVED"));
  const expired = captureDocumentarySnapshot({ tick: 21, animals: [animal] }).entities.get("A");
  assert.equal(expired.calls.emitted, null);
  const historicalOnly = captureDocumentarySnapshot({ tick: 21, animals: [{ ...entity(), lastCall: { kind: "threat", urgency: 80 } }] }).entities.get("A");
  assert.equal(historicalOnly.calls.emitted, null);
});

test("Cinema speaker focus exposes licensed outward cues without carrying private thought", () => {
  const claims = [
    { claimId: "expression", predicate: "entity.expression.current", subjectIds: ["A"], normalizedArguments: { expression: { kind: "fear", observable: true } } },
    { claimId: "call", predicate: "entity.communication.current", subjectIds: ["A"], normalizedArguments: { emitted: { kind: "threat", urgency: 91, vocal: true } } }
  ];
  const focus = observableSpeakerFocus(claims, { subjectIds: ["A"], narration: { subjectIds: ["A"] }, camera: { primarySubjects: ["A"] } });
  assert.deepEqual(focus, { subjectId: "A", basis: "OBSERVABLE_CALL", expression: { kind: "fear", label: null, observable: true }, call: { kind: "threat", urgency: 91, channel: null, vocal: true, observable: true }, privateThought: null });
  assert.equal(JSON.stringify(focus).includes("priority"), false);
});

test("Cinema narration describes expression and call as public evidence rather than private cognition", () => {
  const policy = compileDocumentaryPolicy({});
  const expression = { claimId: "expression", predicate: "entity.expression.current", subjectIds: ["A"], normalizedArguments: { expression: { kind: "fear", observable: true } }, evidenceIds: ["e-expression"], validFromTick: 1, validUntilTick: null };
  const call = { claimId: "call", predicate: "entity.communication.current", subjectIds: ["A"], normalizedArguments: { emitted: { kind: "threat", urgency: 91, vocal: true } }, evidenceIds: ["e-call"], validFromTick: 1, validUntilTick: null };
  const claims = new Map([[expression.claimId, expression], [call.claimId, call]]), evidence = { get: id => ["e-expression", "e-call"].includes(id) ? { evidenceId: id } : null };
  const contract = { decision: { decisionId: "d" }, situationId: "s", threadId: "t", subjectIds: ["A"], allowedClaimIds: ["expression", "call"], narration: { mode: "SPEAK", subjectIds: ["A"], allowedClaimIds: ["expression", "call"], maximumSentences: 2, requireNewInformation: false }, camera: { primarySubjects: ["A"], secondarySubjects: [], preferredFamilies: ["still"], allowedFamilies: ["still"], minimumHoldSeconds: 1, preferredHoldSeconds: 2 } };
  const realised = realiseDeterministicContract({ contract, context: { tick: 2 }, propositions: { get: id => claims.get(id), valid: id => claims.has(id) }, evidence, policy });
  assert.match(realised.text, /visibly shows fear/i);
  assert.match(realised.text, /not evidence of a private thought/i);
  assert.match(realised.text, /threat public signal/i);
  assert.equal(realised.speakerFocus.subjectId, "A");
  assert.equal(realised.speakerFocus.call.kind, "threat");
});

test("observation transactions survive consecutive revisions without freezing internal situation state", () => { const simulation = { tick: 1, animals: [entity()], corpses: [] }, runtime = new ObservationTransactionRuntime(); const first = runtime.observe(simulation, { scenes: [scene] }); simulation.tick = 2; simulation.animals[0].x = 3; const second = runtime.observe(simulation, { scenes: [scene] }); assert.equal(first.revision, 1); assert.equal(second.revision, 2); assert.ok(second.situations.forScene(scene.id)); assert.ok(second.propositions.records.length > 0); });

test("runtime performance budgets expose rolling median and p95 breaches", () => { const tracker = new PerformanceBudgetTracker({ budgets: { planningTransaction: { medianMs: 8, p95Ms: 25 } }, maximumSamples: 16 }); for (const duration of [2, 4, 6, 8, 10]) tracker.record("planningTransaction", duration); const healthy = tracker.snapshot(); assert.equal(healthy.metrics.planningTransaction.medianMs, 6); assert.equal(healthy.metrics.planningTransaction.withinBudget, true); for (let index = 0; index < 16; index++) tracker.record("planningTransaction", 40); const breached = tracker.snapshot(); assert.equal(breached.metrics.planningTransaction.withinBudget, false); assert.deepEqual(breached.breaches, ["planningTransaction"]); });

test("superseded propositions cannot license a later contract", () => { const simulation = { tick: 1, animals: [entity()], corpses: [] }, runtime = new ObservationTransactionRuntime(), first = runtime.observe(simulation, { scenes: [scene] }), oldAction = first.propositions.forSubjects(["A"]).find(claim => claim.predicate === "entity.action.current"); simulation.tick = 2; simulation.animals[0].actionState = { key: "drink", target: "water-1" }; const second = runtime.observe(simulation, { scenes: [scene] }), activeActions = second.propositions.forSubjects(["A"]).filter(claim => claim.predicate === "entity.action.current"); assert.equal(second.snapshot.entities.get("A").plan.targetId, "water-1"); assert.equal(activeActions.length, 1); assert.notEqual(activeActions[0].claimId, oldAction.claimId); assert.equal(second.propositions.valid(oldAction.claimId, 2), false); assert.ok(activeActions[0].evidenceIds.every(id => second.evidence.get(id))); });

test("one failed evidence adapter cannot partially corrupt the committed evidence batch", () => { const bad = { id: "bad", observe() { throw new Error("adapter broke"); } }, good = { id: "good", observe(snapshot) { return [{ sourceAdapter: "good", sourceKind: "ENVIRONMENT_STATE", epistemicClass: "AUTHORITATIVE", predicate: "world.test", subjectIds: [], object: { tick: snapshot.simulationTick }, observedAtTick: snapshot.simulationTick, validFromTick: snapshot.simulationTick, confidence: 1 }]; } }, runtime = new ObservationTransactionRuntime({ adapters: [bad, good] }), result = runtime.observe({ tick: 1, animals: [], corpses: [] }); assert.equal(result.evidenceDelta.records.length, 1); assert.equal(result.adapterDiagnostics.find(item => item.adapterId === "bad").status, "ADAPTER_FAILED"); });

test("hard policy compilation applies camera motion narration channel and subject constraints together", () => { const policy = compileDocumentaryPolicy({ presetName: "characters", subjectMode: "characters", shotTypes: "wildlife", motionTypes: "still", narrationEnabled: false, voiceEnabled: false, captionsEnabled: true, lensPreset: "natural" }); assert.deepEqual(policy.allowedCameraFamilies, ["still"]); assert.equal(policy.narrationEnabled, false); assert.equal(policy.voiceEnabled, false); assert.equal(policy.captionsEnabled, true); assert.equal(policyAllowsScene(scene, policy).allowed, true); assert.equal(policyAllowsScene({ id: "ground", kind: "terrain-transition", ids: [], worldSubject: true }, policy).allowed, false); });

test("contract validation rejects an absent claim and evidence rather than licensing prose", () => { const policy = compileDocumentaryPolicy({}), contract = { decision: { decisionId: "d" }, situationId: "s", threadId: "t", subjectIds: ["A"], allowedClaimIds: ["missing"], narration: { mode: "SPEAK", subjectIds: ["A"] }, camera: { primarySubjects: ["A"], secondarySubjects: [], preferredFamilies: ["still"], allowedFamilies: ["still"], minimumHoldSeconds: 1, preferredHoldSeconds: 2 } }, result = validatePresentationContract(contract, { propositions: { get: () => null, valid: () => false }, evidence: { get: () => null }, policy }); assert.equal(result.valid, false); assert.ok(result.errors.includes("claim-missing:missing")); });

test("contract narration discards unlicensed prose and realises only licensed claims", () => { const policy = compileDocumentaryPolicy({}), identity = { claimId: "identity", predicate: "entity.identity", subjectIds: ["A"], normalizedArguments: { name: "Aster", lifeStage: "adult", sex: "female", speciesId: "grazer" }, evidenceIds: ["e1"], validFromTick: 1, validUntilTick: null }, action = { claimId: "action", predicate: "entity.action.current", subjectIds: ["A"], normalizedArguments: { key: "drink", label: "drinking" }, evidenceIds: ["e2"], validFromTick: 1, validUntilTick: null }, claims = new Map([[identity.claimId, identity], [action.claimId, action]]), propositions = { get: id => claims.get(id), valid: id => claims.has(id) }, evidence = { get: id => ["e1", "e2"].includes(id) ? { evidenceId: id } : null }, contract = { decision: { decisionId: "d" }, situationId: "s", threadId: "t", subjectIds: ["A"], allowedClaimIds: ["identity", "action"], narration: { mode: "SPEAK", subjectIds: ["A"], allowedClaimIds: ["identity", "action"], maximumSentences: 2, requireNewInformation: true }, camera: { primarySubjects: ["A"], secondarySubjects: [], preferredFamilies: ["still"], allowedFamilies: ["still"], minimumHoldSeconds: 1, preferredHoldSeconds: 2 } }, realised = realiseDeterministicContract({ contract, context: { tick: 2 }, propositions, evidence, policy, compose: () => ({ text: "Aster has secretly decided to leave forever." }) }); assert.equal(realised.source, "licensed-claim-realiser"); assert.ok(realised.text.includes("Aster")); assert.ok(!realised.text.includes("secretly")); assert.deepEqual(realised.claimIds, ["identity", "action"]); });

test("V3 active remains shadow-only until the learning capability explicitly permits control", () => { const profile = new AuthorLearningProfile({ lifecycle: "OBSERVING" }), author = new ACSSPredictiveAuthor({ mode: "V3_ACTIVE", profileStore: { load: () => profile, save: () => true } }); assert.equal(author.canControl(), false); author.setLearningLifecycle("BOUNDED_ACTIVE"); assert.equal(author.canControl(), true); });

test("observe-only outcome handling is byte-stable", () => { const profile = new AuthorLearningProfile({ lifecycle: "OBSERVING" }), before = profile.snapshot().profileChecksum; profile.resolveForecast({ forecast: { forecastId: "f", modelId: "m", family: "STATE", outcomes: [{ id: "YES", probability: .8 }, { id: "NO", probability: .2 }] }, resolution: { status: "RESOLVED", observedOutcome: "YES" } }); profile.resolveProduction({ decision: { decisionId: "d", action: "HOLD" }, actual: { executed: true, cameraQualityMean: .9 }, executed: true }); profile.recordProductionFault({ reportId: "r", faultCodes: ["CAMERA_LOOP"], corroboration: { status: "CONFIRMED_BY_TELEMETRY" } }); assert.equal(profile.snapshot().profileChecksum, before); });

test("failure inside an optional model branch does not invalidate the required root graph", () => { const registry = new PredictionModelRegistry(), descriptor = (modelId, dependencies = [], applicable = () => true) => ({ modelId, family: "TEST", predicts: modelId, dependencies, applicable, outcomeObserverId: modelId, predict: () => ({ outcomes: [{ id: "OK", probability: 1 }], confidence: 1 }) }); registry.register(descriptor("unavailable", [], () => false)); registry.register(descriptor("optional", [{ modelId: "unavailable", relation: "REQUIRES" }])); registry.register(descriptor("root", [{ modelId: "optional", relation: "SUPPORTS" }])); const closure = registry.dependencyClosure("root", {}); assert.equal(closure.valid, true); assert.ok(closure.models.some(item => item.model.modelId === "root")); assert.ok(!closure.models.some(item => item.model.modelId === "optional")); });

test("audience memory suppresses semantic paraphrases but permits material revisions", () => { const memory = new DocumentaryAudienceMemory(); memory.mark({ predicate: "entity.action.current", subjectIds: ["A"], arguments: { key: "travel" }, text: "Animal A travels to water.", materialRevision: 1 }, 10); assert.ok(memory.novelty({ predicate: "entity.action.current", subjectIds: ["A"], arguments: { key: "travel" }, text: "A is travelling toward water.", materialRevision: 1 }, 11) < .3); assert.equal(memory.novelty({ predicate: "entity.action.current", subjectIds: ["A"], arguments: { key: "drink" }, text: "A has begun drinking.", materialRevision: 2 }, 12), 1); });

test("horizon camera planning chooses a valid pose and converges without discontinuity", () => { const planner = new CameraHorizonPlanner(), start = { position: { x: 0, y: 5, z: 10 }, target: { x: 0, y: 1, z: 0 }, fov: 45 }, goal = { position: { x: 8, y: 6, z: 8 }, target: { x: 2, y: 1, z: 2 }, fov: 40 }, plan = planner.plan({ current: start, goal, validatePose: candidate => ({ valid: candidate.position.x >= 0, visibility: 1, composition: 1, containment: 1, clearance: 1 }) }); assert.equal(plan.selected.metrics.valid, true); const session = new CameraPresentationSession(); session.begin({ current: start, goal, contract: { maximumSpeed: 8, maximumAcceleration: 12, maximumJerk: 30 } }); const metrics = new CameraMetricAccumulator(start); let current = start; for (let index = 0; index < 120; index++) { const next = session.step({ current, goal, observedFocus: goal.target, dtSeconds: 1 / 60, nowSeconds: index / 60 }); metrics.sample({ pose: next, metrics: { valid: true, visibility: 1, composition: 1, containment: 1, clearance: 1, subjectScreenArea: .2 }, dtSeconds: 1 / 60 }); current = next; } const result = metrics.finalize(); assert.equal(result.discontinuityCount, 0); assert.ok(result.maximumJerk <= 30.01); assert.ok(Math.hypot(current.position.x - start.position.x, current.position.z - start.position.z) > 1); });

test("author profiles commit immutable numbered revisions before moving the current pointer", () => { const storage = { values: new Map(), getItem(key) { return this.values.get(key) ?? null; }, setItem(key, value) { this.values.set(key, value); }, removeItem(key) { this.values.delete(key); } }, store = new BrowserAuthorProfileStore({ storage }), profile = new AuthorLearningProfile(); assert.equal(store.save(profile), true); profile.revision = 1; profile.lifecycle = "CALIBRATING"; assert.equal(store.save(profile), true); const manifest = JSON.parse(storage.getItem(`${store.key}:manifest`)); assert.deepEqual(manifest.revisions, [0, 1]); assert.ok(storage.getItem(`${store.key}:revision:0`)); assert.ok(storage.getItem(`${store.key}:revision:1`)); assert.equal(store.load().revision, 1); });
