import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { AudienceLearningSystem, AudienceProfile, BrowserAudienceProfileStore, normalizeExplicitFeedback, normalizeImplicitSignal, parseWrittenAudienceFeedback, corroborateFaultReport, sceneFeatureVector, extractSceneFeatures } from "../src/documentary-author/audience/index.js";

class MemoryStorage { constructor() { this.items = new Map(); } getItem(key) { return this.items.get(key) ?? null; } setItem(key, value) { this.items.set(key, value); } removeItem(key) { this.items.delete(key); } }
const presentation = system => system.registerPresentation({ presentationId: "p1", contract: { contractId: "c1", decision: { decisionId: "d1" }, threadId: "t1", situationId: "s1", subjectIds: ["A"], beat: "development", camera: {} }, shot: { semanticRoleIds: ["A"], context: "resource", actionKey: "travel water", family: "tracking", duration: 10 }, narration: { text: "A is travelling towards water.", noveltyMean: 1 }, metrics: { containmentMean: .8 } });

test("thumb and rating form one normalized explicit observation", () => { const value = normalizeExplicitFeedback({ thumb: "UP", rating: 5, direction: null, tags: [], status: "CONFIRMED" }); assert.equal(value.value, .35 * .65 + .65); assert.equal(value.confidence, 1); });
test("three stars is neutral", () => { assert.equal(normalizeExplicitFeedback({ rating: 3, thumb: null, tags: [] }).value, 0); });
test("immediate next shot produces no learning and qualified skip stays weak", () => { assert.equal(normalizeImplicitSignal({ type: "NEXT_SHOT", exposureFraction: .1 }).weight, 0); assert.equal(normalizeImplicitSignal({ type: "NEXT_SHOT", exposureFraction: .7 }).weight, .2); });
test("known fault inhibits implicit preference learning", () => { assert.equal(normalizeImplicitSignal({ type: "NEXT_SHOT", exposureFraction: .8, knownFault: true }).weight, 0); });
test("scene feedback changes a bounded interpretable preference", () => { const storage = new MemoryStorage(), system = new AudienceLearningSystem({ store: new BrowserAudienceProfileStore({ storage }) }); presentation(system); const before = system.preferenceForScene({ kind: "activity", semanticRoleIds: ["A"], actionKey: "travel water" }).mean; const result = system.feedback({ presentationId: "p1", rating: 5, tags: ["GOOD_SUBJECT"], status: "CONFIRMED" }); const after = system.preferenceForScene({ kind: "activity", semanticRoleIds: ["A"], actionKey: "travel water" }).mean; assert.equal(result.applied, true); assert.ok(after > before); assert.ok(Math.abs(result.deltas[0].after) <= 1); });
test("an untouched audience prior has zero learned confidence", () => { const profile = new AudienceProfile(); assert.equal(profile.predict({ "camera:family:tracking": 1 }).confidence, 0); profile.update({ "camera:family:tracking": 1 }, 1); assert.ok(profile.predict({ "camera:family:tracking": 1 }).confidence > 0); });
test("camera-specific feedback targets camera features instead of subject affinity", () => { const features = extractSceneFeatures({ shot: { semanticRoleIds: ["A"], family: "tracking", duration: 8 } }), vector = sceneFeatureVector(features, { tags: ["CAMERA_TOO_DISTANT"] }); assert.ok(Object.keys(vector).length); assert.ok(Object.keys(vector).every(key => key.startsWith("camera:"))); });
test("written parser handles negation and requires confirmation", () => { assert.deepEqual(parseWrittenAudienceFeedback("The camera is too far away").proposedTags, ["CAMERA_TOO_DISTANT"]); assert.deepEqual(parseWrittenAudienceFeedback("The camera is not too far away").proposedTags, []); });
test("fault reports are corroborated by telemetry and remain outside taste feedback", () => { const result = corroborateFaultReport({ presentationId: "p", category: "CAMERA", faultCodes: ["SUBJECT_OUT_OF_FRAME"], severity: "MAJOR" }, { containmentMean: .1 }); assert.equal(result.report.corroboration.status, "CONFIRMED_BY_TELEMETRY"); assert.equal(result.report.immediateAction, "REPLAN"); });
test("camera loop and follow reports use their own production telemetry", () => { const loop = corroborateFaultReport({ presentationId: "p", category: "CAMERA", faultCodes: ["CAMERA_LOOP"], severity: "MAJOR" }, { accumulatedAngularTravel: Math.PI * 1.75 }), follow = corroborateFaultReport({ presentationId: "p", category: "CAMERA", faultCodes: ["CAMERA_FAILED_TO_FOLLOW"], severity: "MAJOR" }, { predictedZoneError: 12, containmentMean: .2 }); assert.equal(loop.report.corroboration.status, "CONFIRMED_BY_TELEMETRY"); assert.equal(follow.report.corroboration.status, "CONFIRMED_BY_TELEMETRY"); });
test("blank viewport reports request immediate safe-camera recovery", () => { const result = corroborateFaultReport({ presentationId: "p", category: "CAMERA", faultCodes: ["CAMERA_BLANK_VIEW"], severity: "UNUSABLE" }, { renderEmptySeconds: 2 }); assert.equal(result.report.corroboration.status, "CONFIRMED_BY_TELEMETRY"); assert.equal(result.report.immediateAction, "SAFE_CAMERA"); });
test("profile rollback restores the exact previous committed revision", () => { const storage = new MemoryStorage(), store = new BrowserAudienceProfileStore({ storage }), profile = new AudienceProfile(); profile.update({ "subject:character": 1 }, .5); store.save(profile); const previous = profile.snapshot().profileChecksum; profile.update({ "subject:character": 1 }, 1); store.save(profile); const restored = store.rollback(); assert.equal(restored.profileChecksum, previous); assert.ok(restored.stable.mean("subject:character") < profile.stable.mean("subject:character")); });
test("audience revisions are immutable and the manifest pointer advances only after verification", () => { const storage = new MemoryStorage(), store = new BrowserAudienceProfileStore({ storage }), profile = new AudienceProfile(); profile.update({ "subject:character": 1 }, .5); store.save(profile); const firstRevision = profile.revision, firstRaw = storage.getItem(store.revisionKey(profile.profileId, firstRevision)); profile.update({ "camera:motion:stable": 1 }, 1); store.save(profile); const manifest = JSON.parse(storage.getItem(store.manifestKey(profile.profileId))); assert.deepEqual(manifest.revisions, [firstRevision, profile.revision]); assert.equal(manifest.currentRevision, profile.revision); assert.equal(storage.getItem(store.revisionKey(profile.profileId, firstRevision)), firstRaw); });
test("corrupt current audience profile recovers the previous checksummed revision", () => { const storage = new MemoryStorage(), store = new BrowserAudienceProfileStore({ storage }), profile = new AudienceProfile(); profile.update({ "subject:character": 1 }, .4); store.save(profile); const expected = profile.stable.mean("subject:character"); profile.update({ "camera:family:orbit": 1 }, 1); store.save(profile); const corrupt = JSON.parse(storage.getItem(store.key)); corrupt.stable.records["subject:character"].information = 900; storage.setItem(store.key, JSON.stringify(corrupt)); const recovered = store.load(); assert.equal(recovered.stable.mean("subject:character"), expected); assert.ok(storage.getItem(`${store.key}:quarantined`)); });
test("guest reset does not retain a persistent profile", () => { const store = new BrowserAudienceProfileStore({ storage: new MemoryStorage() }), profile = store.reset({ guest: true }); assert.equal(profile.mode, "GUEST"); });
test("named audience profiles can be created listed and selected", () => { const store = new BrowserAudienceProfileStore({ storage: new MemoryStorage() }), first = store.create("Louie documentary preferences"), second = store.create("Nature group", { mode: "SHARED_AGGREGATE" }); assert.deepEqual(new Set(store.list().map(row => row.profileId)), new Set([first.profileId, second.profileId])); const selected = store.select(first.profileId); assert.equal(selected.displayName, "Louie documentary preferences"); assert.equal(selected.mode, "PERSONAL"); });
test("shared audience mode aggregates explicit disagreement and rejects implicit behavior", () => { const system = new AudienceLearningSystem({ store: new BrowserAudienceProfileStore({ storage: new MemoryStorage() }) }); system.createProfile("Shared room", { mode: "SHARED_AGGREGATE" }); presentation(system); system.feedback({ presentationId: "p1", rating: 5, status: "CONFIRMED" }); system.feedback({ presentationId: "p1", rating: 1, status: "CONFIRMED" }); const health = system.health(); assert.equal(health.sharedVotes, 2); assert.ok(health.sharedDisagreement > 0); assert.equal(system.implicit({ presentationId: "p1", type: "NEXT_SHOT", exposureFraction: 1 }).reason, "shared-profile-explicit-only"); });
test("explicit feedback can be retracted reproducibly", () => { const system = new AudienceLearningSystem({ store: new BrowserAudienceProfileStore({ storage: new MemoryStorage() }) }); presentation(system); const before = system.profile.stable.mean("camera:family:tracking"), learned = system.feedback({ presentationId: "p1", rating: 5, tags: ["GOOD_CAMERA_ANGLE"], status: "CONFIRMED" }); assert.ok(system.profile.stable.mean("camera:family:tracking") > before); const retracted = system.retract(learned.episode.feedbackId); assert.equal(retracted.applied, true); assert.equal(system.profile.stable.mean("camera:family:tracking"), before); });
test("pairwise camera choices rank otherwise valid camera families", () => { const system = new AudienceLearningSystem({ store: new BrowserAudienceProfileStore({ storage: new MemoryStorage() }) }); const result = system.compare({ featureA: { "camera:family:still": 1 }, featureB: { "camera:family:tracking": 1 }, preferred: "B" }); assert.equal(result.applied, true); assert.equal(system.cameraPreferences({ world: false }).families[0].id, "tracking"); assert.equal(system.profile.samples.pairwise, 1); });
test("prompt policy refuses narration and critical-event interruptions", () => { const system = new AudienceLearningSystem({ store: new BrowserAudienceProfileStore({ storage: new MemoryStorage() }) }); system.skipPriming(); assert.equal(system.prompt({ nowMs: 100000, speechActive: true }), null); assert.equal(system.prompt({ nowMs: 100000, criticalEvent: true }), null); });
test("every audience control queried by the runtime exists exactly once", () => { const html = readFileSync(new URL("../index.html", import.meta.url), "utf8"), app = readFileSync(new URL("../src/app.js", import.meta.url), "utf8"), queried = [...app.matchAll(/querySelector\("#(movie-audience-[^"]+)"\)/g)].map(match => match[1]); for (const id of new Set(queried)) assert.equal((html.match(new RegExp(`id=["']${id}["']`, "g")) || []).length, 1, id); });
