import test from "node:test";
import assert from "node:assert/strict";
import { brakingDistance, predictIntercept, shortestAngle, steeringStep } from "../src/steering-controller.js";
import { interactionRadius, physicalContact, resolveAnimalBodyCollision, softSeparation } from "../src/interaction-spacing.js";
import { buildNavMesh } from "../src/navmesh.js";
import { findNavPath } from "../src/navmesh-pathfinding.js";
import { bodySupportedByNavmesh, createLocomotionState, createMovementRequest, predictedRequestDestination, runLocomotionMinute } from "../src/locomotion-system.js";
const profile = { maxSpeed: 2, acceleration: 2, braking: 2, turnRate: Math.PI * 2, bodyRadius: .25, separationWeight: 1 };
test("steering turns shortest and cannot overshoot", () => { assert.ok(shortestAngle(Math.PI - .1, -Math.PI + .1) > 0); assert.equal(brakingDistance(2, 2), 1); const next = steeringStep({ x: 0, z: 0, vx: 4, vz: 0, heading: 0 }, { x: .2, z: 0 }, profile, 1, { stoppingRadius: .1 }); assert.ok(next.x <= .1 + 1e-9); });
test("pursuit is capped and contact target is exempt from separation", () => { assert.deepEqual(predictIntercept({ x: 0, z: 0 }, { x: 10, z: 0, vx: 1, vz: 0, confidence: 1 }, 1, 2), { x: 12, z: 0, lead: 2 }); assert.equal(interactionRadius({ bodyRadius: .2 }, { bodyRadius: .3 }, "attack"), .5); assert.equal(interactionRadius({ bodyRadius: .2 }, { bodyRadius: .3 }, "mating"), .5); assert.equal(interactionRadius({ bodyRadius: .2 }, { bodyRadius: .3 }, "nursing"), .5); assert.equal(interactionRadius({ bodyRadius: .2 }, { bodyRadius: .3 }, "feeding"), .5); assert.equal(physicalContact({ x: 0, z: 0, bodyRadius: .2 }, { x: .51, z: 0, bodyRadius: .3 }), true); assert.equal(physicalContact({ x: 0, z: 0, bodyRadius: .2 }, { x: .511, z: 0, bodyRadius: .3 }), false); assert.deepEqual(softSeparation({ id: "a", x: 0, z: 0, bodyRadius: .2 }, [{ id: "b", x: .1, z: 0, bodyRadius: .2 }], { contactTargetId: "b" }), { x: 0, z: 0 }); });
test("hard body collision preserves contact without allowing overlap", () => { const actor = { id: "a", x: 0, z: 0, bodyRadius: .2 }, other = { id: "b", alive: true, x: .3, z: 0, bodyRadius: .3 }; const resolved = resolveAnimalBodyCollision(actor, { x: .2, z: 0, vx: 1, vz: 0 }, [other]); assert.ok(Math.hypot(resolved.x - other.x, resolved.z - other.z) >= .502 - 1e-9); assert.equal(resolved.collided, true); });
test("stationary overlapping animals are separated instead of remaining phased", () => { const mesh = buildNavMesh(tinyWorld()), left = { id: "a", speciesId: "grazer", alive: true, x: 1, z: 0, orientation: 0 }, right = { id: "b", speciesId: "grazer", alive: true, x: 1.1, z: 0, orientation: 0 }; left.locomotion = createLocomotionState(left, profile); right.locomotion = createLocomotionState(right, profile); runLocomotionMinute([left, right], mesh, { substeps: 8, profileFor: () => profile, neighboursFor: (animal) => animal.id === "a" ? [right] : [left] }); assert.ok(Math.hypot(right.x - left.x, right.z - left.z) >= .5); });
function tinyWorld() { const cells = [{ id: 0, x: 0, z: 0, slope: 0, neighbours: [] }, { id: 1, x: 1, z: 0, slope: 0, neighbours: [] }, { id: 2, x: 2, z: 0, slope: 0, neighbours: [] }]; cells[0].neighbours = [cells[1]]; cells[1].neighbours = [cells[0], cells[2]]; cells[2].neighbours = [cells[1]]; return { radius: .58, cells, lookup: (x) => cells[Math.max(0, Math.min(2, Math.round(x)))], corners: (c) => Array.from({ length: 6 }, (_, i) => ({ x: c.x + .58 * Math.cos(i * Math.PI / 3), z: c.z + .58 * Math.sin(i * Math.PI / 3) })) }; }
test("navmesh routes deterministically and movement is continuous", () => { const mesh = buildNavMesh(tinyWorld()), path = findNavPath(mesh, { x: 0, z: 0 }, { x: 2, z: 0 }); assert.deepEqual(path.polygonIds, [0, 1, 2]); const animal = { id: "a", speciesId: "grazer", alive: true, x: 0, z: 0, orientation: 0 }; animal.locomotion = createLocomotionState(animal, profile); animal.movementRequest = createMovementRequest("go", { x: 2, z: 0 }); runLocomotionMinute([animal], mesh, { substeps: 8, profileFor: () => profile, neighboursFor: () => [] }); assert.ok(animal.x > 0 && animal.x < 2); assert.equal(animal.x, animal.fx); });
test("elapsed locomotion supports responsive real-time player steps", () => { const mesh = buildNavMesh(tinyWorld()), make = () => { const animal = { id: "a", speciesId: "grazer", alive: true, x: 0, z: 0, orientation: 0 }; animal.locomotion = createLocomotionState(animal, profile); animal.movementRequest = createMovementRequest("go", { x: 2, z: 0 }); return animal; }, short = make(), long = make(); runLocomotionMinute([short], mesh, { elapsed: .05, substeps: 2, profileFor: () => profile, neighboursFor: () => [] }); runLocomotionMinute([long], mesh, { elapsed: .5, substeps: 8, profileFor: () => profile, neighboursFor: () => [] }); assert.ok(short.x > 0); assert.ok(short.x < long.x); });
test("direct control can recover when collision leaves its footprint outside a navmesh edge", () => { const mesh = { worldRadius: 1, polygonAt: (x, z) => Math.abs(x) <= 1 && Math.abs(z) <= 1 ? 0 : null }, recoveryProfile = { ...profile, bodyRadius: .4 }, start = { x: .8, z: 0 }; assert.equal(bodySupportedByNavmesh(mesh, start.x, start.z, recoveryProfile.bodyRadius), false); const animal = { id: "a", speciesId: "grazer", alive: true, x: start.x, z: start.z, orientation: Math.PI }; animal.locomotion = createLocomotionState(animal, recoveryProfile); animal.movementRequest = createMovementRequest("embodied-camera-relative", { x: 0, z: 0 }, { destinationSource: "player-camera-relative" }); runLocomotionMinute([animal], mesh, { elapsed: .5, substeps: 8, profileFor: () => recoveryProfile, neighboursFor: () => [] }); assert.ok(animal.x < start.x); });
test("boundary recovery alone can walk inward from beyond the navmesh", () => { const mesh = buildNavMesh(tinyWorld()), animal = { id: "a", speciesId: "grazer", alive: true, x: 3, z: 0, orientation: Math.PI }; animal.locomotion = createLocomotionState(animal, profile); animal.movementRequest = createMovementRequest("boundary", { x: 1.5, z: 0 }, { allowOutsideNavmesh: true, destinationSource: "boundary-recovery" }); runLocomotionMinute([animal], mesh, { substeps: 8, profileFor: () => profile, neighboursFor: () => [] }); assert.ok(animal.x < 3); assert.equal(animal.movementRequest.allowOutsideNavmesh, true); });
test("pursuit extrapolates stored evidence without a live target", () => { const request = createMovementRequest("chase:p", { x: 2, z: 0 }, { destinationSource: "perceived-evidence", perceivedTarget: { x: 2, z: 0, vx: 0, vz: 1, velocityConfidence: .5 }, velocityConfidence: .5 }); const destination = predictedRequestDestination(request, { x: 0, z: 0 }, { maxSpeed: 1, sprintSpeed: 2, predictionCap: 2 }, .5); assert.ok(destination.z > 0); assert.equal(destination.x, 2); });
test("arrival retains completed locomotion mode and contact intent", () => { const mesh = buildNavMesh(tinyWorld()), animal = { id: "a", speciesId: "grazer", alive: true, x: 0, z: 0, orientation: 0 }; animal.locomotion = createLocomotionState(animal, profile); animal.movementRequest = createMovementRequest("chase:p", { x: .1, z: 0 }, { mode: "sprint", contactIntent: { preyId: "p" } }); runLocomotionMinute([animal], mesh, { substeps: 8, profileFor: () => profile, neighboursFor: () => [] }); assert.equal(animal.locomotion.completedMode, "sprint"); assert.equal(animal.locomotion.completedRequestId, "chase:p"); assert.equal(animal.locomotion.completedContactIntent.preyId, "p"); });
