import test from "node:test";
import assert from "node:assert/strict";
import { assessHerbivoreDefence } from "../src/herbivore-defence.js";

test("a lone vulnerable grazer flees even from a juvenile hunter", () => { const result = assessHerbivoreDefence({ herbivore: { health: 45, energy: 40, aggression: .2 }, predator: { lifeStage: "juvenile", health: 90, energy: 70 }, distance: 3 }); assert.equal(result.action, "flee"); });
test("a strong herd may mob an isolated juvenile without treating it as prey", () => { const result = assessHerbivoreDefence({ herbivore: { health: 95, energy: 90, aggression: .5 }, predator: { lifeStage: "juvenile", health: 80, energy: 60 }, herdAdults: 4, distance: 4 }); assert.equal(result.action, "mob"); });
test("protective confident groups can attack adult predators too", () => { const result = assessHerbivoreDefence({ herbivore: { health: 100, energy: 95, aggression: .75, careAffinity: .9 }, predator: { lifeStage: "adult", health: 80, energy: 65 }, herdAdults: 5, protectingYoung: true, distance: 2.5 }); assert.equal(result.action, "attack"); });
test("nearby adult predators make an isolated youngster unsafe to approach", () => { const result = assessHerbivoreDefence({ herbivore: { health: 90, energy: 85, aggression: .6 }, predator: { lifeStage: "dependent", health: 80, energy: 60 }, herdAdults: 2, adultPredatorsNearby: 2, distance: 4 }); assert.equal(result.action, "flee"); });
test("zero-confidence intent fields do not suppress ordinary danger assessment", () => { const result = assessHerbivoreDefence({ herbivore: { health: 90, energy: 80, aggression: .2 }, predator: { lifeStage: "adult", health: 95, energy: 80 }, distance: 4, targetLikelihood: 0, attackImminence: 0, intentConfidence: 0 }); assert.equal(result.action, "flee"); });
test("a dangerous predator inside close range triggers flight before contact", () => { const result = assessHerbivoreDefence({ herbivore: { health: 95, energy: 90, aggression: .35 }, predator: { lifeStage: "adult", health: 95, energy: 80 }, distance: 2.8, targetLikelihood: .1, attackImminence: .1, intentConfidence: .2 }); assert.equal(result.action, "flee"); });
