import test from "node:test";
import assert from "node:assert/strict";
import { advanceRecovery, beginRecovery, interruptRecovery, migrateRecoveryState, recoveryComplete, recoveryNeeds, recoveryPerceptionProfile, selectRecoveryDepth } from "../src/recovery-system.js";
import { initializeMetabolism } from "../src/metabolic-system.js";
import { migrateUtilisationState } from "../src/activity-utilisation.js";

const animal = (extra = {}) => ({ speciesId: "grazer", sex: "F", lifeStage: "adult", bodyMass: 65, leanMass: 50, fatMass: 15, muscleMass: 30, health: 100, hydration: 90, stomach: 50, fatigue: 0, actionState: { key: "idle" }, ...extra });
function prepared(extra = {}) { const a = animal(extra); initializeMetabolism(a); migrateUtilisationState(a); migrateRecoveryState(a); return a; }
test("short burst and long travel select different recovery depths", () => { const burst = prepared(); burst.metabolism.anaerobicDebt = 15; burst.utilisation.recoveryDebt.exertion = 12; assert.equal(recoveryNeeds(burst).recommendedDepth, "active"); const travel = prepared(); travel.utilisation.recoveryDebt.travel = 70; assert.equal(recoveryNeeds(travel).recommendedDepth, "deep-rest"); });
test("unsafe surroundings constrain recovery depth", () => { const a = prepared(); a.utilisation.recoveryDebt.travel = 80; assert.equal(selectRecoveryDepth(a, { threatConfidence: .8 }).selectedDepth, "active"); assert.equal(selectRecoveryDepth(a, { threatConfidence: 0, cover: .8 }, { trustedCompanions: 2 }).selectedDepth, "sleep-like"); });
test("rest continues until minimum time and triggering debt target", () => { const a = prepared(); a.utilisation.recoveryDebt.travel = 55; const needs = recoveryNeeds(a); beginRecovery(a, needs.recommendedDepth, needs.primaryCause, 10, needs); assert.equal(recoveryComplete(a, 11), false); for (let i = 0; i < 30; i++) advanceRecovery(a, { safe: true }); assert.equal(recoveryComplete(a, 30), true); });
test("deeper rest reduces detection and requires stronger waking stimulus", () => { const a = prepared(); beginRecovery(a, "sleep-like", "stress", 0, { causes: [], completionTargets: { stress: 0 }, minimumDuration: 5 }); const senses = recoveryPerceptionProfile(a.recoveryState); assert.ok(senses.vision < .1); assert.equal(interruptRecovery(a, { modality: "hearing", intensity: .2, proximity: .5 }, 1).woke, false); assert.equal(interruptRecovery(a, { modality: "hearing", intensity: 1, proximity: 1, familiarAlarm: true }, 2).woke, false); assert.equal(interruptRecovery(a, { modality: "hearing", intensity: 1, proximity: 1, physicalContact: true }, 3).woke, true); });
