import test from "node:test";
import assert from "node:assert/strict";
import { activateStressResponse, advanceStressResponse, assessStressTrigger, canEmergencyOverride, migrateStressResponse } from "../src/stress-response.js";
import { initializeMetabolism } from "../src/metabolic-system.js";

const animal = (extra = {}) => ({ speciesId: "grazer", sex: "F", lifeStage: "adult", bodyMass: 65, leanMass: 50, fatMass: 15, muscleMass: 30, health: 100, hydration: 90, stomach: 50, fear: 50, aggression: .4, ...extra });
test("adrenaline mobilises but does not create substrate", () => { const a = animal(), metabolism = initializeMetabolism(a), before = metabolism.bloodFuel + metabolism.liverGlycogen + metabolism.muscleGlycogen, liver = metabolism.liverGlycogen; activateStressResponse(a, { intensity: .8, confidence: .9, triggerId: "hunter-1" }, 4); const after = metabolism.bloodFuel + metabolism.liverGlycogen + metabolism.muscleGlycogen; assert.ok(metabolism.liverGlycogen < liver); assert.ok(Math.abs(before - after) < 1e-7); });
test("threat proximity and targeting raise acute stress", () => { const a = animal(), low = assessStressTrigger(a, { confidence: .5, distance: 11, targetingLikelihood: .1 }, { detectionRange: 12 }), high = assessStressTrigger(a, { confidence: .95, distance: 1, targetingLikelihood: 1 }, { detectionRange: 12 }); assert.ok(high.score > low.score); assert.equal(high.acute, true); });
test("stress declines after threat removal and repeated activation leaves debt", () => { const a = animal(); migrateStressResponse(a); activateStressResponse(a, { intensity: .8 }, 1); activateStressResponse(a, { intensity: .8 }, 2); const debt = a.stressResponse.recoveryDebt; for (let i = 0; i < 6; i++) advanceStressResponse(a, { threatPresent: false, safeCover: 1 }); assert.ok(a.stressResponse.intensity < .8); assert.ok(debt > 0); });
test("emergency override still requires substrate and viable condition", () => { const a = animal(); const metabolism = initializeMetabolism(a); activateStressResponse(a, { intensity: .9 }, 1); assert.equal(canEmergencyOverride(a), true); metabolism.bloodFuel = metabolism.liverGlycogen = metabolism.muscleGlycogen = 0; assert.equal(canEmergencyOverride(a), false); });
