import { readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";

const stamp = ms => { const value = Math.max(0, Number(ms) || 0), hours = Math.floor(value / 3600000), minutes = Math.floor(value % 3600000 / 60000), seconds = Math.floor(value % 60000 / 1000), millis = Math.floor(value % 1000); return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")},${String(millis).padStart(3, "0")}`; };
const csv = value => `"${String(value ?? "").replaceAll('"', '""')}"`;
const html = value => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function jsonl(path) { try { return (await readFile(path, "utf8")).split(/\r?\n/).filter(Boolean).map(line => JSON.parse(line)); } catch { return []; } }

export class ExportManager {
  async generate(session) { const timeline = join(session.root, "timeline"), reports = join(session.root, "reports"), editing = join(session.root, "editing"), narrationRecords = await jsonl(join(timeline, "narration.jsonl")), editorial = await jsonl(join(timeline, "editorial-windows.jsonl")), events = await jsonl(join(timeline, "events.jsonl")), promises = await jsonl(join(timeline, "promises.jsonl")), predictions = await jsonl(join(timeline, "predictions.jsonl")), assets = narrationRecords.filter(record => record.recordType === "narration_asset" && Number.isFinite(record.payload.audioStartedAtMs) && Number.isFinite(record.payload.audioEndedAtMs));
    const srt = assets.map((record, index) => `${index + 1}\n${stamp(record.payload.audioStartedAtMs)} --> ${stamp(record.payload.audioEndedAtMs)}\n${record.payload.text}\n`).join("\n"), vtt = `WEBVTT\n\n${assets.map(record => `${stamp(record.payload.audioStartedAtMs).replace(",", ".")} --> ${stamp(record.payload.audioEndedAtMs).replace(",", ".")}\n${record.payload.text}\n`).join("\n")}`; await writeFile(join(session.root, "narration", "narration.srt"), srt); await writeFile(join(session.root, "narration", "narration.vtt"), vtt);
    const windows = editorial.map(record => record.payload), highlights = windows.filter(item => ["HIGHLIGHT", "MAJOR_HIGHLIGHT"].includes(item.classification)), stagnant = windows.filter(item => item.classification.startsWith("STAGNANT")); await writeFile(join(reports, "highlights.csv"), `classification,start_ms,end_ms,score,reasons\n${highlights.map(item => [item.classification, item.startMs, item.endMs, item.score, (item.reasons || []).join("|")].map(csv).join(",")).join("\n")}`); await writeFile(join(reports, "stagnant-ranges.csv"), `classification,start_ms,end_ms,score,reasons\n${stagnant.map(item => [item.classification, item.startMs, item.endMs, item.score, (item.reasons || []).join("|")].map(csv).join(",")).join("\n")}`);
    const openPromises = promises.map(record => record.payload).filter(item => item.status === "OPEN"), openPredictions = predictions.map(record => record.payload).filter(item => item.status === "OPEN"), cameraRecords = await jsonl(join(timeline, "camera-ranges.jsonl")), narrationProblems = narrationRecords.filter(record => record.payload.validation?.valid === false || record.payload.status === "FAILED"), cameraProblems = cameraRecords.filter(record => ["FAILED", "ABORTED"].includes(record.payload.status) || record.payload.cameraQuality === "BAD"); await writeFile(join(reports, "unresolved-promises.csv"), `promise_id,thread_id,question,due_ms\n${openPromises.map(item => [item.promiseId, item.threadId, item.question, item.dueMs].map(csv).join(",")).join("\n")}`); await writeFile(join(reports, "camera-problems.csv"), `decision_id,time_ms,status,reason\n${cameraProblems.map(record => [record.payload.decisionId, record.recordingTimeMs, record.payload.status, record.payload.reason].map(csv).join(",")).join("\n")}`); await writeFile(join(reports, "narration-problems.csv"), `request_id,time_ms,errors,text\n${narrationProblems.map(record => [record.payload.requestId || record.payload.narrationId, record.recordingTimeMs, (record.payload.validation?.errors || []).join("|"), record.payload.text].map(csv).join(",")).join("\n")}`);
    const summary = `# Documentary session summary\n\n- Session: ${session.id}\n- Duration: ${Math.round(session.manifest.elapsedMs || 0)} ms\n- Records: ${session.records}\n- Verified events: ${events.length}\n- Narration assets: ${assets.length}\n- Highlights: ${highlights.length}\n- Stagnant windows: ${stagnant.length}\n- Unresolved promises: ${openPromises.length}\n- Unresolved predictions: ${openPredictions.length}\n`; await writeFile(join(reports, "session-summary.md"), summary);
    const roughCut = { schemaVersion: 1, sessionId: session.id, sourceUnmodified: true, segments: windows.filter(item => item.classification !== "STAGNANT_REMOVE").map(item => ({ sourceStartMs: item.startMs, sourceEndMs: item.endMs, speed: item.classification === "STAGNANT_COMPRESS" ? 4 : 1, classification: item.classification })) }; await writeFile(join(editing, "rough-cut-plan.json"), JSON.stringify(roughCut, null, 2)); await writeFile(join(editing, "chapters.ffmetadata"), `;FFMETADATA1\n${highlights.map((item, index) => `[CHAPTER]\nTIMEBASE=1/1000\nSTART=${Math.round(item.startMs)}\nEND=${Math.round(item.endMs || item.startMs + 1000)}\ntitle=Highlight ${index + 1}\n`).join("")}`); await writeFile(join(editing, "edit-decisions.edl"), windows.map((item, index) => `${String(index + 1).padStart(3, "0")} AX V C ${stamp(item.startMs).replace(",", ":")} ${stamp(item.endMs).replace(",", ":")} ${stamp(item.startMs).replace(",", ":")} ${stamp(item.endMs).replace(",", ":")} * ${item.classification}`).join("\n")); await writeFile(join(session.root, "thumbnails", "thumbnail-plan.json"), JSON.stringify({ sourceUnmodified: true, items: highlights.map((item, index) => ({ id: `highlight-${index + 1}`, sourceTimeMs: Math.round((item.startMs + (item.endMs || item.startMs)) / 2), outputFile: `highlight-${String(index + 1).padStart(3, "0")}.jpg` })) }, null, 2)); const editingHtml = `<!doctype html><meta charset="utf-8"><title>Editing report ${html(session.id)}</title><style>body{font:16px system-ui;max-width:900px;margin:2rem auto;padding:0 1rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:.4rem;text-align:left}</style><h1>Editing report</h1><p>${session.records} records · ${highlights.length} highlights · ${stagnant.length} stagnant windows.</p><h2>Highlights</h2><table><tr><th>Class</th><th>Start</th><th>End</th><th>Reasons</th></tr>${highlights.map(item => `<tr><td>${html(item.classification)}</td><td>${item.startMs}</td><td>${item.endMs}</td><td>${html((item.reasons || []).join(", "))}</td></tr>`).join("")}</table><h2>Unresolved narrative promises</h2><ul>${openPromises.map(item => `<li>${html(item.question)}</li>`).join("") || "<li>None</li>"}</ul>`; await writeFile(join(reports, "editing-report.html"), editingHtml);
    const files = await readdir(join(session.root, "narration")); return { events: events.length, assets: assets.length, highlights: highlights.length, files };
  }
}
