import { NARRATION_RESULT_JSON_SCHEMA } from "../../src/documentary/schemas.js";

const systemPrompt = `You write an original natural-history voice called Controlled Cinematic Naturalism. Return only the required JSON object. For SUMMARY tasks, connect the time-ordered verifiedDevelopments into a cohesive chapter overview; do not paraphrase only the current shot. Drama must come from selection, sequence and contrast of supplied facts. You may reorganize facts but may not expand the factual world. Use only verifiedFacts, verifiedDevelopments, verifiedChanges, unresolvedFacts, permittedInterpretations and permittedPredictions. Never invent emotion, intention, animal knowledge, identity, measurements, causes or outcomes. Animal knowledge requires explicit perception evidence. Respect causal strength, uncertainty and forbiddenClaims. Prefer familiar words, active voice, varied spoken rhythm and restrained wonder. Avoid clichés, catastrophe language and imitation of any living or historical presenter. Silence or a controlled fallback is preferable to repetition. Keep within the word range. Every sentence-level claim must cite supplied support IDs.`;

export class OllamaClient {
  constructor(config) { this.config = config; this.failures = 0; this.openUntil = 0; }
  async health() { try { const response = await fetch(`${this.config.baseUrl}/api/tags`, { signal: AbortSignal.timeout(2500) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(), models = data.models?.map(item => item.name) || []; return { status: models.some(name => name === this.config.model || name.startsWith(`${this.config.model}:`)) ? "ready" : "missing-model", model: this.config.model, models }; } catch (error) { return { status: "offline", error: error.message, model: this.config.model }; } }
  async narrate(packet) { if (Date.now() < this.openUntil) throw new Error("ollama-circuit-open"); const controller = new AbortController(), timeout = setTimeout(() => controller.abort(), this.config.timeoutMs); try { const response = await fetch(`${this.config.baseUrl}/api/chat`, { method: "POST", headers: { "content-type": "application/json" }, signal: controller.signal, body: JSON.stringify({ model: this.config.model, messages: [{ role: "system", content: systemPrompt }, { role: "user", content: JSON.stringify(packet) }], stream: false, think: false, format: NARRATION_RESULT_JSON_SCHEMA, keep_alive: this.config.keepAlive, options: { temperature: 0, num_predict: Math.max(80, packet.maximumWords * 3) } }) }); if (!response.ok) throw new Error(`Ollama HTTP ${response.status}`); const data = await response.json(), result = JSON.parse(data.message?.content || "{}"); this.failures = 0; return { result, metrics: { model: data.model, totalDurationNs: data.total_duration, loadDurationNs: data.load_duration, promptEvalCount: data.prompt_eval_count, promptEvalDurationNs: data.prompt_eval_duration, evalCount: data.eval_count, evalDurationNs: data.eval_duration, doneReason: data.done_reason } }; } catch (error) { this.failures += 1; if (this.failures >= 3) this.openUntil = Date.now() + 30000; throw error; } finally { clearTimeout(timeout); }
  }
}
