import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const safeId = value => { const id = String(value || "default"); if (!/^[a-zA-Z0-9_-]{1,80}$/.test(id)) throw new TypeError("invalid profile id"); return id; };
const canonical = value => JSON.stringify(canonicalize(value));
const canonicalize = value => Array.isArray(value) ? value.map(canonicalize) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonicalize(value[key])])) : value;
const checksum = value => { let hash = 2166136261; for (const character of canonical(value)) { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 16777619); } return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; };

export class AuthorProfileManager {
  constructor(root) { this.root = resolve(root); }
  async initialise() { await mkdir(this.root, { recursive: true }); return this; }
  paths(profileId) { const id = safeId(profileId), root = resolve(this.root, id); if (!root.startsWith(`${this.root}\\`) && root !== this.root) throw new TypeError("profile path escaped root"); return { root, revisions: resolve(root, "revisions"), quarantine: resolve(root, "quarantine"), manifest: resolve(root, "manifest.json"), current: resolve(root, "current.json") }; }
  async load(profileId = "default") { const paths = this.paths(profileId); try { const manifest = JSON.parse(await readFile(paths.manifest, "utf8")), snapshot = JSON.parse(await readFile(paths.current, "utf8")); validateSnapshot(snapshot); if (manifest.currentRevision !== snapshot.revision || manifest.currentChecksum !== snapshot.profileChecksum) throw new TypeError("profile pointer mismatch"); return { profileId: safeId(profileId), manifest, snapshot }; } catch (error) { if (error.code === "ENOENT") return { profileId: safeId(profileId), manifest: null, snapshot: null }; throw error; } }
  async commit(profileId = "default", snapshot) { validateSnapshot(snapshot); const paths = this.paths(profileId); await mkdir(paths.revisions, { recursive: true }); await mkdir(paths.quarantine, { recursive: true }); const revisionName = String(snapshot.revision).padStart(8, "0"), immutablePath = resolve(paths.revisions, `${revisionName}.json`), serialized = JSON.stringify(snapshot, null, 2); try { const existing = JSON.parse(await readFile(immutablePath, "utf8")); if (existing.profileChecksum !== snapshot.profileChecksum) throw new TypeError("immutable profile revision collision"); } catch (error) { if (error.code !== "ENOENT") throw error; const temporary = `${immutablePath}.tmp-${process.pid}-${Date.now()}`; await writeFile(temporary, serialized, { encoding: "utf8", flag: "wx" }); await rename(temporary, immutablePath); }
    const verified = JSON.parse(await readFile(immutablePath, "utf8")); validateSnapshot(verified); const prior = await this.load(profileId).catch(() => ({ manifest: null })), revisions = [...new Set([...(prior.manifest?.revisions || []), snapshot.revision])].sort((a, b) => a - b), manifest = { schemaVersion: 1, profileId: safeId(profileId), currentRevision: snapshot.revision, currentChecksum: snapshot.profileChecksum, previousRevision: prior.manifest?.currentRevision ?? null, revisions, updatedAtUtc: new Date().toISOString() }, currentTemporary = `${paths.current}.tmp-${process.pid}-${Date.now()}`, manifestTemporary = `${paths.manifest}.tmp-${process.pid}-${Date.now()}`; await writeFile(currentTemporary, serialized, "utf8"); await rename(currentTemporary, paths.current); await writeFile(manifestTemporary, JSON.stringify(manifest, null, 2), "utf8"); await rename(manifestTemporary, paths.manifest); return manifest;
  }
  async rollback(profileId = "default", revision = null) { const loaded = await this.load(profileId); if (!loaded.manifest) return null; const target = revision ?? loaded.manifest.previousRevision; if (target == null || !loaded.manifest.revisions.includes(target)) return null; const paths = this.paths(profileId), snapshot = JSON.parse(await readFile(resolve(paths.revisions, `${String(target).padStart(8, "0")}.json`), "utf8")); validateSnapshot(snapshot); const temporary = `${paths.current}.tmp-${process.pid}-${Date.now()}`; await writeFile(temporary, JSON.stringify(snapshot, null, 2), "utf8"); await rename(temporary, paths.current); const manifest = { ...loaded.manifest, previousRevision: loaded.manifest.currentRevision, currentRevision: snapshot.revision, currentChecksum: snapshot.profileChecksum, updatedAtUtc: new Date().toISOString() }, manifestTemporary = `${paths.manifest}.tmp-${process.pid}-${Date.now()}`; await writeFile(manifestTemporary, JSON.stringify(manifest, null, 2), "utf8"); await rename(manifestTemporary, paths.manifest); return { manifest, snapshot }; }
}

function validateSnapshot(snapshot) { if (!snapshot || snapshot.schema !== 2 || snapshot.registryVersion !== 2 || !Number.isInteger(snapshot.revision) || snapshot.revision < 0) throw new TypeError("invalid author profile snapshot"); const { profileChecksum, ...payload } = snapshot; if (!profileChecksum || checksum(payload) !== profileChecksum) throw new TypeError("author profile checksum mismatch"); for (const record of Object.values(snapshot.policy?.records || {})) if (Math.abs(Number(record.adjustment || 0)) > .200001) throw new TypeError("author policy exceeds bound"); for (const record of Object.values(snapshot.production?.records || {})) if (Math.abs(Number(record.adjustment || 0)) > .120001) throw new TypeError("production policy exceeds bound"); return true; }

export { validateSnapshot as validateAuthorProfileSnapshot };
