import { createReadStream } from "node:fs";
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import { stat } from "node:fs/promises";
import { extname } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "./config.js";
import { attachWebSocketServer } from "./websocket-server.js";
import { SessionManager, confined } from "./session-manager.js";
import { OllamaClient } from "./ollama-client.js";
import { PiperClient } from "./piper-client.js";
import { ObsClient } from "./obs-client.js";
import { ExportManager } from "./export-manager.js";
import { AuthorProfileManager } from "./profile-manager.js";
import { parseMessage, response } from "./protocol.js";
import { fallbackNarration, validateNarrationResult } from "../../src/documentary/narration.js";

export async function createCompanion(options = {}) {
  const config = options.config || await loadConfig(options), sessions = options.services?.sessions || new SessionManager(config), recovered = await sessions.initialise(), profiles = options.services?.profiles || await new AuthorProfileManager(config.profilesDir).initialise(), ollama = options.services?.ollama || new OllamaClient(config.ollama), piper = options.services?.piper || new PiperClient(config.piper), obs = options.services?.obs || new ObsClient(config.obs), exports = options.services?.exports || new ExportManager(), peers = new Set(), peerSessions = new Map(), sessionOwners = new Map(), orphanTimers = new Map(), startedAt = Date.now();
  let controlledObsRecording = false;
  const bounded = async (label, task) => { let timer; try { return await Promise.race([task(), new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`${label}-health-timeout`)), config.healthTimeoutMs); })]); } catch (error) { return { status: "degraded", error: error.message }; } finally { clearTimeout(timer); } };
  const health = async () => { const [ollamaHealth, piperHealth, obsHealth] = await Promise.all([bounded("ollama", () => ollama.health()), bounded("piper", () => piper.health()), bounded("obs", () => obs.health())]); return { status: [ollamaHealth, piperHealth, obsHealth].some(item => ["offline", "degraded"].includes(item.status)) ? "degraded" : "ok", uptimeMs: Date.now() - startedAt, securityWarning: config.securityWarning || null, activeSessions: sessions.sessions.size, peers: peers.size, recoveredSessions: recovered.length, orphanGraceMs: config.orphanGraceMs, ollama: ollamaHealth, piper: piperHealth, obs: obsHealth }; };
  const server = createServer(async (request, reply) => { const url = new URL(request.url, `http://${config.host}:${config.port}`), origin = request.headers.origin; if (origin && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(origin)) reply.setHeader("access-control-allow-origin", origin); reply.setHeader("vary", "Origin"); reply.setHeader("x-content-type-options", "nosniff"); if (url.pathname === "/health") { reply.setHeader("content-type", "application/json"); return reply.end(JSON.stringify(await health())); } const audio = url.pathname.match(/^\/sessions\/([a-zA-Z0-9_-]+)\/audio\/([a-zA-Z0-9_-]+\.wav)$/); if (audio) { try { const path = confined(config.sessionsDir, audio[1], "narration", audio[2]), info = await stat(path); reply.writeHead(200, { "content-type": extname(path) === ".wav" ? "audio/wav" : "application/octet-stream", "content-length": info.size, "cache-control": "no-store" }); return createReadStream(path).pipe(reply); } catch { reply.statusCode = 404; return reply.end("Not found"); } } reply.statusCode = 404; reply.end("Not found"); });
  const websocket = attachWebSocketServer(server, { token: config.token, maximum: config.maxMessageBytes, path: "/documentary" });
  const sendError = (peer, requestId, error) => peer.send(response("ERROR", requestId || "unknown", { error: String(error.message || error).replace(config.obs.password || "\u0000", "[redacted]") }));
  const finalizeSession = async (sessionId, reason, status = "COMPLETE") => { clearTimeout(orphanTimers.get(sessionId)); orphanTimers.delete(sessionId); let recording = null; if (config.obs.enabled && controlledObsRecording) try { recording = await obs.stopRecording(); controlledObsRecording = false; } catch (error) { recording = { error: error.message }; } const session = await sessions.stop(sessionId, reason, { status, recording }); if (!session) return null; const exportResult = await exports.generate(session); sessionOwners.delete(sessionId); return { session, recording, exportResult }; };
  const ensureObsRunning = async () => { try { await obs.connect(); return { launched: false }; } catch {} const child = spawn(config.obs.executable, [], { cwd: dirname(config.obs.executable), detached: true, stdio: "ignore", windowsHide: false }); child.unref(); const started = Date.now(); while (Date.now() - started < config.obs.launchTimeoutMs) { await new Promise(resolve => setTimeout(resolve, 750)); try { obs.close(); await obs.connect(); return { launched: true, processId: child.pid }; } catch {} } throw new Error("OBS launched but its WebSocket did not become ready before the timeout"); };
  const scheduleOrphanFinalization = sessionId => { if (!sessions.get(sessionId) || orphanTimers.has(sessionId)) return; const timer = setTimeout(() => { void finalizeSession(sessionId, "companion-peer-disconnected", "ABANDONED"); }, config.orphanGraceMs); timer.unref?.(); orphanTimers.set(sessionId, timer); };
  websocket.on("connection", peer => { peers.add(peer); peerSessions.set(peer, new Set()); peer.send({ schemaVersion: 1, type: "HELLO", capabilities: { schemaVersion: 1, ollama: true, piper: true, obs: config.obs.enabled, recovery: true, exports: true, orphanWatchdog: true, onDemandObsLaunch: true, versionedAuthorProfiles: true } }); peer.on("close", () => { peers.delete(peer); for (const sessionId of peerSessions.get(peer) || []) { if (sessionOwners.get(sessionId) === peer) { sessionOwners.delete(sessionId); scheduleOrphanFinalization(sessionId); } } peerSessions.delete(peer); }); peer.on("error", () => {}); peer.on("message", async raw => { let message; try { message = parseMessage(raw, config.maxMessageBytes); if (message.type === "AUTHOR_PROFILE_LOAD") { const loaded = await profiles.load(message.profileId || "default"); peer.send(response("AUTHOR_PROFILE_LOADED", message.requestId, loaded)); return; }
      if (message.type === "AUTHOR_PROFILE_COMMIT") { const manifest = await profiles.commit(message.profileId || "default", message.snapshot); peer.send(response("AUTHOR_PROFILE_COMMITTED", message.requestId, { profileId: message.profileId || "default", manifest })); return; }
      if (message.type === "AUTHOR_PROFILE_ROLLBACK") { const result = await profiles.rollback(message.profileId || "default", message.revision ?? null); peer.send(response("AUTHOR_PROFILE_ROLLED_BACK", message.requestId, { profileId: message.profileId || "default", result })); return; }
      if (message.type === "START_SESSION") { const currentOwner = sessionOwners.get(message.sessionId); if (currentOwner && currentOwner !== peer) throw new Error("session-already-owned"); clearTimeout(orphanTimers.get(message.sessionId)); orphanTimers.delete(message.sessionId); const existed = Boolean(sessions.get(message.sessionId)); let obsStatus = { mode: "manual", recording: false }; if (config.obs.enabled && message.metadata?.configuration?.obsEnabled === true) { const launch = await ensureObsRunning(); const recordStatus = await obs.recordingStatus(); if (!recordStatus.outputActive) await obs.startRecording(); controlledObsRecording = true; obsStatus = { mode: "controlled", recording: true, resumed: existed, ...launch }; } const session = await sessions.start({ sessionId: message.sessionId, metadata: message.metadata }); sessionOwners.set(session.id, peer); peerSessions.get(peer).add(session.id); peer.send(response("SESSION_STARTED", message.requestId, { sessionId: session.id, elapsedMs: sessions.elapsedMs(session), obs: obsStatus, duplicate: existed })); return; }
      if (message.type === "SET_OBS_RECORDING") { if (!config.obs.enabled) throw new Error("OBS control is disabled in companion configuration"); let recording = null, launch = { launched: false }; if (message.enabled) { launch = await ensureObsRunning(); const status = await obs.recordingStatus(); if (!status.outputActive) await obs.startRecording(); controlledObsRecording = true; recording = await obs.recordingStatus(); } else { try { const status = await obs.recordingStatus(); recording = status.outputActive ? await obs.stopRecording() : status; controlledObsRecording = false; } catch (error) { controlledObsRecording = false; recording = { outputActive: false, warning: error.message }; } } peer.send(response("OBS_RECORDING_STATE", message.requestId, { enabled: Boolean(message.enabled), recording: controlledObsRecording, launch, details: recording })); return; }
      if (message.type === "EVENT_BATCH") { const result = await sessions.append(message.sessionId, message.batchId || message.requestId, message.records); peer.send(response("ACK", message.requestId, { batchId: message.batchId || message.requestId, ...result })); return; }
      if (message.type === "CHECKPOINT") { const checkpointId = await sessions.checkpoint(message.sessionId, message.checkpoint); peer.send(response("ACK", message.requestId, { checkpointId })); return; }
      if (message.type === "CLOCK_REQUEST") { const session = sessions.get(message.sessionId); if (!session) throw new Error("unknown-session"); peer.send(response("CLOCK_SYNC", message.requestId, { sessionId: session.id, serverElapsedMs: sessions.elapsedMs(session) })); return; }
      if (message.type === "NARRATION_REQUEST") { const session = sessions.get(message.sessionId); if (!session) throw new Error("unknown-session"); let generated, metrics, validation, fallback = false; try { const output = await ollama.narrate(message.packet); generated = output.result; metrics = output.metrics; validation = validateNarrationResult(generated, message.packet, { nowMs: sessions.elapsedMs(session) }); if (!validation.valid) { generated = fallbackNarration(message.packet); fallback = true; } } catch (error) { generated = fallbackNarration(message.packet); metrics = { error: error.message }; validation = { valid: false, errors: [error.message] }; fallback = true; } let asset = null; if (generated.text && (!Number.isFinite(message.packet.deadlineMs) || sessions.elapsedMs(session) <= message.packet.deadlineMs)) { try { asset = await piper.synthesize({ narrationId: message.packet.requestId, text: generated.text, sessionRoot: session.root }); asset.audioUrl = `/sessions/${session.id}/audio/${asset.fileName}`; } catch (error) { asset = { status: "subtitle-only", error: error.message }; } } peer.send(response("NARRATION_READY", message.requestId, { sessionId: session.id, result: generated, validation, fallback, metrics, asset, expiresAtMs: message.packet.deadlineMs || null })); return; }
      if (message.type === "STOP_SESSION") { const result = await finalizeSession(message.sessionId, message.reason); if (!result) throw new Error("unknown-session"); peerSessions.get(peer)?.delete(message.sessionId); peer.send(response("SESSION_STOPPED", message.requestId, { sessionId: result.session.id, elapsedMs: result.session.manifest.elapsedMs, exportResult: result.exportResult, recording: result.recording })); return; }
      if (message.type === "HEALTH_REQUEST") { peer.send(response("HEALTH", message.requestId, await health())); return; }
      throw new Error(`unsupported-message:${message.type}`);
    } catch (error) { sendError(peer, message?.requestId, error); } }); });
  const clockTimer = setInterval(() => { for (const session of sessions.sessions.values()) sessionOwners.get(session.id)?.send({ schemaVersion: 1, type: "CLOCK_SYNC", requestId: `clock-${Date.now()}`, sessionId: session.id, serverElapsedMs: sessions.elapsedMs(session) }); }, 5000); clockTimer.unref();
  return { config, server, sessions, profiles, ollama, piper, obs, health, async listen() { await new Promise((resolve, reject) => { server.once("error", reject); server.listen(config.port, config.host, resolve); }); return server.address(); }, async close() { clearInterval(clockTimer); for (const timer of orphanTimers.values()) clearTimeout(timer); for (const peer of peers) peer.close(); for (const session of [...sessions.sessions.values()]) await finalizeSession(session.id, "companion-shutdown", "ABANDONED"); obs.close(); await new Promise(resolve => server.close(() => resolve())); } };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === (await import("node:path")).resolve(process.argv[1])) {
  const companion = await createCompanion(); const address = await companion.listen(); console.log(`Documentary companion listening on http://${address.address}:${address.port}`); if (companion.config.securityWarning) console.warn(companion.config.securityWarning);
}
