import { mkdir, open, readFile, readdir, rename, stat, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve, sep } from "node:path";
import { validateDocumentaryRecord } from "../../src/documentary/schemas.js";

const safeName = value => String(value || "session").replace(/[^a-zA-Z0-9_-]/g, "-").slice(0, 96);
export function confined(root, ...parts) { const target = resolve(root, ...parts), prefix = resolve(root) + sep; if (target !== resolve(root) && !target.startsWith(prefix)) throw new Error("path escapes session root"); return target; }
async function atomicJson(path, value) { const temporary = `${path}.${process.pid}.tmp`; await writeFile(temporary, JSON.stringify(value, null, 2)); await rename(temporary, path); }

export class TimelineWriter {
  constructor(root) { this.root = root; this.handles = new Map(); this.queue = Promise.resolve(); this.recordIds = new Set(); this.failed = 0; }
  append(name, records) { this.queue = this.queue.then(async () => { const accepted = []; for (const record of records) { const validation = validateDocumentaryRecord(record); if (!validation.valid) throw new TypeError(validation.errors.join(", ")); if (this.recordIds.has(record.recordId)) continue; this.recordIds.add(record.recordId); accepted.push(record); } if (!accepted.length) return 0; let handle = this.handles.get(name); if (!handle) { const path = confined(this.root, "timeline", `${safeName(name)}.jsonl`); handle = await open(path, "a"); this.handles.set(name, handle); } await handle.write(accepted.map(record => `${JSON.stringify(record)}\n`).join("")); await handle.sync(); return accepted.length; }).catch(error => { this.failed += 1; throw error; }); return this.queue; }
  async close() { await this.queue.catch(() => {}); await Promise.all([...this.handles.values()].map(handle => handle.close())); this.handles.clear(); }
}

export class SessionManager {
  constructor({ sessionsDir }) { this.sessionsDir = sessionsDir; this.sessions = new Map(); }
  async initialise() { await mkdir(this.sessionsDir, { recursive: true }); return this.recoverIncomplete(); }
  async start(metadata = {}) { const id = safeName(metadata.sessionId || metadata.metadata?.sessionId || `run-${Date.now()}`), existing = this.sessions.get(id); if (existing) return existing; const root = confined(this.sessionsDir, id); await Promise.all(["video", "timeline", "narration", "checkpoints", "reports", "editing", "thumbnails"].map(part => mkdir(confined(root, part), { recursive: true }))); const manifest = { schemaVersion: 1, sessionId: id, status: "RECORDING", startedAtUtc: new Date().toISOString(), ...metadata.metadata }; const session = { id, root, manifest, writer: new TimelineWriter(root), startedMonotonicNs: process.hrtime.bigint(), batches: new Set(), records: 0 }; this.sessions.set(id, session); await atomicJson(confined(root, "session.json"), manifest); return session; }
  get(id) { return this.sessions.get(safeName(id)) || null; }
  elapsedMs(session) { return Number(process.hrtime.bigint() - session.startedMonotonicNs) / 1e6; }
  async append(sessionId, batchId, records) { const session = this.get(sessionId); if (!session) throw new Error("unknown-session"); if (session.batches.has(batchId)) return { accepted: 0, duplicate: true }; const groups = new Map(); for (const record of records) { const name = ({ documentary_event: "events", event_range: "event-ranges", camera_decision: "camera-ranges", story_thread: "story-threads", prediction: "predictions", promise: "promises", editorial_window: "editorial-windows", manual_marker: "manual-markers", narration_request: "narration", narration_result: "narration", narration_asset: "narration" })[record.recordType] || "production"; const list = groups.get(name) || []; list.push(record); groups.set(name, list); } let accepted = 0; for (const [name, items] of groups) accepted += await session.writer.append(name, items); session.batches.add(batchId); session.records += accepted; if (session.batches.size > 20000) session.batches.delete(session.batches.values().next().value); return { accepted, duplicate: false }; }
  async checkpoint(sessionId, checkpoint) { const session = this.get(sessionId); if (!session) throw new Error("unknown-session"); const id = safeName(checkpoint.checkpointId || `checkpoint-${Date.now()}`); await atomicJson(confined(session.root, "checkpoints", `${id}.json`), checkpoint); return id; }
  async stop(sessionId, reason = "operator-stop", details = {}) { const session = this.get(sessionId); if (!session) return null; await session.writer.close(); session.manifest = { ...session.manifest, ...details, status: details.status || "COMPLETE", stoppedAtUtc: new Date().toISOString(), elapsedMs: this.elapsedMs(session), records: session.records, reason }; await atomicJson(confined(session.root, "session.json"), session.manifest); await writeFile(confined(session.root, ".complete"), session.manifest.stoppedAtUtc); this.sessions.delete(session.id); return session;
  }
  async recoverIncomplete() { const reports = []; for (const entry of await readdir(this.sessionsDir, { withFileTypes: true })) { if (!entry.isDirectory()) continue; const root = confined(this.sessionsDir, entry.name); let manifest; try { manifest = JSON.parse(await readFile(confined(root, "session.json"), "utf8")); await stat(confined(root, ".complete")); continue; } catch {} if (!manifest) continue; const report = { sessionId: entry.name, detectedAtUtc: new Date().toISOString(), previousStatus: manifest.status, action: "retained-append-only-files", discontinuity: true }; await mkdir(confined(root, "reports"), { recursive: true }); await writeFile(confined(root, "reports", "recovery-report.md"), `# Recovery report\n\nSession: ${entry.name}\n\nThe previous process did not write a completion marker. Existing append-only files were retained. Validate media alignment across the discontinuity before editing.\n`); manifest.status = "RECOVERABLE"; manifest.recovery = report; await atomicJson(confined(root, "session.json"), manifest); reports.push(report); } return reports; }
}
