import { createHash } from "node:crypto";
import { EventEmitter } from "node:events";

const GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
const acceptKey = key => createHash("sha1").update(key + GUID).digest("base64");
const frame = value => { const payload = Buffer.from(typeof value === "string" ? value : JSON.stringify(value)), header = payload.length < 126 ? Buffer.from([0x81, payload.length]) : payload.length < 65536 ? Buffer.from([0x81, 126, payload.length >> 8, payload.length & 255]) : (() => { const head = Buffer.alloc(10); head[0] = 0x81; head[1] = 127; head.writeBigUInt64BE(BigInt(payload.length), 2); return head; })(); return Buffer.concat([header, payload]); };

function parseFrames(buffer, maximum) { const messages = []; let offset = 0; while (buffer.length - offset >= 2) { const first = buffer[offset], second = buffer[offset + 1], opcode = first & 0x0f, masked = Boolean(second & 0x80); let length = second & 0x7f, header = 2; if (length === 126) { if (buffer.length - offset < 4) break; length = buffer.readUInt16BE(offset + 2); header = 4; } else if (length === 127) { if (buffer.length - offset < 10) break; const big = buffer.readBigUInt64BE(offset + 2); if (big > BigInt(maximum)) throw new Error("message-too-large"); length = Number(big); header = 10; } if (length > maximum) throw new Error("message-too-large"); const maskLength = masked ? 4 : 0, total = header + maskLength + length; if (buffer.length - offset < total) break; const payload = Buffer.from(buffer.subarray(offset + header + maskLength, offset + total)); if (masked) { const mask = buffer.subarray(offset + header, offset + header + 4); for (let i = 0; i < payload.length; i += 1) payload[i] ^= mask[i % 4]; } messages.push({ opcode, payload }); offset += total; } return { messages, remaining: buffer.subarray(offset) }; }

export class WebSocketPeer extends EventEmitter {
  constructor(socket, maximum) { super(); this.socket = socket; this.maximum = maximum; this.buffer = Buffer.alloc(0); this.closed = false; socket.on("data", chunk => this.receive(chunk)); socket.on("close", () => { this.closed = true; this.emit("close"); }); socket.on("error", error => this.emit("error", error)); }
  receive(chunk) { try { this.buffer = Buffer.concat([this.buffer, chunk]); const parsed = parseFrames(this.buffer, this.maximum); this.buffer = parsed.remaining; for (const item of parsed.messages) { if (item.opcode === 0x8) return this.close(); if (item.opcode === 0x9) { this.socket.write(Buffer.concat([Buffer.from([0x8a, item.payload.length]), item.payload])); continue; } if (item.opcode === 0x1) this.emit("message", item.payload.toString("utf8")); } } catch (error) { this.emit("error", error); this.close(1009); } }
  send(value) { if (!this.closed) this.socket.write(frame(value)); }
  close(code = 1000) { if (this.closed) return; this.closed = true; const payload = Buffer.alloc(2); payload.writeUInt16BE(code); this.socket.end(Buffer.concat([Buffer.from([0x88, 2]), payload])); }
}

export function attachWebSocketServer(server, { token, maximum = 1048576, path = "/documentary" } = {}) {
  const emitter = new EventEmitter(); server.on("upgrade", (request, socket) => { try { const url = new URL(request.url, "http://127.0.0.1"), supplied = url.searchParams.get("token") || request.headers.authorization?.replace(/^Bearer\s+/i, ""); if (!token || token.length < 16) { socket.write("HTTP/1.1 503 Service Unavailable\r\nConnection: close\r\n\r\n"); return socket.destroy(); } if (url.pathname !== path || supplied !== token) { socket.write("HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n"); return socket.destroy(); } const key = request.headers["sec-websocket-key"]; if (!key || request.headers.upgrade?.toLowerCase() !== "websocket") return socket.destroy(); socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${acceptKey(key)}\r\n\r\n`); const peer = new WebSocketPeer(socket, maximum); emitter.emit("connection", peer, request); } catch { socket.destroy(); } }); return emitter;
}
