import { expect, test } from "@playwright/test";

test("documentary director selects validated shots and restores the observer camera", async ({ page }) => {
  const errors = []; page.on("pageerror", error => errors.push(String(error)));
  await page.goto("/?test=1"); await page.waitForFunction(() => window.rssDiagnostics?.startMovie);
  const ordinary = await page.evaluate(() => ({ vision: document.querySelector("#overlay-vision")?.checked, water: document.querySelector("#overlay-water")?.checked }));
  const before = await page.evaluate(() => window.rssDiagnostics.movieState().camera); await page.evaluate(() => window.rssDiagnostics.startMovie()); await page.waitForTimeout(350); expect(Number(await page.locator("#movie-transition-layer").evaluate(element => getComputedStyle(element).opacity))).toBeGreaterThan(0); await page.waitForFunction(() => window.rssDiagnostics.movieState().shot.metrics.valid === true, null, { timeout: 5_000 });
  const first = await page.evaluate(() => window.rssDiagnostics.movieState());
  expect(first.active).toBe(true); expect(first.shot.metrics.valid).toBe(true); expect(first.shot.metrics.visibility).toBeGreaterThan(.3); expect(first.shot.transition.type).toBe("dip"); expect(first.shot.beat).toBeTruthy(); expect(first.shot.scale).toBe("wide"); expect(first.shot.duration).toBeGreaterThan(first.shot.minimumDuration); expect(Object.values(first.effectiveLens).some(Boolean)).toBe(false); expect(await page.locator("#movie-captions").isVisible()).toBe(false); expect(await page.locator("#movie-lens-preset").inputValue()).toBe("adaptive"); expect(await page.locator(".movie-lens-controls").evaluate(element => element.open)).toBe(false);
  expect(first.planningProfile.generatedCandidates).toBeGreaterThan(first.planningProfile.fullyValidatedCandidates); expect(first.planningProfile.fullyValidatedCandidates).toBeLessThanOrEqual(4); expect(first.planningProfile.cheapValidationPasses).toBeGreaterThan(0); expect(first.planningProfile.fullValidationPasses).toBeLessThanOrEqual(6);
  await page.waitForFunction(() => { const presentation = window.rssDiagnostics.moviePopulationPresentation(); return presentation.mode === "region" && presentation.individualAnimalCount === 0 && presentation.markerKinds.length > 0 && presentation.markerKinds.every(kind => kind === "region-count"); }, null, { timeout: 5_000 });
  await page.evaluate(() => window.rssDiagnostics.nextMovieShot()); await page.waitForTimeout(1900); const narratedShot = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(["medium", "close"]).toContain(narratedShot.shot.scale); await expect(page.locator("#movie-captions")).toContainText(/\w{8,}/); expect(await page.locator("#movie-captions").isVisible()).toBe(true);
  const narratedPopulation = await page.evaluate(() => window.rssDiagnostics.moviePopulationPresentation()); if (narratedShot.shot.scale === "medium") { expect(narratedPopulation.mode).toBe("group"); expect(narratedPopulation.individualAnimalCount).toBe(0); expect(narratedPopulation.markerKinds.length).toBeGreaterThan(0); expect(narratedPopulation.markerKinds.every(kind => ["organization", "group", "local-count"].includes(kind))).toBe(true); } else expect(narratedPopulation.mode).toBe("entity");
  const narratedDuration = narratedShot.shot.duration; await page.locator("#movie-captions-enabled").evaluate(node => { node.checked = false; node.dispatchEvent(new Event("change", { bubbles: true })); }); await page.locator("#movie-narration-enabled").evaluate(node => { node.checked = false; node.dispatchEvent(new Event("change", { bubbles: true })); }); expect(await page.locator("#movie-captions").isVisible()).toBe(false); expect((await page.evaluate(() => window.rssDiagnostics.movieState())).shot.duration).toBeLessThanOrEqual(narratedDuration);
  await page.locator("#movie-narration-enabled").evaluate(node => { node.checked = true; node.dispatchEvent(new Event("change", { bubbles: true })); }); await page.locator("#movie-captions-enabled").evaluate(node => { node.checked = true; node.dispatchEvent(new Event("change", { bubbles: true })); }); await page.waitForTimeout(1900); expect(await page.locator("#movie-captions").isVisible()).toBe(true);
  await page.locator("#movie-panel-narration-preset").evaluate(node => { node.value = "deep"; node.dispatchEvent(new Event("change", { bubbles: true })); }); expect(await page.locator("#movie-panel-narration-context").inputValue()).toBe("5"); expect(await page.locator("#movie-panel-narration-length").inputValue()).toBe("extended"); expect(await page.locator("#movie-narration-context").inputValue()).toBe("5");
  await page.locator("#movie-panel-narration-context").evaluate(node => { node.value = "2"; node.dispatchEvent(new Event("change", { bubbles: true })); }); expect(await page.locator("#movie-panel-narration-preset").inputValue()).toBe("custom"); expect(await page.locator("#movie-narration-preset").inputValue()).toBe("custom");
  await page.keyboard.press("Shift"); await page.locator(".movie-lens-controls summary").click(); await page.locator('[data-movie-channel="thoughts"]').selectOption("never"); await page.locator('[data-movie-channel="physiology"]').selectOption("always");
  const overridden = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(overridden.effectiveLens.thoughts).toBe(false); expect(overridden.effectiveLens.physiology).toBe(true);
  await page.evaluate(() => document.activeElement?.blur()); await page.mouse.move(2, 2); await page.waitForTimeout(3400); expect(await page.locator("#movie-hud").evaluate(element => element.classList.contains("movie-hud-hidden"))).toBe(true);
  await page.keyboard.press("Shift"); expect(await page.locator("#movie-hud").evaluate(element => element.classList.contains("movie-hud-hidden"))).toBe(false);
  await page.evaluate(() => window.rssDiagnostics.nextMovieShot()); await page.waitForTimeout(100); const second = await page.evaluate(() => window.rssDiagnostics.movieState());
  expect(second.history).toHaveLength(2); expect(second.shot.context).toBeTruthy(); expect(["cut", "blend", "dip", "travel"]).toContain(second.shot.transition.type);
  await page.locator('[data-movie-channel="physiology"]').selectOption("auto"); await page.locator("#movie-lens-preset").selectOption("natural"); const natural = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(Object.values(natural.effectiveLens).some(Boolean)).toBe(false);
  await page.locator("#movie-lens-preset").selectOption("ecology"); const ecology = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(ecology.effectiveLens.physiology).toBe(true); expect(ecology.effectiveLens.decisions).toBe(true);
  await page.locator("#movie-production-preset").selectOption("overview"); await page.waitForTimeout(120); const world = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(world.presetName).toBe("overview"); expect(world.subjectMode).toBe("world"); expect(world.shot.subjectIds).toEqual([]); expect(["landscape", "waterhole", "habitat-landmark", "weather-system", "hydrology", "vegetation-transition", "terrain-transition"]).toContain(world.shot.kind); expect(world.effectiveLens.identity).toBe(false);
  await page.locator("#movie-production-preset").selectOption("follow"); await page.waitForTimeout(120); const follow = await page.evaluate(() => window.rssDiagnostics.movieState()); expect(follow.presetName).toBe("follow"); expect(follow.subjectMode).toBe("characters"); expect(await page.locator("#movie-ai-enabled").isChecked()).toBe(false);
  const recoveryBefore = await page.evaluate(() => window.rssDiagnostics.movieCameraRecoveryState().recoveryCount); expect(await page.evaluate(() => window.rssDiagnostics.injectMovieCameraFault())).toBe(true); await page.waitForFunction(count => window.rssDiagnostics.movieCameraRecoveryState().recoveryCount > count, recoveryBefore); const automaticRecovery = await page.evaluate(() => window.rssDiagnostics.movieCameraRecoveryState()); expect(automaticRecovery.poseFinite).toBe(true); expect(automaticRecovery.lastReason).toBe("non-finite-inherited-camera"); expect((await page.evaluate(() => window.rssDiagnostics.movieState())).active).toBe(true);
  const reportRecoveryBefore = automaticRecovery.recoveryCount; await page.evaluate(() => { const code = document.querySelector("#movie-audience-fault-code"), severity = document.querySelector("#movie-audience-fault-severity"); code.value = "CAMERA_BLANK_VIEW"; severity.value = "UNUSABLE"; document.querySelector("#movie-audience-report-fault").click(); }); await page.waitForFunction(count => window.rssDiagnostics.movieCameraRecoveryState().recoveryCount > count, reportRecoveryBefore); expect(await page.locator("#movie-audience-scene-status").textContent()).toContain("camera repaired immediately");
  await page.locator(".movie-cinema-controls summary").first().click(); await page.locator("#movie-shot-length").selectOption("short"); await page.locator("#movie-shot-types").selectOption("wildlife"); await page.locator("#movie-motion-types").selectOption("still"); expect(await page.locator("#movie-shot-length").inputValue()).toBe("short");
  const stopped = await page.evaluate(() => window.rssDiagnostics.stopMovie()); const restored = await page.evaluate(() => ({ vision: document.querySelector("#overlay-vision")?.checked, water: document.querySelector("#overlay-water")?.checked })); expect(stopped.active).toBe(false); expect(stopped.camera.x).toBeCloseTo(before.x, 4); expect(stopped.camera.z).toBeCloseTo(before.z, 4); expect(restored).toEqual(ordinary); const narration = await page.evaluate(() => window.rssDiagnostics.movieNarrationState()); expect(narration).toMatchObject({ active: false, finalizing: false, immediateNarration: false, companionPlaying: false, overviewPlayback: false, queuedCompanionNarration: 0, audioAttached: false, pendingRequests: 0, pendingTimeouts: 0 }); expect(errors).toEqual([]);
});

test("Cinema exclusively presents its authored subject and restores observer selection", async ({ page }) => {
  const errors = []; page.on("pageerror", error => errors.push(String(error)));
  await page.goto("/?test=1");
  await page.waitForFunction(() => window.rssDiagnostics?.startMovie && window.rssDiagnostics?.prepareBaseline);
  const observer = await page.evaluate(() => {
    const baseline = window.rssDiagnostics.prepareBaseline("follow"), names = document.querySelector("#overlay-entity-names"), preset = document.querySelector("#movie-production-preset");
    if (names) { names.checked = true; names.dispatchEvent(new Event("change", { bubbles: true })); }
    preset.value = "follow"; preset.dispatchEvent(new Event("change", { bubbles: true }));
    window.rssDiagnostics.startMovie();
    return baseline;
  });

  await page.waitForFunction(() => { const focus = window.rssDiagnostics.cinemaPanelFocusState(); if (!focus.active) return false; return focus.presentationDepth === "ring" ? !focus.ownerId && focus.narrationHighlightSubjectIds[0] === focus.presentationSubjectId : Boolean(focus.ownerId) && focus.authoritySubjectIds[0] === focus.ownerId; }, null, { timeout: 10_000 });
  await page.locator('[data-movie-channel="physiology"]').evaluate(node => { node.value = "never"; node.dispatchEvent(new Event("change", { bubbles: true })); });
  await page.waitForFunction(() => { const focus = window.rssDiagnostics.cinemaPanelFocusState(), population = window.rssDiagnostics.moviePopulationPresentation(), panels = window.rssDiagnostics.entityConstellationState(), resources = window.rssDiagnostics.report().resources; if (population.mode !== "entity" || focus.presentationDepth === "ring") return panels.length === 0 && resources.visibleEntityPanels === 0 && resources.visibleInstrumentPanels === 0; if (["full", "laboratory"].includes(focus.presentationDepth)) return panels.length === 1 && panels[0].entityId === focus.ownerId && panels[0].detailLevel === "instrument" && panels[0].cinemaInstrumentOwner && resources.visibleInstrumentPanels === 1; return panels.length === 1 && panels[0].entityId === focus.ownerId && panels[0].detailLevel === "panel" && !panels[0].selected && !panels[0].cinemaInstrumentOwner && resources.visibleEntityPanels === 1 && resources.visibleInstrumentPanels === 0 && resources.visibleOwnershipTethers === 1 && resources.visibleEntityNameplates === 0; }, null, { timeout: 10_000 });
  const cinemaSelection = await page.evaluate(() => window.rssDiagnostics.observerSelectionState()); expect(cinemaSelection.selectedId).toBe(null); expect(cinemaSelection.savedSelectedId).toBe(observer.selectedId);

  await page.locator('[data-movie-channel="physiology"]').evaluate(node => { node.value = "always"; node.dispatchEvent(new Event("change", { bubbles: true })); });
  await page.waitForFunction(() => { const focus = window.rssDiagnostics.cinemaPanelFocusState(), population = window.rssDiagnostics.moviePopulationPresentation(), panels = window.rssDiagnostics.entityConstellationState(), resources = window.rssDiagnostics.report().resources; if (population.mode !== "entity") return panels.length === 0 && resources.visibleEntityPanels === 0 && resources.visibleInstrumentPanels === 0; return panels.length === 1 && panels[0].entityId === focus.ownerId && panels[0].detailLevel === "instrument" && panels[0].cinemaInstrumentOwner && !panels[0].selected && resources.visibleEntityPanels === 1 && resources.visibleInstrumentPanels === 1 && resources.visibleOwnershipTethers === 1 && resources.visibleEntityNameplates === 0 && resources.visibleThoughts === 0; }, null, { timeout: 10_000 });

  await page.locator("#movie-production-preset").evaluate(node => { node.value = "overview"; node.dispatchEvent(new Event("change", { bubbles: true })); });
  await page.waitForFunction(() => { const focus = window.rssDiagnostics.cinemaPanelFocusState(), resources = window.rssDiagnostics.report().resources; return focus.active && focus.ownerId === null && focus.authoritySubjectIds.length === 0 && window.rssDiagnostics.entityConstellationState().length === 0 && resources.visibleEntityPanels === 0 && resources.visibleOwnershipTethers === 0 && resources.visibleEntityNameplates === 0; }, null, { timeout: 10_000 });

  await page.evaluate(() => window.rssDiagnostics.stopMovie());
  await page.waitForFunction(selectedId => { const selection = window.rssDiagnostics.observerSelectionState(), panels = window.rssDiagnostics.entityConstellationState(); return selection.selectedId === selectedId && panels.length === 1 && panels[0].entityId === selectedId && panels[0].selected && panels[0].detailLevel === "instrument"; }, observer.selectedId, { timeout: 10_000 });
  expect(errors).toEqual([]);
});
