const clamp = (value, low = -1, high = 1) => Math.max(low, Math.min(high, Number(value) || 0));
const stable = value => { const visit = item => Array.isArray(item) ? item.map(visit) : item && typeof item === "object" ? Object.fromEntries(Object.keys(item).sort().map(key => [key, visit(item[key])])) : item; return JSON.stringify(visit(value)); };
const checksum = value => { let hash = 2166136261; const source = stable(value); for (let i = 0; i < source.length; i++) { hash ^= source.charCodeAt(i); hash = Math.imul(hash, 16777619); } return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; };

export class PreferencePosterior {
  constructor(snapshot = {}, { priorPrecision = 4, maximumWeight = 250 } = {}) { this.priorPrecision = priorPrecision; this.maximumWeight = maximumWeight; this.records = new Map(Object.entries(snapshot.records || {})); this.samples = Number(snapshot.samples || 0); }
  record(key) { return this.records.get(key) || { precision: this.priorPrecision, information: 0, explicitWeight: 0, implicitWeight: 0 }; }
  mean(key) { const row = this.record(key); return clamp(row.information / Math.max(this.priorPrecision, row.precision)); }
  variance(key) { return 1 / Math.max(this.priorPrecision, this.record(key).precision); }
  predict(vector = {}) { const entries = Object.entries(vector).filter(([, value]) => Number.isFinite(Number(value)) && Number(value) !== 0); if (!entries.length) return { mean: 0, variance: 1, confidence: 0 }; let weighted = 0, scale = 0, variance = 0, confidence = 0; for (const [key, raw] of entries) { const x = clamp(raw), magnitude = Math.abs(x), row = this.record(key), evidence = Math.max(0, row.precision - this.priorPrecision); weighted += this.mean(key) * x; scale += magnitude; variance += x * x * this.variance(key); confidence += evidence / (evidence + 3) * magnitude; } return { mean: clamp(weighted / Math.max(1, scale)), variance: Math.min(1, variance / Math.max(1, entries.length)), confidence: clamp(confidence / Math.max(1, scale), 0, 1) }; }
  update(vector, response, { weight = 1, explicit = true } = {}) { const boundedWeight = clamp(weight, 0, 1), y = clamp(response); if (!boundedWeight) return []; const deltas = []; for (const [key, raw] of Object.entries(vector || {})) { const x = clamp(raw); if (!x) continue; const previous = this.record(key), implicitRoom = explicit ? Infinity : Math.max(0, previous.explicitWeight * .5 + 2 - previous.implicitWeight), applied = Math.min(boundedWeight, implicitRoom), precision = Math.min(this.maximumWeight, previous.precision + applied * x * x), information = clamp(previous.information + applied * y * x, -precision, precision), next = { precision, information, explicitWeight: previous.explicitWeight + (explicit ? applied : 0), implicitWeight: previous.implicitWeight + (explicit ? 0 : applied) }; this.records.set(key, next); deltas.push({ feature: key, before: previous.information / previous.precision, after: next.information / next.precision, weight: applied, precisionDelta: next.precision - previous.precision, informationDelta: next.information - previous.information, explicitWeightDelta: next.explicitWeight - previous.explicitWeight, implicitWeightDelta: next.implicitWeight - previous.implicitWeight }); } this.samples += boundedWeight; return deltas; }
  retract(deltas = [], sampleWeight = 0) { for (const delta of deltas) { const previous = this.record(delta.feature), precision = Math.max(this.priorPrecision, previous.precision - Math.max(0, Number(delta.precisionDelta || 0))), information = clamp(previous.information - Number(delta.informationDelta || 0), -precision, precision), next = { precision, information, explicitWeight: Math.max(0, previous.explicitWeight - Math.max(0, Number(delta.explicitWeightDelta || 0))), implicitWeight: Math.max(0, previous.implicitWeight - Math.max(0, Number(delta.implicitWeightDelta || 0))) }; if (precision === this.priorPrecision && !information && !next.explicitWeight && !next.implicitWeight) this.records.delete(delta.feature); else this.records.set(delta.feature, next); } this.samples = Math.max(0, this.samples - Math.max(0, Number(sampleWeight || 0))); }
  clearFeatures(prefixes = []) { let removed = 0; for (const key of [...this.records.keys()]) if (prefixes.some(prefix => key.startsWith(prefix))) { this.records.delete(key); removed += 1; } return removed; }
  snapshot() { return { records: Object.fromEntries(this.records), samples: this.samples }; }
}

export class AudienceProfile {
  constructor(snapshot = {}) { this.schemaVersion = 1; this.profileId = snapshot.profileId || `audience-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`; this.displayName = snapshot.displayName || "Local documentary viewer"; this.mode = snapshot.mode || "PERSONAL"; this.createdAtUtc = snapshot.createdAtUtc || new Date().toISOString(); this.lastUsedAtUtc = snapshot.lastUsedAtUtc || new Date().toISOString(); this.consent = { retainExplicitFeedback: true, retainImplicitSignals: true, retainWrittenFeedback: false, allowStartupPriming: true, allowOccasionalPrompts: true, ...(snapshot.consent || {}) }; if (this.mode === "SHARED_AGGREGATE") this.consent.retainImplicitSignals = false; this.stable = new PreferencePosterior(snapshot.stable); this.session = new PreferencePosterior(snapshot.session); this.entityAffinities = new Map(Object.entries(snapshot.entityAffinities || {})); this.sharedAggregates = new Map(Object.entries(snapshot.sharedAggregates || {})); this.directives = new Map(Object.entries(snapshot.directives || {})); this.feedbackEpisodes = new Map(Object.entries(snapshot.feedbackEpisodes || {})); this.promptState = { phase: "PRIMING", prompts: 0, dismissed: 0, scenes: 0, lastPromptScene: -Infinity, lastPromptAtMs: -Infinity, stopSession: false, ...(snapshot.promptState || {}) }; this.samples = { explicit: 0, implicit: 0, pairwise: 0, confirmedTextTags: 0, ...(snapshot.samples || {}) }; this.revision = Number(snapshot.revision || 0); this.parentRevision = snapshot.parentRevision ?? null; this.profileChecksum = snapshot.profileChecksum || null; }
  predict(vector) { const stable = this.stable.predict(vector), session = this.session.predict(vector), hasSession = this.session.samples > 0; return { mean: clamp(stable.mean * (hasSession ? .55 : 1) + session.mean * (hasSession ? .45 : 0)), variance: Math.min(1, stable.variance * (hasSession ? .55 : 1) + session.variance * (hasSession ? .45 : 0)), confidence: Math.max(stable.confidence, hasSession ? session.confidence : 0) }; }
  update(vector, value, { weight = 1, explicit = true, remember = true } = {}) { const target = remember && this.mode !== "GUEST" ? this.stable : this.session, deltas = target.update(vector, value, { weight, explicit }); if (deltas.length) { this.revision += 1; if (explicit) this.samples.explicit += 1; else this.samples.implicit += 1; } return deltas; }
  updateShared(vector, value, { weight = 1 } = {}) { const boundedWeight = clamp(weight, 0, 1), deltas = this.stable.update(vector, value, { weight: boundedWeight, explicit: true }), aggregateDeltas = []; for (const [feature, raw] of Object.entries(vector || {})) { const x = clamp(raw), observation = clamp(value * x), previous = this.sharedAggregates.get(feature) || { count: 0, sum: 0, sumSquares: 0 }, delta = { feature, countDelta: boundedWeight, sumDelta: observation * boundedWeight, sumSquaresDelta: observation * observation * boundedWeight }, next = { count: previous.count + delta.countDelta, sum: previous.sum + delta.sumDelta, sumSquares: previous.sumSquares + delta.sumSquaresDelta }; this.sharedAggregates.set(feature, next); aggregateDeltas.push(delta); } if (deltas.length) { this.revision += 1; this.samples.explicit += 1; } return { deltas, aggregateDeltas }; }
  sharedSummary(feature) { const row = this.sharedAggregates.get(feature); if (!row?.count) return { count: 0, mean: 0, variance: 1 }; const mean = row.sum / row.count, variance = Math.max(0, row.sumSquares / row.count - mean * mean); return { count: row.count, mean, variance }; }
  markEntity(id, value, mode = null) { if (!id) return; const previous = this.entityAffinities.get(id) || { mean: 0, explicitSamples: 0, implicitSamples: 0, requestedFollowMode: null }; this.entityAffinities.set(id, { ...previous, mean: clamp(previous.mean + value), explicitSamples: previous.explicitSamples + 1, requestedFollowMode: mode || previous.requestedFollowMode }); this.revision += 1; }
  entityAffinity(id) { return clamp(this.entityAffinities.get(id)?.mean || 0); }
  setDirective(key, value) { if (value == null || value === "") this.directives.delete(key); else this.directives.set(key, value); this.revision += 1; }
  clearSession() { this.session = new PreferencePosterior(); this.directives.clear(); for (const [id, episode] of this.feedbackEpisodes) if (episode.target === "session") this.feedbackEpisodes.delete(id); this.promptState.stopSession = false; this.revision += 1; }
  clearFeatures(prefixes = []) { const removed = this.stable.clearFeatures(prefixes) + this.session.clearFeatures(prefixes); if (removed) this.revision += 1; return removed; }
  rememberEpisode(id, episode) { this.feedbackEpisodes.set(id, episode); while (this.feedbackEpisodes.size > 500) this.feedbackEpisodes.delete(this.feedbackEpisodes.keys().next().value); }
  retractEpisode(id) { const episode = this.feedbackEpisodes.get(id); if (!episode || episode.retracted) return false; const target = episode.target === "session" ? this.session : this.stable; target.retract(episode.deltas, episode.sampleWeight); for (const delta of episode.aggregateDeltas || []) { const current = this.sharedAggregates.get(delta.feature); if (!current) continue; const restored = { count: Math.max(0, current.count - delta.countDelta), sum: current.sum - delta.sumDelta, sumSquares: Math.max(0, current.sumSquares - delta.sumSquaresDelta) }; if (!restored.count) this.sharedAggregates.delete(delta.feature); else this.sharedAggregates.set(delta.feature, restored); } for (const delta of episode.entityDeltas || []) { const current = this.entityAffinities.get(delta.id); if (!current) continue; const restored = { ...current, mean: clamp(current.mean - Number(delta.meanDelta || 0)), explicitSamples: Math.max(0, Number(current.explicitSamples || 0) - Number(delta.explicitSamplesDelta || 0)) }; if (!restored.mean && !restored.explicitSamples && !restored.implicitSamples) this.entityAffinities.delete(delta.id); else this.entityAffinities.set(delta.id, restored); } this.feedbackEpisodes.set(id, { ...episode, retracted: true, retractedAtUtc: new Date().toISOString() }); this.samples.explicit = Math.max(0, this.samples.explicit - 1); this.revision += 1; return true; }
  snapshot({ includeChecksum = true } = {}) { const value = { schemaVersion: 1, profileId: this.profileId, displayName: this.displayName, mode: this.mode, createdAtUtc: this.createdAtUtc, lastUsedAtUtc: this.lastUsedAtUtc, consent: { ...this.consent }, stable: this.stable.snapshot(), session: this.session.snapshot(), entityAffinities: Object.fromEntries(this.entityAffinities), sharedAggregates: Object.fromEntries(this.sharedAggregates), directives: Object.fromEntries(this.directives), feedbackEpisodes: Object.fromEntries(this.feedbackEpisodes), promptState: { ...this.promptState }, samples: { ...this.samples }, revision: this.revision, parentRevision: this.parentRevision }; return includeChecksum ? { ...value, profileChecksum: checksum(value) } : value; }
  verify() { return this.profileChecksum == null || this.profileChecksum === checksum(this.snapshot({ includeChecksum: false })); }
}

export class BrowserAudienceProfileStore {
  constructor({ key = "rss-documentary-audience-profile-v1", storage = globalThis.localStorage } = {}) { this.key = key; this.storage = storage; this.quarantined = null; }
  profileKey(profileId) { return `${this.key}:profile:${profileId}`; }
  revisionKey(profileId, revision) { return `${this.profileKey(profileId)}:revision:${revision}`; }
  manifestKey(profileId) { return `${this.profileKey(profileId)}:manifest`; }
  manifest(profileId) { try { const value = JSON.parse(this.storage?.getItem(this.manifestKey(profileId)) || "null"); return value?.schemaVersion === 1 ? value : { schemaVersion: 1, profileId, currentRevision: null, revisions: [] }; } catch { return { schemaVersion: 1, profileId, currentRevision: null, revisions: [] }; } }
  catalog() { try { const rows = JSON.parse(this.storage?.getItem(`${this.key}:catalog`) || "[]"); return Array.isArray(rows) ? rows.filter(row => row?.profileId && row.mode !== "GUEST") : []; } catch { return []; } }
  index(profile) { if (!profile || profile.mode === "GUEST") return; try { const entry = { profileId: profile.profileId, displayName: profile.displayName, mode: profile.mode, revision: profile.revision, lastUsedAtUtc: new Date().toISOString() }, rows = [entry, ...this.catalog().filter(row => row.profileId !== profile.profileId)].slice(0, 32); this.storage?.setItem(`${this.key}:catalog`, JSON.stringify(rows)); } catch {} }
  list() { return this.catalog(); }
  parse(raw) { try { const data = JSON.parse(raw || "null"); if (!data || data.schemaVersion !== 1) return null; const profile = new AudienceProfile(data); if (!profile.verify()) { this.quarantined = data; return null; } return profile; } catch { return null; } }
  load() {
    const current = this.storage?.getItem(this.key), parsed = this.parse(current);
    if (parsed) { this.index(parsed); return parsed; }
    if (current) {
      let profileId = null; try { profileId = JSON.parse(current)?.profileId || null; } catch {} const previous = this.parse(this.storage?.getItem(profileId ? `${this.profileKey(profileId)}:previous` : `${this.key}:previous`) || this.storage?.getItem(`${this.key}:previous`));
      if (previous) {
        try { this.storage?.setItem(`${this.key}:quarantined`, current); this.storage?.setItem(this.key, JSON.stringify(previous.snapshot())); } catch {}
        this.index(previous); return previous;
      }
    }
    return new AudienceProfile();
  }
  save(profile) {
    if (profile?.mode === "GUEST") return true;
    try {
      const current = this.storage?.getItem(this.key), currentProfile = this.parse(current);
      if (currentProfile?.profileId === profile.profileId && profile.revision > currentProfile.revision) profile.parentRevision = currentProfile.revision;
      const snapshot = profile.snapshot(), next = JSON.stringify(snapshot), revisionKey = this.revisionKey(profile.profileId, snapshot.revision), existing = this.storage?.getItem(revisionKey);
      if (existing && existing !== next) throw new TypeError(`audience profile revision ${snapshot.revision} is immutable`);
      if (!existing) this.storage?.setItem(revisionKey, next);
      const verified = this.parse(this.storage?.getItem(revisionKey)); if (!verified) throw new TypeError("audience revision read-back failed");
      const manifest = this.manifest(profile.profileId), revisions = [...new Set([...(manifest.revisions || []), snapshot.revision])].sort((left, right) => left - right).slice(-64);
      if (currentProfile?.profileId === profile.profileId && current) this.storage?.setItem(`${this.profileKey(profile.profileId)}:previous`, current);
      else if (current) this.storage?.setItem(`${this.key}:previous`, current);
      this.storage?.setItem(this.profileKey(profile.profileId), next);
      this.storage?.setItem(this.key, next);
      this.storage?.setItem(this.manifestKey(profile.profileId), JSON.stringify({ schemaVersion: 1, profileId: profile.profileId, currentRevision: snapshot.revision, revisions, currentChecksum: snapshot.profileChecksum }));
      profile.profileChecksum = snapshot.profileChecksum; this.index(profile); return true;
    } catch { return false; }
  }
  create(displayName = "Documentary viewer", { mode = "PERSONAL" } = {}) { const profile = new AudienceProfile({ displayName: String(displayName || "Documentary viewer").slice(0, 80), mode: mode === "SHARED_AGGREGATE" ? mode : "PERSONAL", consent: mode === "SHARED_AGGREGATE" ? { retainImplicitSignals: false } : {} }); this.save(profile); return profile; }
  select(profileId) { try { const raw = this.storage?.getItem(this.profileKey(profileId)), profile = this.parse(raw); if (!profile) return null; this.storage?.setItem(this.key, raw); this.index(profile); return profile; } catch { return null; } }
  rollback() { try { const current = this.parse(this.storage?.getItem(this.key)); if (!current) return null; const manifest = this.manifest(current.profileId), targetRevision = [...manifest.revisions].filter(revision => revision < current.revision).sort((left, right) => right - left)[0], raw = targetRevision == null ? this.storage?.getItem(`${this.profileKey(current.profileId)}:previous`) : this.storage?.getItem(this.revisionKey(current.profileId, targetRevision)), restored = this.parse(raw); if (!restored) return null; const now = this.storage?.getItem(this.key); if (now) this.storage?.setItem(`${this.profileKey(restored.profileId)}:rolled-forward`, now); this.storage?.setItem(this.key, raw); this.storage?.setItem(this.profileKey(restored.profileId), raw); this.storage?.setItem(this.manifestKey(restored.profileId), JSON.stringify({ ...manifest, currentRevision: restored.revision, currentChecksum: restored.snapshot().profileChecksum })); this.index(restored); return restored; } catch { return null; } }
  reset({ guest = false } = {}) { if (guest) return new AudienceProfile({ displayName: "Guest documentary viewer", mode: "GUEST", consent: { retainExplicitFeedback: false, retainImplicitSignals: false, retainWrittenFeedback: false } }); try { const current = this.parse(this.storage?.getItem(this.key)), profile = new AudienceProfile({ profileId: current?.profileId, displayName: current?.displayName || "Local documentary viewer", mode: current?.mode === "SHARED_AGGREGATE" ? "SHARED_AGGREGATE" : "PERSONAL", revision: Number(current?.revision || 0) + 1, parentRevision: current?.revision ?? null }); this.save(profile); return profile; } catch { return new AudienceProfile(); } }
}
