const PHASES = Object.freeze({ PRIMING: { minScenes: 0, sceneGap: 1, timeGapMs: 0, maximum: 10 }, EARLY_CALIBRATION: { minScenes: 0, sceneGap: 3, timeGapMs: 90000, maximum: 8 }, ADAPTIVE_LEARNING: { minScenes: 12, sceneGap: 6, timeGapMs: 240000, maximum: 6 }, STEADY_STATE: { minScenes: 40, sceneGap: 15, timeGapMs: 900000, maximum: 4 }, OCCASIONAL_RECHECK: { minScenes: 100, sceneGap: 30, timeGapMs: 1800000, maximum: 3 } });

export class AudiencePromptPolicy {
  phase(profile) { const samples = profile.samples.explicit + profile.samples.pairwise + profile.samples.confirmedTextTags, scenes = profile.promptState.scenes; if (!samples && profile.consent.allowStartupPriming && !profile.promptState.primingSkipped) return "PRIMING"; if (samples < 12 || scenes < 12) return "EARLY_CALIBRATION"; if (samples < 40) return "ADAPTIVE_LEARNING"; if (samples < 100) return "STEADY_STATE"; return "OCCASIONAL_RECHECK"; }
  observeScene(profile) { profile.promptState.scenes += 1; profile.promptState.phase = this.phase(profile); }
  eligible(profile, { nowMs = 0, speechActive = false, criticalEvent = false, interacting = false, faultOpen = false } = {}) { if (!profile.consent.allowOccasionalPrompts || profile.promptState.stopSession || speechActive || criticalEvent || interacting || faultOpen) return false; const phase = this.phase(profile), rule = PHASES[phase], state = profile.promptState; return state.prompts < rule.maximum && state.scenes - state.lastPromptScene >= rule.sceneGap && nowMs - state.lastPromptAtMs >= rule.timeGapMs; }
  choose(profile, candidates = [], context = {}) { if (!this.eligible(profile, context)) return null; const ranked = candidates.filter(item => item && item.preferenceKey && item.options?.length >= 2).map(item => { const prediction = profile.predict(item.featureVector || { [item.preferenceKey]: 1 }), uncertainty = Math.sqrt(prediction.variance), informationGain = uncertainty * Math.min(1, Number(item.futureDecisionFrequency ?? .5)), utility = informationGain * Math.min(1, Number(item.responseProbability ?? .7)) - Math.max(0, Number(item.interruptionCost || 0)); return { ...item, uncertainty, utility }; }).filter(item => item.utility >= .12).sort((a, b) => b.utility - a.utility); return ranked[0] || null; }
  markPrompt(profile, nowMs) { profile.promptState.prompts += 1; profile.promptState.lastPromptScene = profile.promptState.scenes; profile.promptState.lastPromptAtMs = nowMs; profile.promptState.phase = this.phase(profile); }
  dismiss(profile, { stopSession = false } = {}) { profile.promptState.dismissed += 1; if (stopSession) profile.promptState.stopSession = true; }
}

export function defaultAudienceQuestions({ subjectIds = [], subjectNames = {}, worldAvailable = true } = {}) {
  const questions = [{ questionId: "focus-balance", preferenceKey: "subject:character", text: "What should receive more attention next?", options: [{ id: "CHARACTERS", label: "Individual animals" }, { id: "WORLD", label: "Weather, water and plants" }, { id: "PERCEPTION", label: "Perception and senses" }, { id: "PHYSIOLOGY", label: "Needs and physiology" }, { id: "NO_PREFERENCE", label: "No preference" }], featureVector: { "subject:character": 1, "subject:world": -1 }, futureDecisionFrequency: .9, responseProbability: .75, interruptionCost: .05 }];
  if (subjectIds[0]) questions.push({ questionId: `follow:${subjectIds[0]}`, preferenceKey: `entity:${subjectIds[0]}`, text: `Should I continue following ${subjectNames[subjectIds[0]] || subjectIds[0]}?`, options: [{ id: "ALWAYS", label: "Follow this individual" }, { id: "IMPORTANT_CHANGES", label: "Return for important changes" }, { id: "GROUP", label: "Follow the family or group" }, { id: "NONE", label: "Show something else" }], featureVector: { [`entity:${subjectIds[0]}`]: 1 }, futureDecisionFrequency: .7, responseProbability: .8, interruptionCost: .04 });
  if (!worldAvailable) return questions.filter(item => item.questionId !== "focus-balance"); return questions;
}
