import { validateSceneFeedback, validateImplicitSignal, normalizeExplicitFeedback, normalizeImplicitSignal } from "./feedback-schema.js";
import { extractSceneFeatures, sceneFeatureVector, planningFeatureVector } from "./scene-features.js";
import { AudienceProfile, BrowserAudienceProfileStore } from "./preference-profile.js";
import { AudiencePromptPolicy, defaultAudienceQuestions } from "./prompt-policy.js";
import { parseWrittenAudienceFeedback, confirmWrittenAudienceFeedback } from "./written-feedback.js";
import { corroborateFaultReport, faultInhibitsPreference } from "./faults.js";

export class AudienceLearningSystem {
  constructor({ store = null, influenceCap = .12, maximumEvents = 1000 } = {}) { this.store = store || new BrowserAudienceProfileStore(); this.profile = this.store.load(); this.influenceCap = influenceCap; this.maximumEvents = maximumEvents; this.presentations = new Map(); this.feedbackEvents = []; this.faultReports = []; this.promptPolicy = new AudiencePromptPolicy(); this.sequence = 0; this.lastFaultByPresentation = new Map(); }
  id(kind) { return `audience-${kind}-${String(++this.sequence).padStart(8, "0")}`; }
  beginSession() { this.presentations.clear(); this.lastFaultByPresentation.clear(); this.profile.session = new this.profile.session.constructor(); this.profile.directives.clear(); for (const [id, episode] of this.profile.feedbackEpisodes) if (episode.target === "session") this.profile.feedbackEpisodes.delete(id); this.profile.promptState = { ...this.profile.promptState, prompts: 0, dismissed: 0, scenes: 0, lastPromptScene: -Infinity, lastPromptAtMs: -Infinity, stopSession: false }; return this.health(); }
  registerPresentation(input) { const presentationId = input.presentationId || this.id("presentation"), previous = this.presentations.get(presentationId), features = input.features || extractSceneFeatures(input); const record = Object.freeze({ presentationId, contractId: input.contract?.contractId || input.contractId || "", decisionId: input.contract?.decision?.decisionId || input.decisionId || "", threadId: input.contract?.threadId || "", situationId: input.contract?.situationId || "", subjectIds: Object.freeze([...(input.contract?.subjectIds || input.shot?.narrationSubjectIds || input.shot?.semanticRoleIds || [])]), features, startedAtMs: Number(input.startedAtMs ?? previous?.startedAtMs ?? 0), completedAtMs: Number(input.completedAtMs || 0), profileRevision: this.profile.revision }); this.presentations.set(presentationId, record); while (this.presentations.size > 100) this.presentations.delete(this.presentations.keys().next().value); if (!previous) this.promptPolicy.observeScene(this.profile); return record; }
  feedback(input) { const checked = validateSceneFeedback({ ...input, feedbackId: input.feedbackId || this.id("feedback"), audienceProfileId: this.profile.profileId }); if (!checked.valid) return { applied: false, errors: checked.errors }; const episode = checked.value, presentation = this.presentations.get(episode.presentationId); if (!presentation) return { applied: false, errors: ["unknown presentation"] }; const normalized = normalizeExplicitFeedback(episode), vector = sceneFeatureVector(presentation.features, { tags: episode.tags }), remember = input.remember !== false, target = remember && this.profile.mode !== "GUEST" ? "stable" : "session", inhibited = faultInhibitsPreference(this.lastFaultByPresentation.get(episode.presentationId)), shared = !inhibited && this.profile.mode === "SHARED_AGGREGATE" ? this.profile.updateShared(vector, normalized.value, { weight: normalized.confidence }) : null, deltas = inhibited ? [] : shared?.deltas || this.profile.update(vector, normalized.value, { weight: normalized.confidence, explicit: true, remember }), aggregateDeltas = shared?.aggregateDeltas || [], entityDeltas = []; if (!inhibited && this.profile.mode !== "SHARED_AGGREGATE") for (const tag of episode.tags) if (tag === "FOLLOW_ENTITY") for (const id of presentation.subjectIds) { const before = this.profile.entityAffinities.get(id) || { mean: 0, explicitSamples: 0 }; this.profile.markEntity(id, .4, "ALWAYS"); const after = this.profile.entityAffinities.get(id); entityDeltas.push({ id, meanDelta: after.mean - before.mean, explicitSamplesDelta: after.explicitSamples - before.explicitSamples }); } if (deltas.length || entityDeltas.length) this.profile.rememberEpisode(episode.feedbackId, { target, deltas, aggregateDeltas, entityDeltas, sampleWeight: normalized.confidence, presentationId: episode.presentationId, recordedAtUtc: new Date().toISOString(), retracted: false }); this.record({ type: "EXPLICIT_FEEDBACK", episode, normalized, deltas, aggregateDeltas, entityDeltas, inhibited }); if (this.profile.mode !== "GUEST") this.store.save(this.profile); return { applied: deltas.length > 0 || entityDeltas.length > 0, episode, normalized, deltas, aggregateDeltas, entityDeltas, inhibited, profileRevision: this.profile.revision }; }
  retract(feedbackId) { const applied = this.profile.retractEpisode(feedbackId); if (applied && this.profile.mode !== "GUEST") this.store.save(this.profile); this.record({ type: "EXPLICIT_FEEDBACK_RETRACTED", feedbackId, applied }); return { applied, feedbackId, profileRevision: this.profile.revision }; }
  implicit(input) { if (this.profile.mode === "SHARED_AGGREGATE") return { applied: false, reason: "shared-profile-explicit-only" }; if (!this.profile.consent.retainImplicitSignals) return { applied: false, reason: "implicit-disabled" }; const checked = validateImplicitSignal({ ...input, signalId: input.signalId || this.id("signal") }); if (!checked.valid) return { applied: false, errors: checked.errors }; const signal = checked.value, presentation = this.presentations.get(signal.presentationId); if (!presentation) return { applied: false, errors: ["unknown presentation"] }; const normalized = normalizeImplicitSignal({ ...signal, knownFault: signal.knownFault || this.lastFaultByPresentation.has(signal.presentationId) }), vector = sceneFeatureVector(presentation.features), deltas = normalized.weight ? this.profile.update(vector, normalized.value, { weight: normalized.weight, explicit: false, remember: true }) : []; if (signal.type === "FAVOURITE") for (const id of presentation.subjectIds) this.profile.markEntity(id, .5, "ALWAYS"); this.record({ type: "IMPLICIT_SIGNAL", signal, normalized, deltas }); if (deltas.length && this.profile.mode !== "GUEST") this.store.save(this.profile); return { applied: deltas.length > 0, signal, normalized, deltas, profileRevision: this.profile.revision }; }
  written(text) { return { writtenFeedbackId: this.id("written"), ...parseWrittenAudienceFeedback(text) }; }
  confirmWritten(parsed, tags, presentationId, options = {}) { const confirmed = confirmWrittenAudienceFeedback(parsed, tags); if (!confirmed.learningApplied) return { applied: false, confirmed }; this.profile.samples.confirmedTextTags += 1; const result = this.feedback({ presentationId, tags: confirmed.confirmedTags, rating: options.rating || null, direction: options.direction || (confirmed.confirmedTags.some(tag => tag.startsWith("MORE_") || tag === "FOLLOW_ENTITY") ? "MORE_LIKE_THIS" : "LESS_LIKE_THIS"), status: "CONFIRMED", remember: options.remember }); this.record({ type: "WRITTEN_FEEDBACK_CONFIRMED", writtenFeedbackId: parsed.writtenFeedbackId, confirmedTags: confirmed.confirmedTags }); return { ...result, confirmed }; }
  reportFault(input, metrics = {}) { const result = corroborateFaultReport({ ...input, reportId: input.reportId || this.id("fault") }, metrics); if (!result.valid) return result; this.faultReports.push(result.report); this.faultReports = this.faultReports.slice(-this.maximumEvents); this.lastFaultByPresentation.set(result.report.presentationId, result.report); this.record({ type: "FAULT_REPORT", report: result.report }); return result; }
  preferenceForScene(scene, policy = {}, { influenceCap = this.influenceCap } = {}) { const vector = planningFeatureVector(scene, policy), prediction = this.profile.predict(vector), ids = scene.semanticRoleIds || scene.ids || [], entityAffinity = ids.reduce((sum, id) => sum + this.profile.entityAffinity(id), 0) / Math.max(1, ids.length); return { ...prediction, vector, adjustment: Math.max(-influenceCap, Math.min(influenceCap, prediction.mean * influenceCap + entityAffinity * influenceCap * .5)) }; }
  cameraPreferences({ world = false } = {}) { const families = world ? ["establishing", "sweep", "pull-out", "aerial", "still"] : ["still", "tracking", "push-in", "orbit", "intercept"], sizes = world ? ["wide", "establishing", "medium-wide"] : ["medium", "medium-wide", "close", "wide"], rank = (values, prefix) => values.map((id, order) => ({ id, order, ...this.profile.predict({ [`${prefix}:${id}`]: 1 }) })).sort((left, right) => right.mean - left.mean || right.confidence - left.confidence || left.order - right.order); return Object.freeze({ families: Object.freeze(rank(families, "camera:family")), sizes: Object.freeze(rank(sizes, "camera:size")), stable: this.profile.predict({ "camera:motion:stable": 1 }), moving: this.profile.predict({ "camera:motion:moving": 1 }) }); }
  narrationPreferences() { const depths = ["2", "3", "5"].map((id, order) => ({ id, order, ...this.profile.predict({ [`narration:depth:${id}`]: 1 }) })).sort((left, right) => right.mean - left.mean || left.order - right.order); return Object.freeze({ depths: Object.freeze(depths), density: this.profile.predict({ "narration:density": 1 }), questions: this.profile.predict({ "narration:questions": 1 }), quiet: this.profile.predict({ "narration:quiet": 1 }), names: this.profile.predict({ "narration:names": 1 }), recap: this.profile.predict({ "narration:recap": 1 }) }); }
  compare({ featureA = {}, featureB = {}, preferred = "A", remember = true, comparisonId = null } = {}) { const keys = new Set([...Object.keys(featureA), ...Object.keys(featureB)]), vector = Object.fromEntries([...keys].map(key => [key, (Number(featureA[key]) || 0) - (Number(featureB[key]) || 0)]).filter(([, value]) => value)), direction = preferred === "B" ? -1 : preferred === "A" ? 1 : 0; if (!direction || !Object.keys(vector).length) return { applied: false, reason: "neutral-comparison" }; const shared = this.profile.mode === "SHARED_AGGREGATE" ? this.profile.updateShared(vector, direction, { weight: .9 }) : null, deltas = shared?.deltas || this.profile.update(vector, direction, { weight: .9, explicit: true, remember }); this.profile.samples.pairwise += 1; if (this.profile.mode !== "GUEST") this.store.save(this.profile); const result = { applied: deltas.length > 0, comparisonId: comparisonId || this.id("comparison"), preferred, vector, deltas, aggregateDeltas: shared?.aggregateDeltas || [], profileRevision: this.profile.revision }; this.record({ type: "PAIRWISE_PREFERENCE", ...result }); return result; }
  explain({ maximum = 6 } = {}) { const labels = { "subject:character": "recurring individual animals", "subject:world": "weather, water and plant processes", "camera:motion:stable": "stable and measured camera movement", "camera:motion:moving": "moving camera work", "camera:size:close": "close shots", "camera:size:wide": "wide environmental context", "narration:depth:2": "concise immediate narration", "narration:depth:5": "deep Laboratory explanation", "topic:perception": "perception and senses", "topic:physiology": "needs and physiology", "topic:weather": "weather", "topic:water": "water processes", "topic:plants": "plant life" }, rows = [...new Set([...this.profile.stable.records.keys(), ...this.profile.session.records.keys()])].map(key => ({ key, label: labels[key] || key.replaceAll(":", " · ").replaceAll("_", " "), ...this.profile.predict({ [key]: 1 }) })).filter(item => Math.abs(item.mean) >= .04).sort((a, b) => Math.abs(b.mean) - Math.abs(a.mean)).slice(0, maximum); return rows.map(item => ({ ...item, strength: item.confidence >= .55 ? "STRONG" : item.confidence >= .3 ? "MODERATE" : "UNCERTAIN", statement: `${item.mean >= 0 ? "Prefers" : "Avoids"} ${item.label}` })); }
  prompt(context = {}) { const candidates = defaultAudienceQuestions({ subjectIds: context.subjectIds || [], subjectNames: context.subjectNames || {}, worldAvailable: context.worldAvailable !== false }), selected = this.promptPolicy.choose(this.profile, candidates, context); if (selected) { this.promptPolicy.markPrompt(this.profile, context.nowMs || 0); this.record({ type: "PROMPT_SHOWN", questionId: selected.questionId }); } return selected; }
  answerPrompt(question, answer, { remember = false } = {}) { if (!question) return { applied: false }; const vectors = { CHARACTERS: { "subject:character": 1, "subject:world": -1 }, WORLD: { "subject:character": -1, "subject:world": 1 }, PERCEPTION: { "topic:perception": 1 }, PHYSIOLOGY: { "topic:physiology": 1 }, ALWAYS: question.preferenceKey ? { [question.preferenceKey]: 1 } : {}, IMPORTANT_CHANGES: question.preferenceKey ? { [question.preferenceKey]: .5, "rarity:rare": 1 } : {}, GROUP: { "count:small_group": 1 }, NONE: question.preferenceKey ? { [question.preferenceKey]: -1 } : {} }, vector = vectors[answer] || {}; if (!Object.keys(vector).length) return { applied: false, reason: "neutral-answer" }; const shared = this.profile.mode === "SHARED_AGGREGATE" ? this.profile.updateShared(vector, 1, { weight: 1 }) : null, deltas = shared?.deltas || this.profile.update(vector, 1, { weight: 1, explicit: true, remember }); if (question.questionId.startsWith("follow:") && this.profile.mode !== "SHARED_AGGREGATE") { const id = question.questionId.slice(7); this.profile.markEntity(id, answer === "NONE" ? -.6 : answer === "IMPORTANT_CHANGES" ? .3 : .7, answer); } if (this.profile.mode !== "GUEST") this.store.save(this.profile); this.record({ type: "PROMPT_ANSWER", questionId: question.questionId, answer, deltas, aggregateDeltas: shared?.aggregateDeltas || [] }); return { applied: true, deltas, profileRevision: this.profile.revision }; }
  applyPriming(answers = {}, { remember = true } = {}) { const vectors = []; if (answers.purpose === "characters") vectors.push({ "subject:character": 1 }); if (answers.purpose === "world") vectors.push({ "subject:world": 1 }); if (answers.purpose === "rare") vectors.push({ "rarity:rare": 1 }); if (answers.purpose === "quiet") vectors.push({ "narration:quiet": 1, "narration:density": -.8, "camera:motion:stable": 1 }); if (answers.purpose === "laboratory") vectors.push({ "channel:laboratory": 1, "narration:depth:5": 1 }); if (answers.purpose === "everything") vectors.push({ "subject:character": .5, "subject:world": .5, "channel:laboratory": 1, "content:causal-depth": 1 }); for (const topic of answers.topics || []) vectors.push({ [`topic:${String(topic).toLowerCase()}`]: 1 }); for (const choice of answers.narrationChoices || []) vectors.push({ [`narration:${String(choice).toLowerCase()}`]: 1 }); if (answers.cameraDistance) vectors.push({ [`camera:size:${answers.cameraDistance}`]: 1 }); if (answers.cameraMotion) vectors.push({ [`camera:motion:${answers.cameraMotion}`]: 1 }); if (answers.narrationDepth) vectors.push({ [`narration:depth:${answers.narrationDepth}`]: 1 }); const deltas = vectors.flatMap(vector => this.profile.mode === "SHARED_AGGREGATE" ? this.profile.updateShared(vector, 1, { weight: .8 }).deltas : this.profile.update(vector, 1, { weight: .8, explicit: true, remember })); this.profile.promptState.phase = "EARLY_CALIBRATION"; if (this.profile.mode !== "GUEST") this.store.save(this.profile); this.record({ type: "PRIMING_COMPLETED", answers, deltas }); return { applied: deltas.length > 0, deltas, profileRevision: this.profile.revision }; }
  skipPriming() { this.profile.promptState.primingSkipped = true; this.profile.promptState.phase = "EARLY_CALIBRATION"; this.record({ type: "PRIMING_SKIPPED" }); return this.health(); }
  clearSessionPreferences() { this.profile.clearSession(); this.presentations.clear(); this.lastFaultByPresentation.clear(); if (this.profile.mode !== "GUEST") this.store.save(this.profile); return this.health(); }
  setConsent(changes = {}) { this.profile.consent = { ...this.profile.consent, ...changes }; this.profile.revision += 1; if (this.profile.mode !== "GUEST") this.store.save(this.profile); return this.health(); }
  clearCameraPreferences() { const removed = this.profile.clearFeatures(["camera:"]); if (removed && this.profile.mode !== "GUEST") this.store.save(this.profile); this.record({ type: "CAMERA_PREFERENCES_CLEARED", removed }); return { removed, profileRevision: this.profile.revision }; }
  exportProfile() { return Object.freeze({ exportedAtUtc: new Date().toISOString(), profile: this.profile.snapshot(), explanation: this.explain({ maximum: 50 }), feedbackSummary: { events: this.feedbackEvents.length, faults: this.faultReports.length } }); }
  profiles() { return this.store.list?.() || []; }
  createProfile(displayName, options = {}) { this.profile = this.store.create?.(displayName, options) || new AudienceProfile({ displayName, mode: options.mode }); this.beginSession(); return this.profile; }
  selectProfile(profileId) { const selected = this.store.select?.(profileId); if (!selected) return null; this.profile = selected; this.beginSession(); return this.profile; }
  rollback() { const restored = this.store.rollback(); if (!restored) return false; this.profile = restored; return true; }
  reset(options = {}) { this.profile = this.store.reset(options); this.beginSession(); return this.profile; }
  record(event) { this.feedbackEvents.push(Object.freeze({ eventId: this.id("event"), at: Date.now(), ...event })); this.feedbackEvents = this.feedbackEvents.slice(-this.maximumEvents); }
  health() { const shared = [...this.profile.sharedAggregates.values()], sharedDisagreement = shared.length ? shared.reduce((sum, row) => { const mean = row.sum / Math.max(1, row.count); return sum + Math.max(0, row.sumSquares / Math.max(1, row.count) - mean * mean); }, 0) / shared.length : 0; return { profileId: this.profile.profileId, displayName: this.profile.displayName, mode: this.profile.mode, revision: this.profile.revision, explicitSamples: this.profile.samples.explicit, implicitSamples: this.profile.samples.implicit, confirmedTextTags: this.profile.samples.confirmedTextTags, preferenceFeatures: this.profile.stable.records.size + this.profile.session.records.size, sharedVotes: shared.reduce((maximum, row) => Math.max(maximum, row.count), 0), sharedDisagreement, promptPhase: this.promptPolicy.phase(this.profile), prompts: this.profile.promptState.prompts, promptsDisabled: this.profile.promptState.stopSession || !this.profile.consent.allowOccasionalPrompts, presentations: this.presentations.size, faults: this.faultReports.length }; }
}

export { AudienceProfile };
