const canonical = value => { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`; return JSON.stringify(value); };
const hash = value => { let result = 2166136261; for (const char of canonical(value)) { result ^= char.charCodeAt(0); result = Math.imul(result, 16777619); } return (result >>> 0).toString(36); };

export class DocumentaryAudienceMemory {
  constructor({ maximum = 2000, recentWindowTicks = 600, semanticThreshold = .78 } = {}) { this.maximum = maximum; this.recentWindowTicks = recentWindowTicks; this.semanticThreshold = semanticThreshold; this.items = new Map(); this.questions = new Map(); this.hypotheses = new Map(); this.openQuestionCount = 0; this.openHypothesisCount = 0; this.revision = 0; this.snapshotCache = null; }
  fingerprint({ predicate = "narration", subjectIds = [], arguments: args = {}, text = "" } = {}) { return `semantic-${hash({ predicate, subjectIds: [...subjectIds].sort(), arguments: args, text: normalizeMeaning(text) })}`; }
  novelty(input, tick = 0) { const fingerprint = input.fingerprint || this.fingerprint(input), exact = this.items.get(fingerprint), previous = exact || this.closest(input); if (!previous) return 1; const age = Math.max(0, tick - previous.tick), changed = input.materialRevision != null && input.materialRevision !== previous.materialRevision, similarity = exact ? 1 : semanticSimilarity(input, previous); return changed ? 1 : Math.min(.8, age / Math.max(1, this.recentWindowTicks)) * (1 - .5 * similarity); }
  hasClaim(claim, tick = 0) { return this.novelty({ fingerprint: claim.semanticFingerprint, predicate: claim.predicate, subjectIds: claim.subjectIds, arguments: claim.normalizedArguments, materialRevision: claim.materialRevision }, tick) < .12; }
  closest(input) { let best = null, score = 0; for (const item of this.items.values()) { const candidate = semanticSimilarity(input, item); if (candidate > score) { score = candidate; best = item; } } return score >= this.semanticThreshold ? best : null; }
  mark(input, tick = 0) { const fingerprint = input.fingerprint || this.fingerprint(input), item = Object.freeze({ fingerprint, predicate: input.predicate || "narration", subjectIds: Object.freeze([...(input.subjectIds || [])]), arguments: input.arguments || input.normalizedArguments || {}, tokens: meaningTokens(input.text), text: String(input.text || ""), tick, materialRevision: input.materialRevision ?? null, threadId: input.threadId || null, claimId: input.claimId || null }); this.items.set(fingerprint, item); while (this.items.size > this.maximum) this.items.delete(this.items.keys().next().value); this.#changed(); return item; }
  openQuestion(id, input = {}) { const previous = this.questions.get(id); this.questions.set(id, { id, state: "OPEN", ...input }); if (!previous || previous.state === "ANSWERED") this.openQuestionCount += 1; this.#changed(); }
  resolveQuestion(id, evidenceIds = []) { const item = this.questions.get(id); if (!item) return null; const resolved = { ...item, state: "ANSWERED", evidenceIds: [...evidenceIds] }; this.questions.set(id, resolved); if (item.state !== "ANSWERED") this.openQuestionCount -= 1; this.#changed(); return resolved; }
  openHypothesis(id, input = {}) { const previous = this.hypotheses.get(id); this.hypotheses.set(id, { id, state: "OPEN", ...input }); if (!previous || previous.state === "RESOLVED") this.openHypothesisCount += 1; this.#changed(); }
  resolveHypothesis(id, outcome, evidenceIds = []) { const item = this.hypotheses.get(id); if (!item) return null; const resolved = { ...item, state: "RESOLVED", outcome, evidenceIds: [...evidenceIds] }; this.hypotheses.set(id, resolved); if (item.state !== "RESOLVED") this.openHypothesisCount -= 1; this.#changed(); return resolved; }
  snapshot() { if (this.snapshotCache?.revision === this.revision) return this.snapshotCache.value; const value = Object.freeze({ propositions: this.items.size, openQuestions: this.openQuestionCount, openHypotheses: this.openHypothesisCount }); this.snapshotCache = { revision: this.revision, value }; return value; }
  #changed() { this.revision += 1; this.snapshotCache = null; }
}

function normalizeMeaning(text) { return String(text || "").toLowerCase().replace(/\b(the|a|an|this|that|is|are|was|were|very|quite)\b/g, " ").replace(/[^a-z0-9]+/g, " ").trim().split(/\s+/).sort().join(" "); }
function meaningTokens(text) { return [...new Set(normalizeMeaning(text).split(" ").filter(Boolean))]; }
function semanticSimilarity(input, item) { const predicates = input.predicate === item.predicate ? 1 : tokenJaccard(meaningTokens(input.predicate), meaningTokens(item.predicate)), subjects = tokenJaccard((input.subjectIds || []).map(String), (item.subjectIds || []).map(String)), argumentsScore = tokenJaccard(meaningTokens(JSON.stringify(input.arguments || input.normalizedArguments || {})), meaningTokens(JSON.stringify(item.arguments || {}))), text = tokenJaccard(meaningTokens(input.text), item.tokens || meaningTokens(item.text)); return .45 * predicates + .3 * subjects + .15 * argumentsScore + .1 * text; }
function tokenJaccard(left, right) { const a = new Set(left), b = new Set(right), union = new Set([...a, ...b]); if (!union.size) return 1; let intersection = 0; for (const value of a) if (b.has(value)) intersection += 1; return intersection / union.size; }
