import { authorOntologyIntegrity } from "./ontology.js";
import { createDefaultPredictionModelRegistry } from "./models.js";
import { ACSSDecisionPlanner, ACSSStoryPlanner, compilePresentationContract } from "./planner.js";
import { AuthorLearningProfile, BrowserAuthorProfileStore, attributeOutcome } from "./learning.js";
import { ForecastLedger } from "./forecast-ledger.js";
import { DocumentaryAudienceMemory } from "./audience-memory.js";
import { AudienceLearningSystem } from "../documentary-author/audience/index.js";
import { ObservationTransactionRuntime } from "../documentary-author/runtime/observation-transaction.js";
import { compileDocumentaryPolicy } from "../documentary-author/planning/policy-compiler.js";
import { validatePresentationContract } from "../documentary-author/presentation/contract-validator.js";
import { validateCertificate } from "../documentary-author/learning/validation-certificate.js";
import { PerformanceBudgetTracker, monotonicNow } from "../documentary-author/runtime/performance-budget.js";

class IdFactory { constructor(prefix = "acss") { this.prefix = prefix; this.sequence = 0; } next(kind) { return `${this.prefix}-${kind}-${String(++this.sequence).padStart(8, "0")}`; } }

export class ACSSPredictiveAuthor {
  constructor({ mode = "V3_SHADOW", profileStore = null, audience = null, lifecycle = null, onRecord = null } = {}) {
    this.mode = mode; this.ids = new IdFactory(); this.recordSink = onRecord; this.ontologyHealth = authorOntologyIntegrity(); if (!this.ontologyHealth.valid) throw new TypeError(this.ontologyHealth.errors.join("; "));
    this.registry = createDefaultPredictionModelRegistry(); this.registryHealth = this.registry.integrity(); if (!this.registryHealth.valid) throw new TypeError(this.registryHealth.errors.join("; ")); this.profileStore = profileStore || new BrowserAuthorProfileStore(); this.learning = this.profileStore.load(); if (lifecycle) this.learning.lifecycle = lifecycle; this.learning.refreshCapabilities();
    this.performance = new PerformanceBudgetTracker(); this.observer = new ObservationTransactionRuntime({ performance: this.performance, onRecord: (type, payload, tick) => this.writeTrace(type, payload, tick) }); this.stories = new ACSSStoryPlanner(); this.audienceMemory = new DocumentaryAudienceMemory(); this.audience = audience || new AudienceLearningSystem(); this.planner = new ACSSDecisionPlanner({ registry: this.registry, learning: this.learning, stories: this.stories, idFactory: this.ids }); this.currentPlan = null; this.currentContract = null; this.currentObservation = null; this.plansByDecision = new Map(); this.traceQueue = []; this.traceHead = 0; this.traceCache = null; this.maximumTrace = 4000; Object.defineProperty(this, "trace", { enumerable: true, get: () => { if (!this.traceCache) this.traceCache = this.traceQueue.slice(this.traceHead); return this.traceCache; } }); this.lastSaveRevision = this.learning.revision; this.session = null; this.diagnosticRevision = 0; this.healthCache = null; this.diagnosticCache = null; this.forecasts = new ForecastLedger({ learning: this.learning, onRecord: entry => this.writeTrace(entry.type, entry.payload, entry.payload?.issuedAtTick || entry.payload?.resolvedAtTick || 0) });
  }
  setRecordSink(sink) { this.recordSink = typeof sink === "function" ? sink : null; return this; }
  async hydrateProfile() { if (typeof this.profileStore.loadAsync !== "function") return this.learning; const profile = await this.profileStore.loadAsync(); if (profile && profile.revision >= this.learning.revision) this.#replaceLearning(profile); return this.learning; }
  importLearningProfile(snapshot) { const profile = snapshot instanceof AuthorLearningProfile ? snapshot : new AuthorLearningProfile(snapshot || {}); if (!profile.verify()) throw new TypeError("Imported ACSS profile failed checksum verification"); if (profile.registryVersion !== this.learning.registryVersion) throw new TypeError("Imported ACSS profile registry version does not match"); if (profile.revision >= this.learning.revision) this.#replaceLearning(profile); return this.learning; }
  #replaceLearning(profile) { this.learning = profile; this.learning.refreshCapabilities(); this.planner.learning = profile; this.forecasts.learning = profile; this.lastSaveRevision = profile.revision; this.diagnosticRevision += 1; this.healthCache = null; this.diagnosticCache = null; }
  setExecutionMode(mode) { if (!new Set(["V3_SHADOW", "V3_ACTIVE"]).has(mode)) throw new TypeError(`Unknown ACSS execution mode: ${mode}`); this.mode = mode; return mode; }
  policy(input = {}) { return compileDocumentaryPolicy(input); }
  canControl() { return this.mode === "V3_ACTIVE" && (this.learning.allows("CONTROL_BOUNDED", { component: "production-policy" }) || this.learning.allows("CONTROL_VALIDATED", { component: "production-policy" })); }
  beginSession(input = {}) { this.forecasts.censorAll("new-session", input.tick || 0); this.observer.reset(); this.stories = new ACSSStoryPlanner(); this.planner.stories = this.stories; this.audienceMemory = new DocumentaryAudienceMemory(); this.audience.beginSession?.(); this.session = { sessionId: input.sessionId || null, simulationSeed: input.simulationSeed ?? null, startedAt: Date.now(), profileRevision: this.learning.revision, profileChecksum: this.learning.snapshot().profileChecksum, registryVersion: this.learning.registryVersion, audienceProfileRevision: this.audience.profile.revision }; this.currentPlan = null; this.currentContract = null; this.currentObservation = null; this.plansByDecision.clear(); this.writeTrace("author_session_begun", this.session, input.tick || 0); return this.session; }
  endSession({ reason = "session-ended", tick = 0 } = {}) { const resolutions = this.forecasts.censorAll(reason, tick), closedObligations = this.stories.close(tick, reason); this.persist(); this.writeTrace("author_session_ended", { reason, censoredForecasts: resolutions.length, closedReturnObligations: closedObligations.length, profileRevision: this.learning.revision }, tick); const session = this.session; this.session = null; return session; }
  async flushPersistence() { await this.profileStore.flush?.(); return true; }
  observe(simulation, { scenes = [], tick = simulation?.tick || 0 } = {}) { this.currentObservation = this.observer.observe(simulation, { scenes }); this.forecasts.observe({ observation: this.currentObservation, tick }); return this.currentObservation; }
  selectPresentation({ scenes = [], simulation = {}, policy = {}, tick = simulation.tick || 0, speechActive = false } = {}) {
    const resolvedPolicy = this.policy(policy), observation = this.observe(simulation, { scenes, tick }), planningStarted = monotonicNow(), observedScenes = scenes.map(scene => { const subjectIds = scene.semanticRoleIds || scene.ids || [], semanticFingerprint = this.audienceMemory.fingerprint({ predicate: scene.eventType || scene.actionKey || scene.kind, subjectIds, arguments: { kind: scene.kind, eventType: scene.eventType || null, actionKey: scene.actionKey || null } }); return { ...scene, semanticFingerprint, semanticNovelty: this.audienceMemory.novelty({ fingerprint: semanticFingerprint, predicate: scene.eventType || scene.actionKey || scene.kind, subjectIds, arguments: { kind: scene.kind, eventType: scene.eventType || null, actionKey: scene.actionKey || null } }, tick) }; });
    const situationByScene = observation.situationDelta.byScene, plan = this.planner.choose(observedScenes, observation.snapshot, resolvedPolicy, tick, { speechActive, observation, situationByScene, audience: this.audience }); if (!plan) { this.performance.record("planningTransaction", monotonicNow() - planningStarted); this.writeTrace("author_silence_selected", { reason: "no-policy-valid-evidence-supported-plan", rejections: this.planner.rejections.slice(-50) }, tick); this.currentPlan = null; this.currentContract = null; return null; }
    plan.context.profileRevision = this.learning.revision; const opened = this.forecasts.open(plan.ensemble, plan.context, tick), rootForecast = opened.find(item => item.modelId === plan.ensemble.rootModelId) || null; plan.ensemble = Object.freeze({ ...plan.ensemble, forecasts: Object.freeze(opened), rootForecast }); const draft = compilePresentationContract(plan, { tick, policy: resolvedPolicy }), validation = validatePresentationContract(draft, { propositions: observation.propositions, evidence: observation.evidence, policy: resolvedPolicy, tick }), contract = Object.freeze({ ...draft, valid: validation.valid, validationErrors: validation.errors, validationWarnings: validation.warnings });
    if (!validation.valid) { this.performance.record("planningTransaction", monotonicNow() - planningStarted); this.writeTrace("author_contract_rejected", { sceneId: plan.scene.id, contractId: draft.contractId, errors: validation.errors }, tick); return null; }
    this.currentPlan = plan; this.currentContract = contract; this.plansByDecision.set(contract.decision.decisionId, plan); while (this.plansByDecision.size > 200) this.plansByDecision.delete(this.plansByDecision.keys().next().value); this.performance.record("planningTransaction", monotonicNow() - planningStarted); this.writeTrace("author_model_graph", { planId: plan.planId, rootModelId: plan.ensemble.rootModelId, dependencyCompleteness: plan.ensemble.dependencyCompleteness, forecasts: plan.ensemble.forecasts.map(item => ({ forecastId: item.forecastId, modelId: item.modelId, dependencyForecastIds: item.dependencyForecastIds, confidence: item.confidence })) }, tick); this.writeTrace("author_plan_proposed", { plan: tracePlan(plan), contract, activeControl: this.canControl() }, tick); return { scene: plan.scene, plan, contract, observationRevision: observation.revision, activate: this.canControl() };
  }
  observeScene(scene, context = {}, { tick = 0, simulation = null } = {}) { if (!simulation) return []; const observation = this.observe(simulation, { scenes: [scene], tick }); const situation = observation.situations.forScene(scene.id); return (situation?.beliefIds || []).map(id => ({ belief: observation.beliefs.get(id), situation })).filter(item => item.belief); }
  cycle({ scene = {}, tick = 0, simulation = {}, policy = {}, speechActive = false } = {}) { const selected = this.selectPresentation({ scenes: [scene], simulation, policy, tick, speechActive }), contract = selected?.contract || null, realised = contract ? { text: "", propositionIds: [], evidenceIds: [], wordingFamilies: [], fallback: true } : null; return { mode: this.mode, decision: contract?.decision || null, narration: contract?.narration || null, camera: contract?.camera || null, validation: { valid: Boolean(contract?.valid), errors: contract?.validationErrors || ["no-presentation-contract"] }, realised, contract, forecasts: contract?.forecasts || [], activate: Boolean(selected?.activate) }; }
  completeCurrentBeat({ outcomeChanged = false, shown = true, narratedClaimIds = [], tick = this.currentObservation?.snapshot?.simulationTick || 0, skipReason = null } = {}) { if (!this.currentPlan) return null; const result = this.stories.completeBeat(this.currentPlan.thread, this.currentContract?.beat, { outcomeChanged, shown, narratedClaimIds, tick, skipReason }); this.writeTrace("author_story_beat_completed", { threadId: result?.threadId, beat: this.currentContract?.beat, shown, narratedClaimIds, skipReason }, tick); return result; }
  markDecisionExecuted({ contract = this.currentContract, cameraFamily = null, shotSize = null, tick = 0 } = {}) { if (!contract || !this.canControl()) return null; return this.writeTrace("author_decision_executed", { contractId: contract.contractId, decision: contract.decision, cameraFamily, shotSize, subjectIds: contract.subjectIds, claimIds: contract.allowedClaimIds }, tick); }
  recordShadowComparison(decision, actual = {}) { const plan = this.plansByDecision.get(decision?.decisionId), contract = this.currentContract?.decision?.decisionId === decision?.decisionId ? this.currentContract : null; if (!plan || this.canControl()) return null; const proposed = { rootModelId: plan.ensemble.rootModelId, action: plan.action, cameraFamilies: contract?.camera?.preferredFamilies || [], shotSizes: contract?.camera?.preferredShotSizes || [], subjectIds: plan.participants, threadId: plan.thread.threadId, sceneId: plan.scene.id }, comparison = { decisionId: decision.decisionId, proposed, executedBaseline: { cameraFamily: actual.cameraFamily || null, shotSize: actual.shotSize || null, subjectIds: [...(actual.subjectIds || [])], visibilityMean: actual.visibilityMean ?? null, containmentMean: actual.containmentMean ?? null, discontinuityCount: actual.discontinuityCount ?? null }, productionRewardApplied: false }; return this.writeTrace("author_shadow_comparison", comparison, actual.tick || 0); }
  markPresented(input = {}, { tick = 0 } = {}) { const contract = input.contract || this.currentContract, text = input.text || "", claimIds = input.claimIds || input.propositionIds || contract?.allowedClaimIds || []; for (const claimId of claimIds) { const claim = this.currentObservation?.propositions?.get?.(claimId); if (claim) this.audienceMemory.mark({ ...claim, fingerprint: claim.semanticFingerprint, arguments: claim.normalizedArguments, text, threadId: contract?.threadId, claimId }, tick); } if (!claimIds.length && text) this.audienceMemory.mark({ fingerprint: input.fingerprint || contract?.semanticFingerprint, predicate: input.predicate || contract?.narration?.function, subjectIds: input.subjectIds || contract?.subjectIds, text, threadId: contract?.threadId }, tick); this.writeTrace("author_presentation_completed", { contractId: contract?.contractId, claimIds, subjectIds: contract?.subjectIds || [], textLength: text.length }, tick); return { contract, claimIds }; }
  registerAudiencePresentation(input = {}) { return this.audience.registerPresentation(input); }
  audienceFeedback(input = {}) { const result = this.audience.feedback(input); this.writeTrace("audience_feedback", result, input.tick || 0); return result; }
  retractAudienceFeedback(feedbackId) { const result = this.audience.retract(feedbackId); this.writeTrace("audience_feedback_retracted", result, 0); return result; }
  audienceImplicit(input = {}) { const result = this.audience.implicit(input); this.writeTrace("audience_implicit_signal", result, input.tick || 0); return result; }
  audienceFault(input = {}, metrics = {}) { const result = this.audience.reportFault(input, metrics), correction = result?.valid ? this.learning.recordProductionFault(result.report) : { updated: false, reason: "invalid-report" }; if (correction.updated) this.persist(); const combined = { ...result, productionCorrection: correction }; this.writeTrace("audience_fault_report", combined, input.tick || 0); return combined; }
  audienceWritten(text) { return this.audience.written(text); }
  audienceConfirmWritten(parsed, tags, presentationId, options = {}) { const result = this.audience.confirmWritten(parsed, tags, presentationId, options); this.writeTrace("audience_written_feedback", result, options.tick || 0); return result; }
  audiencePrompt(context = {}) { return this.audience.prompt(context); }
  audienceAnswerPrompt(question, answer, options = {}) { const result = this.audience.answerPrompt(question, answer, options); this.writeTrace("audience_prompt_answer", result, options.tick || 0); return result; }
  audiencePriming(answers = {}, options = {}) { const result = this.audience.applyPriming(answers, options); this.writeTrace("audience_priming", result, options.tick || 0); return result; }
  audienceComparison(input = {}) { const result = this.audience.compare(input); this.writeTrace("audience_pairwise_preference", result, input.tick || 0); return result; }
  skipAudiencePriming() { return this.audience.skipPriming(); } clearAudienceSession() { return this.audience.clearSessionPreferences(); } setAudienceConsent(changes = {}) { return this.audience.setConsent(changes); } clearAudienceCameraPreferences() { return this.audience.clearCameraPreferences(); } exportAudienceProfile() { return this.audience.exportProfile(); } audienceProfiles() { return this.audience.profiles(); } createAudienceProfile(displayName, options = {}) { return this.audience.createProfile(displayName, options); } selectAudienceProfile(profileId) { return this.audience.selectProfile(profileId); } rollbackAudienceLearning() { return this.audience.rollback(); } resetAudienceLearning(options = {}) { return this.audience.reset(options); }
  evaluate(decision, actual = {}) { const plan = this.plansByDecision.get(decision?.decisionId) || this.currentPlan, attribution = attributeOutcome({ decision, actual, interruption: actual.interruption }), executed = actual.executed !== false, productionResolutions = executed ? this.forecasts.resolveProduction(plan?.ensemble?.forecasts || [], actual, actual.tick || 0) : [], result = this.learning.resolveProduction({ decision, context: plan?.context || {}, actual, attributable: attribution.attributable, executed }); this.writeTrace("author_presentation_outcome", { decisionId: decision?.decisionId, actual, productionResolutions }, actual.tick || 0); this.writeTrace("author_learning_attribution", { decisionId: decision?.decisionId, attribution, learning: result, executed }, actual.tick || 0); if (this.learning.revision - this.lastSaveRevision >= 5) this.persist(); return { outcome: { decisionId: decision?.decisionId, actual, success: Number(result.reward || 0) >= 0 }, errors: attribution.errors, learning: result, forecastResolutions: productionResolutions }; }
  operatorFeedback(kind, { subjectIds = [], decision = this.currentContract?.decision } = {}) { const values = { KEEP: .3, HIGHLIGHT: .2, COMPRESS: -.12, REMOVE: -.35, NEXT_SHOT: -.05 }, value = values[kind] || 0; for (const id of subjectIds) if (kind === "FAVOURITE") this.learning.preferences.markCharacter(id, 1); else if (value) this.learning.preferences.markCharacter(id, value * .25); if (decision && value) this.learning.preferences.markAction(decision.action, this.currentPlan?.context || {}, value); this.learning.revision += 1; this.learning.refreshCapabilities(); this.persist(); }
  persist() { const started = monotonicNow(), snapshot = this.learning.snapshot(), previousRevision = this.lastSaveRevision, saved = this.profileStore.save(this.learning); if (saved) this.lastSaveRevision = this.learning.revision; if (this.audience.profile.mode !== "GUEST") this.audience.store.save(this.audience.profile); if (saved) { const tick = this.currentObservation?.snapshot?.simulationTick || 0, payload = { previousRevision, revision: this.learning.revision, checksum: snapshot.profileChecksum, profileId: this.profileStore.profileId || "default", snapshot }; this.writeTrace("author_profile_delta", { previousRevision, revision: this.learning.revision, calibrationRecords: this.learning.calibration.records.size, policyRecords: this.learning.policy.records.size, productionRecords: this.learning.production.records.size }, tick); this.writeTrace("author_profile_commit", payload, tick); } this.performance.record("profileCheckpoint", monotonicNow() - started); return saved; }
  rollbackLearning() { if (this.profileStore.indexedStore?.available?.()) return this.profileStore.rollbackAsync().then(profile => { if (!profile) return false; this.#replaceLearning(profile); return true; }); const profile = this.profileStore.rollback(); if (!profile) return false; this.#replaceLearning(profile); return true; }
  resetLearning() { const previousRevision = this.learning.revision; this.profileStore.backup?.(); this.#replaceLearning(new AuthorLearningProfile({ lifecycle: "OBSERVING", revision: previousRevision + 1 })); this.lastSaveRevision = previousRevision; return this.persist(); }
  setLearningLifecycle(lifecycle, { family = null, component = null } = {}) { const allowed = new Set(["OBSERVING", "CALIBRATING", "SHADOW_POLICY", "BOUNDED_ACTIVE", "VALIDATED_ACTIVE"]); if (!allowed.has(lifecycle)) throw new TypeError(`Unknown ACSS learning lifecycle: ${lifecycle}`); const nextRevision = this.learning.revision + 1; if (lifecycle === "VALIDATED_ACTIVE") { const validation = validateCertificate(this.learning.validationCertificate, { profileRevision: nextRevision, registryVersion: this.learning.registryVersion, requiredCapabilities: ["CONTROL_VALIDATED"] }); if (!this.learning.validated || !validation.valid) throw new TypeError(`Validated active requires a matching validation certificate: ${validation.errors.join(", ")}`); } if (family) this.learning.familyLifecycles[family] = lifecycle; else if (component) this.learning.componentLifecycles[component] = lifecycle; else this.learning.lifecycle = lifecycle; this.learning.revision = nextRevision; this.learning.refreshCapabilities(); this.persist(); return lifecycle; }
  writeTrace(type, payload, tick = 0) { const record = Object.freeze({ traceId: this.ids.next("trace"), type, tick, payload }); this.traceQueue.push(record); const overflow = this.traceQueue.length - this.traceHead - this.maximumTrace; if (overflow > 0) this.traceHead += overflow; if (this.traceHead > 1024 && this.traceHead * 2 > this.traceQueue.length) { this.traceQueue = this.traceQueue.slice(this.traceHead); this.traceHead = 0; } this.traceCache = null; this.diagnosticRevision += 1; this.healthCache = null; this.diagnosticCache = null; this.recordSink?.(record); return record; }
  stateRevisionKey() { return `${this.diagnosticRevision}|${this.mode}|${this.learning.revision}|${this.learning.lifecycle}|${this.observer.revision}|${this.stories.revision}|${this.stories.obligations.revision}|${this.forecasts.revision}|${this.performance.revision}|${this.audience.profile.revision}|${this.audienceMemory.revision}|${this.currentPlan?.planId || "none"}|${this.currentContract?.contractId || "none"}`; }
  health() { const key = this.stateRevisionKey(); if (this.healthCache?.key === key) return this.healthCache.value; const observation = this.observer.health(), value = Object.freeze({ mode: this.mode, lifecycle: this.learning.lifecycle, controlActive: this.canControl(), ontology: this.ontologyHealth, registry: this.registryHealth, beliefs: observation.beliefRecords, situations: observation.activeSituations, activeSituations: observation.activeSituations, evidenceRecords: observation.evidenceRecords, propositionRecords: this.currentObservation?.propositions?.records?.length || 0, observationDurationMs: observation.lastDurationMs, adapterFailures: observation.adapterFailures, threads: this.stories.threads.size, returnObligations: this.stories.obligations.snapshot().active.length, currentThreadId: this.stories.currentThreadId, models: this.registry.models.size, selectedModels: this.currentPlan?.ensemble?.forecasts?.length || 0, candidateExclusions: this.planner.rejections.length, predictionFallbacks: this.planner.fallbacks.length, learningRevision: this.learning.revision, calibrationRecords: this.learning.calibration.records.size, policyRecords: this.learning.policy.records.size, productionPolicyRecords: this.learning.production.records.size, traceRecords: this.traceQueue.length - this.traceHead, currentConcern: this.currentPlan?.concerns?.[0]?.id || null, currentMethod: this.currentPlan?.methodId || null, currentBeat: this.currentContract?.beat || null, forecasts: this.forecasts.health(), performance: this.performance.snapshot(), audience: this.audience.health(), audienceMemory: this.audienceMemory.snapshot() }); this.healthCache = { key, value }; return value; }
  diagnostic() { const key = this.stateRevisionKey(); if (this.diagnosticCache?.key === key) return this.diagnosticCache.value; const profile = this.learning.snapshot(), certificate = validateCertificate(this.learning.validationCertificate, { profileRevision: this.learning.revision, registryVersion: this.learning.registryVersion }), value = Object.freeze({ health: this.health(), observation: this.currentObservation ? { revision: this.currentObservation.revision, snapshotId: this.currentObservation.snapshot.snapshotId, evidenceRevision: this.currentObservation.evidence.revision, beliefRevision: this.currentObservation.beliefs.revision, propositionRevision: this.currentObservation.propositions.revision, situationRevision: this.currentObservation.situations.revision, adapterDiagnostics: this.currentObservation.adapterDiagnostics } : null, profile: { revision: profile.revision, checksum: profile.profileChecksum, registryVersion: profile.registryVersion, lifecycles: this.learning.capabilities.snapshot(), certificate: { valid: certificate.valid, errors: certificate.errors, certificateId: certificate.certificateId, approvedCapabilities: this.learning.validationCertificate?.approvedCapabilities || [], trainingSeedSetHash: this.learning.validationCertificate?.trainingSeedSetHash || null, heldOutSeedSetHash: this.learning.validationCertificate?.heldOutSeedSetHash || null } }, currentPlan: this.currentPlan ? tracePlan(this.currentPlan) : null, contract: this.currentContract, alternatives: this.planner.lastPlans.map(tracePlan), candidateExclusions: this.planner.rejections.slice(-100), predictionFallbacks: this.planner.fallbacks.slice(-100), modelGraph: this.currentPlan ? { rootModelId: this.currentPlan.ensemble.rootModelId, dependencyCompleteness: this.currentPlan.ensemble.dependencyCompleteness, totalCost: this.currentPlan.ensemble.totalCost, budget: this.currentPlan.ensemble.budget, correlationInfluence: this.currentPlan.ensemble.correlationInfluence, abstentions: this.currentPlan.ensemble.abstentions, models: this.currentPlan.ensemble.forecasts.map(item => ({ modelId: item.modelId, family: item.family, confidence: item.confidence, rawOutcomes: item.rawOutcomes || item.outcomes, calibratedOutcomes: item.outcomes, dependencies: item.dependencyForecastIds, observer: item.outcomeObserverId, horizon: { earliestTick: item.earliestTick, latestTick: item.latestTick }, conflicts: item.conflicts })) } : null, situations: this.currentObservation?.situations?.situations || [], returnObligations: this.stories.obligations.snapshot(), recentLearning: this.learning.learningEvents.slice(-20), recentAudienceFeedback: this.audience.feedbackEvents.slice(-20), recentTrace: this.traceQueue.slice(Math.max(this.traceHead, this.traceQueue.length - 50)) }); this.diagnosticCache = { key, value }; return value; }
}

function tracePlan(plan) { return { planId: plan.planId, sceneId: plan.scene.id, sceneKind: plan.scene.kind, eventType: plan.scene.eventType || null, situationId: plan.situation?.situationId, threadId: plan.thread.threadId, action: plan.action, methodId: plan.methodId, beat: plan.beat, subjectIds: plan.participants, score: plan.score, utility: plan.utility, silenceSelected: Boolean(plan.silenceSelected), concern: plan.concerns[0], rootModelId: plan.ensemble.rootModelId, predictionFallback: plan.predictionFallback || null, confidence: plan.ensemble.confidence, frameable: plan.frameable, audience: plan.audience }; }

export { AuthorLearningProfile };
