import { PredictionModelRegistry } from "./model-registry.js";

const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
const outcomes = rows => { const safe = rows.map(([id, probability]) => ({ id, probability: Math.max(0, Number(probability) || 0) })), total = safe.reduce((sum, item) => sum + item.probability, 0) || 1; return safe.map(item => Object.freeze({ ...item, probability: item.probability / total })); };
const subject = context => context.subjects?.[0] || null;
const action = context => String(subject(context)?.action?.key || subject(context)?.actionState?.key || subject(context)?.actionKey || context.action || "unknown").toLowerCase();
const methodPhase = context => subject(context)?.plan?.phase || subject(context)?.needDependencyPlan?.phase || subject(context)?.activePlan?.phase || subject(context)?.planPhase || context.phase || null;
const situationIs = (context, ...types) => types.includes(context.situation?.type);
const frameworkFor = familyName => ({ CAMERA: "FORWARD_ACTION", PHYSIOLOGY: "DYNAMICAL", PREDATION: "HAZARD", AUDIENCE: "CONTEXTUAL_PREFERENCE", PRODUCTION: "METAPREDICTION", STATE: "PERSISTENCE", SPATIAL: "TREND_EXTRAPOLATION" })[familyName] || "DEPENDENCY_EVENT_STATE";
const authorityFor = familyName => ({ CAMERA: "CONSTRAINING", PRODUCTION: "SELECTING", AUDIENCE: "SCORING", STORY: "SCORING", PHYSIOLOGY: "CONSTRAINING" })[familyName] || "ADVISORY";
const family = (modelId, familyName, predicts, extra = {}) => ({ modelId, family: familyName, predicts, framework: frameworkFor(familyName), outputShape: "CATEGORICAL_DISTRIBUTION", authority: authorityFor(familyName), applicable: () => true, evidenceConfidence: context => context.evidenceConfidence ?? .75, relevance: () => .6, outcomeObserverId: modelId, correlationGroup: `${familyName.toLowerCase()}:${predicts.toLowerCase()}`, costUnits: 1, horizon: { minimumTicks: 1, maximumTicks: 30 }, predict: () => ({ outcomes: outcomes([["STABLE", 1]]), confidence: .6 }), ...extra });

export function createDefaultPredictionModelRegistry() {
  const registry = new PredictionModelRegistry();

  registry.register(family("state.identity-continuity.v1", "STATE", "SUBJECT_IDENTITY", { applicable: context => Boolean(context.scene), predict: context => ({ outcomes: outcomes(context.scene?.ids?.length ? [["IDENTIFIED", .96], ["IDENTITY_LOST", .04]] : [["WORLD_SUBJECT", 1]]), confidence: .98, values: { subjectIds: [...(context.scene?.ids || [])], world: !context.scene?.ids?.length } }) }));
  registry.register(family("state.evidence-freshness.v1", "STATE", "EVIDENCE_FRESHNESS", { predict: context => ({ outcomes: outcomes(context.evidenceFresh === false ? [["STALE", .9], ["FRESH", .1]] : [["FRESH", .92], ["STALE", .08]]), confidence: context.evidenceFresh === false ? .8 : .92 }) }));
  registry.register(family("resource.target-validity.v1", "RESOURCE", "TARGET_VALIDITY", { applicable: context => situationIs(context, "RESOURCE_ACQUISITION", "PREDATION_SEQUENCE", "REPRODUCTION_STAGE") || Boolean(subject(context)?.plan?.targetId), evidenceConfidence: context => context.targetValid === false ? .3 : .76, predict: context => ({ outcomes: outcomes([[context.targetValid === false ? "INVALID" : "REMAINS_VALID", .78], ["CHANGES", .22]]), confidence: context.targetValid === false ? .9 : .68 }) }));
  registry.register(family("physiology.locomotion-capacity.v1", "PHYSIOLOGY", "LOCOMOTION_CAPACITY", { applicable: context => Boolean(subject(context)), evidenceConfidence: context => Number.isFinite(Number(subject(context)?.physiology?.fatigue ?? subject(context)?.fatigue ?? subject(context)?.energy)) ? .94 : .55, predict: context => { const entity = subject(context) || {}, physiology = entity.physiology || entity, endurance = Number.isFinite(Number(physiology.endurance)) ? Number(physiology.endurance) : 100 - Number(physiology.fatigue || 0), stress = Number(physiology.adrenalineStress || 0), viable = endurance > 18 || Number(physiology.sprintCapacity || entity.sprintEnergy || 0) > 12 || Number(physiology.emergencyReserve || 0) > .1 && stress < 88; return { outcomes: outcomes([[viable ? "MOBILE" : "RECOVERY_REQUIRED", viable ? .82 : .78], [viable ? "RECOVERY_REQUIRED" : "MOBILE", viable ? .18 : .22]]), confidence: .78, values: { endurance, stress } }; } }));
  registry.register(family("space.route-reachability.v1", "SPATIAL", "ROUTE_REACHABILITY", { applicable: context => Boolean(subject(context)), predict: context => ({ outcomes: outcomes([[context.routeBlocked ? "BLOCKED" : "REACHABLE", context.routeBlocked ? .8 : .76], [context.routeBlocked ? "REACHABLE" : "BLOCKED", context.routeBlocked ? .2 : .24]]), confidence: .7, values: { blocked: Boolean(context.routeBlocked) } }) }));
  registry.register(family("camera.subject-trajectory.v1", "CAMERA", "SUBJECT_ACTION_ZONE", { dependencies: [{ modelId: "state.identity-continuity.v1", relation: "REQUIRES", output: "identity", minimumConfidence: .7 }], applicable: context => Boolean(context.subjects?.length), predict: context => { const entities = context.subjects || [], x = entities.length ? entities.reduce((sum, item) => sum + Number(item.position?.x ?? item.x ?? 0), 0) / entities.length : Number(context.scene?.focus?.x || 0), z = entities.length ? entities.reduce((sum, item) => sum + Number(item.position?.z ?? item.z ?? 0), 0) / entities.length : Number(context.scene?.focus?.z || 0), vx = entities.length ? entities.reduce((sum, item) => sum + Number(item.velocity?.x ?? item.locomotion?.vx ?? item.velocityX ?? 0), 0) / entities.length : 0, vz = entities.length ? entities.reduce((sum, item) => sum + Number(item.velocity?.z ?? item.locomotion?.vz ?? item.velocityZ ?? 0), 0) / entities.length : 0, identityValid = Boolean(context.dependencyOutputs?.identity); return { outcomes: outcomes([["ZONE_VALID", identityValid ? .88 : .55], ["ZONE_CHANGES", identityValid ? .12 : .45]]), confidence: identityValid ? .82 : .56, values: { now: { x, z }, predicted: { x: x + vx * 8, z: z + vz * 8 }, radius: Math.max(2, Math.hypot(vx, vz) * 12 + 2), vx, vz, path: Array.from({ length: 17 }, (_, index) => ({ t: index * .25, x: x + vx * index * .25, z: z + vz * index * .25, radius: Math.max(1.5, Math.hypot(vx, vz) * index * .18 + 1.5) })) } }; } }));
  registry.register(family("camera.frameability.v1", "CAMERA", "SUBJECT_FRAMEABILITY", { dependencies: [{ modelId: "camera.subject-trajectory.v1", relation: "REQUIRES", output: "trajectory", minimumConfidence: .6 }, { modelId: "space.route-reachability.v1", relation: "SUPPORTS", output: "route" }], applicable: context => Boolean(context.subjects?.length), predict: context => { const subjects = context.subjects || [], focus = context.scene?.focus || { x: 0, z: 0 }, extent = subjects.reduce((maximum, item) => Math.max(maximum, Math.hypot(Number(item.position?.x ?? item.x ?? 0) - focus.x, Number(item.position?.z ?? item.z ?? 0) - focus.z)), 0), frameable = extent < 14; return { outcomes: outcomes([[frameable ? "FRAMEABLE" : "WIDEN_REQUIRED", frameable ? .86 : .8], [frameable ? "WIDEN_REQUIRED" : "FRAMEABLE", frameable ? .14 : .2]]), confidence: .8, values: { extent, requiredShotSize: extent > 14 ? "WIDE" : extent > 6 ? "MEDIUM_WIDE" : "MEDIUM" } }; } }));
  registry.register(family("camera.occlusion-risk.v1", "CAMERA", "OCCLUSION_RISK", { dependencies: [{ modelId: "camera.subject-trajectory.v1", relation: "REQUIRES" }], predict: context => { const risk = clamp01(context.cameraRisk ?? 0); return { outcomes: outcomes([[risk > .55 ? "OCCLUSION_LIKELY" : "CLEAR", Math.max(.55, risk > .55 ? risk : 1 - risk)], [risk > .55 ? "CLEAR" : "OCCLUSION_LIKELY", Math.min(.45, risk > .55 ? 1 - risk : risk)]]), confidence: .72, values: { risk } }; } }));
  registry.register(family("behaviour.plan-phase.v1", "BEHAVIOUR", "NEXT_METHOD_PHASE", { dependencies: [{ modelId: "physiology.locomotion-capacity.v1", relation: "REQUIRES", output: "locomotion", minimumConfidence: .6 }, { modelId: "space.route-reachability.v1", relation: "REQUIRES", output: "route", minimumConfidence: .55 }, { modelId: "resource.target-validity.v1", relation: "CONDITIONS", output: "target", minimumConfidence: .5 }], applicable: context => Boolean(subject(context) && methodPhase(context)), relevance: context => methodPhase(context) ? .95 : .2, predict: context => { const phase = methodPhase(context), entity = subject(context) || {}, physiology = entity.physiology || entity, locomotion = context.dependencyOutputs?.locomotion || {}, route = context.dependencyOutputs?.route || {}, tired = Number(physiology.fatigue || 0) > 76 || Number(locomotion.endurance || 100) < 18, threatened = Number(physiology.fear || 0) > 75, blocked = route.blocked === true; return { outcomes: outcomes(threatened ? [["INTERRUPTED", .62], ["HOLD_PHASE", .24], ["ADVANCE_PHASE", .14]] : blocked ? [["HOLD_PHASE", .55], ["ABANDON_METHOD", .3], ["ADVANCE_PHASE", .15]] : tired ? [["HOLD_PHASE", .55], ["ADVANCE_PHASE", .25], ["ABANDON_METHOD", .2]] : [["ADVANCE_PHASE", .62], ["HOLD_PHASE", .28], ["INTERRUPTED", .1]]), confidence: .73, values: { phase, locomotion, route } }; } }));
  registry.register(family("physiology.recovery-window.v1", "PHYSIOLOGY", "RECOVERY_WINDOW", { dependencies: [{ modelId: "physiology.locomotion-capacity.v1", relation: "REQUIRES", output: "locomotion", minimumConfidence: .6 }], applicable: context => situationIs(context, "RECOVERY"), predict: context => { const entity = subject(context) || {}, depth = entity.physiology?.recoveryDepth || entity.recoveryState?.depth || entity.recoveryDepth || "brief", ticks = depth === "deep" ? 18 : depth === "travel" ? 10 : 4; return { outcomes: outcomes([["RECOVERY_CONTINUES", .58], ["RESUMES_ACTIVITY", .42]]), confidence: .72, values: { expectedTicks: ticks, depth } }; } }));
  registry.register(family("danger.response.v1", "PREDATION", "DANGER_RESPONSE", { dependencies: [{ modelId: "physiology.locomotion-capacity.v1", relation: "REQUIRES", output: "locomotion", minimumConfidence: .55 }, { modelId: "space.route-reachability.v1", relation: "REQUIRES", output: "route", minimumConfidence: .5 }], applicable: context => situationIs(context, "DANGER_RESPONSE", "PREDATION_SEQUENCE"), relevance: () => .96, predict: context => { const entity = subject(context) || {}, physiology = entity.physiology || entity, fear = Number(physiology.fear || 0), reserve = Number(physiology.emergencyReserve || 0); return { outcomes: outcomes(fear > 65 ? [["FLIGHT_CONTINUES", .5], ["CONTACT_OR_DEFENCE", .28], ["DISENGAGES", .22]] : [["ASSESSMENT_CONTINUES", .46], ["DISENGAGES", .36], ["ESCALATES", .18]]), confidence: clamp01(.6 + fear / 400 + reserve / 10) }; } }));
  registry.register(family("social.relationship-resolution.v1", "SOCIAL", "SOCIAL_PHASE", { dependencies: [{ modelId: "state.identity-continuity.v1", relation: "REQUIRES", output: "identity", minimumConfidence: .7 }, { modelId: "camera.frameability.v1", relation: "OBSERVES", output: "frame" }], applicable: context => situationIs(context, "SOCIAL_INTERACTION", "GROUP_MOVEMENT", "REPRODUCTION_STAGE") || (context.subjects?.length || 0) > 1, predict: context => ({ outcomes: outcomes([["INTERACTION_CONTINUES", .5], ["RELATIONSHIP_RESPONSE", .32], ["SEPARATION", .18]]), confidence: .66 }) }));
  registry.register(family("reproduction.phase.v1", "REPRODUCTION", "REPRODUCTION_PHASE", { dependencies: [{ modelId: "social.relationship-resolution.v1", relation: "REQUIRES", output: "social", minimumConfidence: .55 }, { modelId: "physiology.locomotion-capacity.v1", relation: "SUPPORTS", output: "locomotion" }], applicable: context => situationIs(context, "REPRODUCTION_STAGE", "LIFECYCLE_TRANSITION"), predict: context => ({ outcomes: outcomes([["PHASE_CONTINUES", .48], ["ADVANCES", .34], ["ENDS_OR_INTERRUPTS", .18]]), confidence: .68 }) }));
  registry.register(family("environment.character-causal-link.v1", "ENVIRONMENT", "CHARACTER_WORLD_RELEVANCE", { dependencies: [{ modelId: "behaviour.plan-phase.v1", relation: "SUPPORTS" }, { modelId: "resource.target-validity.v1", relation: "SUPPORTS" }], applicable: context => Boolean(context.scene?.ids?.length && context.worldLink), predict: context => ({ outcomes: outcomes([["CAUSALLY_RELEVANT", context.worldLink ? .85 : .2], ["INCIDENTAL", context.worldLink ? .15 : .8]]), confidence: .8 }) }));
  registry.register(family("environment.world-process.v1", "ENVIRONMENT", "WORLD_PROCESS_CHANGE", { dependencies: [{ modelId: "state.evidence-freshness.v1", relation: "REQUIRES" }], applicable: context => Boolean(context.scene?.worldSubject || !context.scene?.ids?.length), predict: context => ({ outcomes: outcomes([["PROCESS_CONTINUES", .72], ["MATERIAL_CHANGE", .28]]), confidence: .7 }) }));
  registry.register(family("story.resolution-window.v1", "STORY", "THREAD_RESOLUTION_WINDOW", { dependencies: [{ modelId: "behaviour.plan-phase.v1", relation: "SUPPORTS" }, { modelId: "danger.response.v1", relation: "SUPPORTS" }, { modelId: "social.relationship-resolution.v1", relation: "SUPPORTS" }], applicable: context => Boolean(context.scene?.ids?.length), relevance: () => .92, predict: context => { const phase = methodPhase(context), near = ["contact", "acquire", "feed", "resolve", "recover", "respond"].includes(phase); return { outcomes: outcomes([[near ? "RESOLUTION_LIKELY" : "DEVELOPMENT_LIKELY", near ? .7 : .68], [near ? "DEVELOPMENT_LIKELY" : "RESOLUTION_LIKELY", near ? .3 : .32]]), confidence: .69, values: { phase } }; } }));
  registry.register(family("audience.semantic-novelty.v1", "AUDIENCE", "INFORMATION_GAIN", { dependencies: [{ modelId: "state.evidence-freshness.v1", relation: "REQUIRES" }], predict: context => ({ outcomes: outcomes([[context.semanticNovelty < .5 ? "DUPLICATE" : "NOVEL", context.semanticNovelty < .5 ? 1 - context.semanticNovelty : context.semanticNovelty], [context.semanticNovelty < .5 ? "NOVEL" : "DUPLICATE", context.semanticNovelty < .5 ? context.semanticNovelty : 1 - context.semanticNovelty]]), confidence: .9 }) }));
  registry.register(family("production.hold-value.v1", "PRODUCTION", "HOLD_OR_SWITCH", { dependencies: [{ modelId: "story.resolution-window.v1", relation: "REQUIRES", output: "story" }, { modelId: "camera.frameability.v1", relation: "REQUIRES", output: "frame" }, { modelId: "camera.occlusion-risk.v1", relation: "SUPPORTS", output: "occlusion" }, { modelId: "audience.semantic-novelty.v1", relation: "SUPPORTS", output: "novelty" }], applicable: context => Boolean(context.scene?.ids?.length), relevance: () => 1, predict: context => { const story = context.dependencyOutputs?.story || {}, frame = context.dependencyOutputs?.frame || {}, occlusion = context.dependencyOutputs?.occlusion || {}, holdBase = context.currentThread ? .66 : .58, resolutionBonus = story.phase ? .08 : 0, framePenalty = Number(frame.extent || 0) > 14 ? .18 : 0, occlusionPenalty = Number(occlusion.risk || 0) * .16, hold = clamp01(holdBase + resolutionBonus - framePenalty - occlusionPenalty); return { outcomes: outcomes([[context.currentThread ? "HOLD" : "ESTABLISH", hold], ["SWITCH", 1 - hold]]), confidence: .76, values: { hold, dependencyDriven: true } }; } }));

  registry.register(family("camera.validity-safety.v1", "CAMERA", "CAMERA_VALIDITY", { framework: "ANOMALY_SAFETY", authority: "VETO", safetyRegistered: true, dependencies: [{ modelId: "camera.subject-trajectory.v1", relation: "REQUIRES" }], predict: context => { const invalid = context.cameraPoseValid === false || Number(context.cameraRisk || 0) > .88; return { outcomes: outcomes([[invalid ? "INVALID" : "CLEAR", invalid ? .99 : .98], [invalid ? "CLEAR" : "INVALID", invalid ? .01 : .02]]), confidence: .98, values: { invalid } }; } }));
  const integrity = registry.integrity(); if (!integrity.valid) throw new TypeError(integrity.errors.join("; "));
  return registry;
}

export function runModelEnsemble(closure, context, { ensembleId, issuedAtTick = 0, horizonTicks = 30 } = {}) {
  if (!closure?.valid) return Object.freeze({ ensembleId, valid: false, abstained: true, reason: "dependency-closure-invalid", forecasts: Object.freeze([]), confidence: 0 });
  const forecasts = [], execution = new Map(), abstentions = [], selectedById = new Map(closure.models.map(item => [item.model.modelId, item])), groupInfluence = new Map(), correlationCap = Math.max(.1, Math.min(1, Number(context.correlationInfluenceCap || .45)));
  for (const modelId of closure.topologicalOrder || closure.models.map(item => item.model.modelId).reverse()) {
    const selected = selectedById.get(modelId); if (!selected) continue; const dependencyOutputs = {}, dependencyForecastIds = []; let dependencyFailed = false;
    for (const edge of selected.model.dependencies || []) {
      const dependency = execution.get(edge.modelId), minimumConfidence = Number(edge.minimumConfidence ?? .55); if (["REQUIRES", "REFINES"].includes(edge.relation) && (!dependency || dependency.status !== "PREDICTED" || dependency.confidence < minimumConfidence)) { dependencyFailed = true; abstentions.push(Object.freeze({ modelId, status: "DEPENDENCY_FAILED", dependencyModelId: edge.modelId, minimumConfidence, actualConfidence: dependency?.confidence ?? null })); break; }
      if (dependency) { dependencyOutputs[edge.output || edge.modelId] = dependency.values; dependencyForecastIds.push(dependency.forecastId); }
    }
    if (dependencyFailed) continue;
    const result = selected.model.predict({ ...context, dependencyOutputs }) || {};
    let confidence = clamp01(result.confidence ?? selected.score);
    const conflicts = [];
    for (const edge of selected.model.dependencies || []) { const dependency = execution.get(edge.modelId), top = dependency?.outcomes?.[0]; if (!dependency && selectedById.has(edge.modelId) && ["SUPPORTS", "CONDITIONS"].includes(edge.relation)) confidence *= .86; if (dependency && edge.relation === "INHIBITS" && (!edge.outcomes?.length || edge.outcomes.includes(top?.id)) && Number(top?.probability || 0) >= Number(edge.threshold ?? .6)) confidence *= Math.max(.05, 1 - Math.min(Number(selected.model.maximumInfluence || .2), Number(edge.strength ?? .65))); if (dependency && edge.relation === "CONTRADICTS" && (!edge.outcomes?.length || edge.outcomes.includes(top?.id)) && Number(top?.probability || 0) >= Number(edge.threshold ?? .6)) { confidence *= Math.max(.05, 1 - Math.min(Number(selected.model.maximumInfluence || .2), Number(edge.strength ?? .8))); conflicts.push({ modelId: edge.modelId, outcome: top?.id, probability: top?.probability }); } }
    if (confidence < selected.model.abstainBelowConfidence) { abstentions.push(Object.freeze({ modelId, status: "ABSTAINED", reason: "confidence-below-threshold", confidence, threshold: selected.model.abstainBelowConfidence })); continue; }
    const group = selected.model.correlationGroup || selected.model.family, priorInfluence = groupInfluence.get(group) || 0, requestedInfluence = Math.min(Number(selected.model.maximumInfluence || .2), confidence), admittedInfluence = Math.max(0, Math.min(requestedInfluence, correlationCap - priorInfluence)); if (admittedInfluence <= 0 && modelId !== closure.rootId) { abstentions.push(Object.freeze({ modelId, status: "ABSTAINED", reason: "correlation-cap", correlationGroup: group })); continue; } groupInfluence.set(group, priorInfluence + admittedInfluence);
    const rawOutcomes = result.outcomes || []; if (!rawOutcomes.length) { abstentions.push(Object.freeze({ modelId, status: "ABSTAINED", reason: "no-outcomes" })); continue; }
    const calibrated = context.calibration?.calibrate?.(selected.model.modelId, context, rawOutcomes) || rawOutcomes, modelHorizon = selected.model.horizon || {}, maximumTicks = Math.min(Number(horizonTicks), Number(modelHorizon.maximumTicks || horizonTicks)), effectiveConfidence = clamp01(confidence * (.7 + .3 * selected.reliability)), forecast = Object.freeze({ forecastId: `${ensembleId}:${selected.model.modelId}`, ensembleId, modelId: selected.model.modelId, modelVersion: selected.model.version, family: selected.model.family, predicts: selected.model.predicts, framework: selected.model.framework, outputShape: selected.model.outputShape, authority: selected.model.authority, safetyRegistered: selected.model.safetyRegistered, referent: context.scene?.ids?.[0] || context.scene?.id || null, activation: Object.freeze({ activated: true, reason: selected.model.modelId === closure.rootId ? "editorial root" : "dependency coalition" }), admission: Object.freeze({ admitted: true, confidence: effectiveConfidence, cost: Number(selected.model.costUnits || 0) }), coordination: Object.freeze({ influence: admittedInfluence, correlationGroup: group }), outcomeObserverId: selected.model.outcomeObserverId, rawOutcomes: Object.freeze(rawOutcomes.map(item => Object.freeze({ ...item }))), outcomes: Object.freeze(calibrated), confidence: effectiveConfidence, values: Object.freeze({ ...(result.values || {}) }), evidenceIds: Object.freeze([...(context.evidenceIds || [])]), dependencyForecastIds: Object.freeze(dependencyForecastIds), correlationGroup: group, admittedInfluence, conflicts: Object.freeze(conflicts), issuedAtTick, earliestTick: issuedAtTick + Number(modelHorizon.minimumTicks || 1), latestTick: issuedAtTick + maximumTicks, status: "PROPOSED" }); forecasts.push(forecast); execution.set(modelId, Object.freeze({ ...forecast, status: "PREDICTED" }));
  }
  const root = forecasts.find(item => item.modelId === closure.rootId), requiredConfidence = forecasts.length ? Math.pow(forecasts.reduce((product, item) => product * Math.max(.001, item.confidence), 1), 1 / forecasts.length) * Math.pow(Math.min(...forecasts.map(item => item.confidence)), .2) : 0;
  const vetoes = forecasts.filter(item => item.authority === "VETO" && item.safetyRegistered && item.outcomes[0]?.id !== "CLEAR" && item.outcomes[0]?.probability >= .55).map(item => Object.freeze({ modelId: item.modelId, outcome: item.outcomes[0].id, probability: item.outcomes[0].probability }));
  return Object.freeze({ ensembleId, rootModelId: closure.rootId, valid: Boolean(root) && !vetoes.length, abstained: !root, forecasts: Object.freeze(forecasts), abstentions: Object.freeze(abstentions), vetoes: Object.freeze(vetoes), authorityAssignments: Object.freeze(forecasts.map(item => Object.freeze({ modelId: item.modelId, authority: item.authority, influence: item.admittedInfluence }))), confidence: clamp01(requiredConfidence), dependencyCompleteness: closure.dependencyCompleteness, rootForecast: root || null, totalCost: closure.totalCost, budget: closure.budget, correlationInfluence: Object.freeze(Object.fromEntries(groupInfluence)) });
}
