import { runModelEnsemble } from "./models.js";
import { compileDocumentaryPolicy, policyAllowsClaim, policyAllowsScene as policySceneDecision } from "../documentary-author/planning/policy-compiler.js";
import { eligibleDocumentaryMethods, evaluateDocumentaryConcerns } from "../documentary-author/ontology/eligibility.js";
import { buildDependencyPlan, dependencyPlanComplete, nextReadyBeat, presentBeat, updateDependencyPlan } from "../documentary-author/stories/dependency-plan.js";
import { ReturnObligationQueue } from "../documentary-author/stories/return-obligation-queue.js";
import { deepFreeze } from "../documentary-author/runtime/immutable.js";

const CRITICAL_EVENTS = new Set(["BIRTH", "DEATH", "ATTACK"]);
const RETAINED_PLAN_LIMIT = 20;
const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
const participantsOf = scene => [...new Set(scene?.semanticRoleIds || scene?.ids || [])].map(String).filter(Boolean);
const rolesOf = situation => Object.fromEntries(Object.entries(situation?.participantRoles || {}).map(([role, ids]) => [role, [...ids].map(String).sort()]));
const rootFor = (situation, methodId) => situation?.type === "ENVIRONMENTAL_PROCESS" ? "environment.world-process.v1" : ["observe-danger-resolution", "observe-death-consequence"].includes(methodId) ? "danger.response.v1" : ["observe-social-resolution", "observe-reproduction-stage"].includes(methodId) ? "social.relationship-resolution.v1" : "production.hold-value.v1";

export function policyAllowsScene(scene, policy = {}) {
  return policySceneDecision(scene, policy.policyId ? policy : compileDocumentaryPolicy(policy)).allowed;
}

export class ACSSStoryPlanner {
  constructor() { this.threads = new Map(); this.byId = new Map(); this.bySituation = new Map(); this.currentThreadId = null; this.obligations = new ReturnObligationQueue(); this.returnObligations = []; this.sequence = 0; this.revision = 0; }
  threadKey(scene, context = {}) { const situation = context.situation; return `${situation?.situationId || scene?.id || "unknown"}|${Object.entries(rolesOf(situation)).map(([role, ids]) => `${role}:${ids.join("+")}`).join("|")}|${context.methodId || "observe"}`; }
  ensure(scene, tick, context = {}) {
    const key = this.threadKey(scene, context); let thread = this.threads.get(key);
    if (!thread) { thread = { threadId: `acss-thread-${String(++this.sequence).padStart(8, "0")}`, key, situationId: context.situation?.situationId || null, subjectIds: participantsOf(scene), participantRoles: rolesOf(context.situation), methodId: context.methodId, dependencyPlan: buildDependencyPlan(context.methodId, context.situation), openedAtTick: tick, lastObservedAtTick: tick, lastSelectedAtTick: null, state: "DEVELOPING", presentationHistory: [] }; this.threads.set(key, thread); this.byId.set(thread.threadId, thread); addIndex(this.bySituation, thread.situationId, thread.threadId); }
    thread.lastObservedAtTick = tick; thread.subjectIds = participantsOf(scene); thread.participantRoles = rolesOf(context.situation); thread.dependencyPlan = updateDependencyPlan(thread.dependencyPlan, context.situation); if (dependencyPlanComplete(thread.dependencyPlan)) thread.state = "RESOLVED"; this.revision += 1; return thread;
  }
  current() { return this.byId.get(this.currentThreadId) || null; }
  nextBeat(thread) { return nextReadyBeat(thread?.dependencyPlan || [])?.beatId || "release"; }
  select(thread, tick, { interrupted = false, critical = false } = {}) {
    const previous = this.current();
    if (previous && previous.threadId !== thread.threadId && previous.state !== "RESOLVED") { const obligation = this.obligations.create({ threadId: previous.threadId, situationId: previous.situationId, createdAtTick: tick, deadlineTick: tick + (critical ? 240 : 420), causalValue: critical ? .9 : .65, characterImportance: previous.subjectIds.length ? .7 : .25, reason: interrupted ? "critical-interruption" : "editorial-switch", requiredBeatIds: [this.nextBeat(previous)].filter(Boolean) }); previous.state = "RETURN_READY"; previous.returnObligationId = obligation.obligationId; }
    this.currentThreadId = thread.threadId; thread.lastSelectedAtTick = tick; thread.state = "ACTIVE"; const returning = this.obligations.forThread(thread.threadId); if (returning?.state === "ELIGIBLE") this.obligations.select(returning.obligationId, tick); this.revision += 1; this.#syncObligations(); return thread;
  }
  completeBeat(thread, beat, { outcomeChanged = false, shown = true, narratedClaimIds = [], tick = 0, skipReason = null } = {}) { if (!thread) return null; const before = thread.dependencyPlan.find(item => item.beatId === beat)?.status; thread.dependencyPlan = presentBeat(thread.dependencyPlan, beat, { shown: shown || outcomeChanged, narratedClaimIds, skipReason }); const after = thread.dependencyPlan.find(item => item.beatId === beat)?.status; thread.presentationHistory.push({ beat, tick, shown, narratedClaimIds: [...narratedClaimIds], skipReason }); if (thread.presentationHistory.length > 128) thread.presentationHistory.splice(0, thread.presentationHistory.length - 128); if (dependencyPlanComplete(thread.dependencyPlan)) thread.state = "RESOLVED"; const obligation = this.obligations.forThread(thread.threadId), requiredBeatSatisfied = obligation && (!obligation.requiredBeatIds?.length || obligation.requiredBeatIds.includes(beat)) && before !== "PRESENTED" && after === "PRESENTED"; if (obligation && ["SELECTED", "ELIGIBLE"].includes(obligation.state) && requiredBeatSatisfied) this.obligations.fulfill(obligation.obligationId, tick, "required-beat-presented"); this.revision += 1; this.#syncObligations(); return thread; }
  updateSituations(tick, activeSituationIds) { const valid = new Set(); for (const situationId of activeSituationIds) for (const threadId of this.bySituation.get(situationId) || []) valid.add(threadId); this.obligations.update(tick, valid); this.#syncObligations(); }
  returnable(tick = 0) { const item = this.obligations.topEligible(tick); return item ? this.byId.get(item.threadId) || null : null; }
  close(tick = 0, reason = "session-ended") { const closed = this.obligations.closeAll(tick, reason); for (const thread of this.threads.values()) if (!["RESOLVED", "ARCHIVED"].includes(thread.state)) thread.state = "ARCHIVED"; this.currentThreadId = null; this.revision += 1; this.#syncObligations(); return closed; }
  #syncObligations() { this.returnObligations = this.obligations.snapshot().active.map(item => item.threadId); }
}

function addIndex(index, key, value) { if (key == null) return; let values = index.get(key); if (!values) { values = new Set(); index.set(key, values); } values.add(value); }

// Array#sort is stable, so equal-scoring plans historically retained scene
// order. Keep that contract while bounding both ranking work and retained plans.
function ranksBefore(candidate, held) { return held.score - candidate.score < 0; }
function betterRankedPlan(held, candidate) { return !held || ranksBefore(candidate, held) ? candidate : held; }
function retainRankedPlan(plans, candidate, limit = RETAINED_PLAN_LIMIT) {
  let index = plans.length;
  while (index > 0 && ranksBefore(candidate, plans[index - 1])) index -= 1;
  if (index >= limit) return;
  plans.splice(index, 0, candidate);
  if (plans.length > limit) plans.pop();
}

export class ACSSDecisionPlanner {
  constructor({ registry, learning, stories, idFactory = null } = {}) { this.registry = registry; this.learning = learning; this.stories = stories; this.idFactory = idFactory || { sequence: 0, next(prefix) { return `${prefix}-${++this.sequence}`; } }; this.lastPlans = []; this.rejections = []; this.fallbacks = []; }
  contextFor(scene, snapshot, policy, currentThread, extras = {}) {
    const ids = participantsOf(scene), subjects = ids.map(id => snapshot?.entities?.get?.(id) || snapshot?.entityByIdentityId?.get?.(id) || snapshot?.corpses?.get?.(id) || snapshot?.corpseByIdentityId?.get?.(id) || [...(snapshot?.corpses?.values?.() || [])].find(item => item.id === id || item.identityId === id)).filter(Boolean), primary = subjects[0], situation = extras.situation || null;
    return { scene, subjects, subjectCount: subjects.length, methodId: extras.methodId, simulationMethodId: primary?.plan?.methodId || situation?.methodId || null, simulationMethodFamily: situation?.type || null, phase: situation?.methodPhase || null, preset: policy.presetName, worldLink: Boolean(ids.length && extras.worldClaimIds?.length), semanticNovelty: scene.semanticNovelty ?? .5, currentThread: currentThread?.situationId === situation?.situationId, cameraRisk: Number(scene.cameraRisk || 0), routeBlocked: primary?.movement?.blocked === true, targetValid: primary?.plan?.targetId ? true : undefined, evidenceFresh: true, calibration: this.learning.calibration, beliefs: extras.observation?.beliefs || null, situation, situationId: situation?.situationId || null, action: primary?.action?.key || "observe", worldRevision: snapshot?.worldRevision || null, evidenceIds: extras.claims?.flatMap(claim => claim.evidenceIds || []) || [] };
  }
  planScene(scene, snapshot, policy, tick, extras = {}) {
    const scenePolicy = policySceneDecision(scene, policy); if (!scenePolicy.allowed) { this.rejections.push({ sceneId: scene.id, reason: scenePolicy.reason }); return null; }
    const situation = extras.situationByScene?.get?.(scene.id) || extras.observation?.situations?.forScene?.(scene.id) || null; if (!situation) { this.rejections.push({ sceneId: scene.id, reason: "situation-missing" }); return null; }
    const sceneParticipants = participantsOf(scene), rawClaims = sceneParticipants.length ? extras.observation?.propositions?.forSubjects?.(sceneParticipants) || [] : (extras.observation?.propositions?.records || []).filter(claim => !claim.subjectIds?.length), claims = rawClaims.filter(claim => policyAllowsClaim(claim, policy).allowed); const eligibility = eligibleDocumentaryMethods({ situation, policy, claims, cameraFeasible: scene.cameraRisk !== 1 }); if (!eligibility.eligible.length) { this.rejections.push(...eligibility.rejected.map(item => ({ sceneId: scene.id, ...item }))); return null; }
    const method = eligibility.eligible[0], current = this.stories.current(), provisional = this.contextFor(scene, snapshot, policy, current, { ...extras, situation, methodId: method.methodId, claims }), thread = this.stories.ensure(scene, tick, provisional), context = { ...provisional, currentThread: current?.threadId === thread.threadId }, preferredRootModelId = rootFor(situation, method.methodId); let rootModelId = preferredRootModelId, closure = this.registry.dependencyClosure(rootModelId, context, this.learning.calibration, { budget: 100 }), predictionFallback = null;
    if (!closure.valid) { const failed = closure, fallbackRoots = situation.type === "ENVIRONMENTAL_PROCESS" ? ["state.identity-continuity.v1"] : ["production.hold-value.v1", "camera.frameability.v1", "state.identity-continuity.v1"]; for (const candidateRoot of fallbackRoots) { if (candidateRoot === preferredRootModelId) continue; const candidate = this.registry.dependencyClosure(candidateRoot, context, this.learning.calibration, { budget: 100 }); if (candidate.valid) { rootModelId = candidateRoot; closure = candidate; predictionFallback = { preferredRootModelId, fallbackRootModelId: candidateRoot, reason: "preferred-model-unavailable", missing: failed.missing }; this.fallbacks.push({ sceneId: scene.id, tick, ...predictionFallback }); this.fallbacks = this.fallbacks.slice(-200); break; } } }
    if (!closure.valid) { this.rejections.push({ sceneId: scene.id, reason: "prediction-dependency-closure-failed", details: closure.missing, contradictions: closure.contradictions }); return null; }
    const ensemble = runModelEnsemble(closure, context, { ensembleId: this.idFactory.next("ensemble"), issuedAtTick: tick, horizonTicks: 30 }); if (!ensemble.valid) { this.rejections.push({ sceneId: scene.id, reason: "prediction-ensemble-invalid" }); return null; }
    const participants = participantsOf(scene), critical = CRITICAL_EVENTS.has(String(scene.eventType || "").toUpperCase()) || Number(scene.importance || scene.eventPriority || 0) >= policy.eventThreshold, sameThread = current?.threadId === thread.threadId, frameForecast = ensemble.forecasts.find(item => item.modelId === "camera.frameability.v1"), frameable = frameForecast?.outcomes?.[0]?.id !== "WIDEN_REQUIRED", nearResolution = ["OUTCOME_PENDING", "RESOLVED", "CONSEQUENCE_AVAILABLE"].includes(situation.state), concerns = evaluateDocumentaryConcerns({ situation, policy, novelty: context.semanticNovelty, cameraRisk: scene.cameraRisk || 0, critical, activeThread: sameThread, nearResolution, explicitConflict: false, audienceUncertainty: extras.audience?.health?.().uncertainty || 0 });
    const importance = clamp01(Number(scene.importance || scene.eventPriority || scene.score || 0) / 100), continuity = sameThread ? 1 : thread.state === "RETURN_READY" ? .8 : .1, novelty = clamp01(context.semanticNovelty), favorite = participants.reduce((sum, id) => sum + this.learning.preferences.character(id), 0), policyAdjustment = Math.max(-policy.maximumPolicyAdjustment, Math.min(policy.maximumPolicyAdjustment, this.learning.policy.adjustment(sameThread ? "HOLD_THREAD" : "SELECT_THREAD", context))), audience = extras.audience?.preferenceForScene?.(scene, policy) || { adjustment: 0, mean: 0, variance: 1 }, audienceAdjustment = Math.max(-policy.maximumAudienceUtility, Math.min(policy.maximumAudienceUtility, Number(audience.adjustment || 0))), imageSufficiency = clamp01(Number(frameable) * (1 - Number(scene.cameraRisk || 0))), speechUtility = clamp01(.55 * novelty + .3 * (concerns[0]?.pressure || 0) + .15 * importance), silenceUtility = clamp01(.5 * (1 - novelty) + .35 * imageSufficiency + .15 * Number(!policy.narrationEnabled)), silenceSelected = !critical && (policy.narrationEnabled === false || !claims.length || silenceUtility > speechUtility + .18), utility = { importance, prediction: ensemble.confidence, continuity, novelty, frameability: Number(frameable), favorite: clamp01((favorite + 1) / 2), concern: concerns[0]?.pressure || 0, imageSufficiency, speechUtility, silenceUtility, policyAdjustment, audienceAdjustment }, score = .23 * utility.importance + .18 * utility.prediction + .18 * utility.continuity + .13 * utility.novelty + .1 * utility.frameability + .08 * utility.favorite + .1 * utility.concern + utility.policyAdjustment + utility.audienceAdjustment;
    return { planId: this.idFactory.next("plan"), scene, situation, claims, thread, context, ensemble, concerns, utility, action: sameThread ? "HOLD_THREAD" : thread.state === "RETURN_READY" ? "RETURN_TO_THREAD" : "SELECT_THREAD", methodId: method.methodId, satisfierId: method.satisfierId, beat: this.stories.nextBeat(thread), participants, critical, score, frameable, silenceSelected, predictionFallback, audience, audienceCamera: extras.audience?.cameraPreferences?.({ world: !participants.length }) || null, audienceNarration: extras.audience?.narrationPreferences?.() || null, productionPolicy: this.learning.production, productionFaults: this.learning.faults, policy };
  }
  choose(scenes, snapshot, policyInput, tick, { speechActive = false, ...extras } = {}) {
    const policy = policyInput?.policyId ? policyInput : compileDocumentaryPolicy(policyInput); this.rejections = []; this.fallbacks = []; this.stories.updateSituations(tick, new Set(extras.observation?.situations?.situations?.map(item => item.situationId) || []));
    const current = this.stories.current(), currentThreadId = current?.threadId, returnable = this.stories.returnable(tick), returnThreadId = returnable?.threadId; let incumbent = null, critical = null, returning = null; const plans = [];
    for (const scene of scenes) {
      const plan = this.planScene(scene, snapshot, policy, tick, extras);
      if (!plan) continue;
      retainRankedPlan(plans, plan);
      if (plan.critical) critical = betterRankedPlan(critical, plan);
      if (plan.thread.threadId === currentThreadId) incumbent = betterRankedPlan(incumbent, plan);
      if (plan.thread.threadId === returnThreadId) returning = betterRankedPlan(returning, plan);
    }
    let best = plans[0]; if (critical) best = critical; else if (incumbent && policy.continuity !== "off" && (speechActive || incumbent.score >= (plans[0]?.score || 0) - policy.continuityMargin)) best = incumbent; else if (returning && policy.allowElectiveReturns && returning.score >= (plans[0]?.score || 0) - policy.continuityMargin * .6) best = returning; this.lastPlans = plans; if (!best) return null; this.stories.select(best.thread, tick, { interrupted: Boolean(critical && incumbent && critical.thread.threadId !== incumbent.thread.threadId), critical: Boolean(critical) }); return best;
  }
}

export function compilePresentationContract(plan, { tick = 0, policy = plan?.policy || {} } = {}) {
  if (!plan) return null; const resolvedPolicy = policy.policyId ? policy : compileDocumentaryPolicy(policy), world = !plan.participants.length, trajectory = plan.ensemble.forecasts.find(item => item.modelId === "camera.subject-trajectory.v1"), frame = plan.ensemble.forecasts.find(item => item.modelId === "camera.frameability.v1"), zone = trajectory?.values?.predicted || plan.scene.focus, minimumHold = plan.critical ? 5 : ["outcome", "consequence", "reaction"].includes(plan.beat) ? 9 : 7, preferredHold = plan.critical ? 12 : resolvedPolicy.pacing === "relaxed" ? 16 : 11;
  const preferred = world ? ["establishing", "sweep", "pull-out", "aerial", "still"] : ["still", "tracking", "intercept", "push-in", "orbit"], permitted = preferred.filter(id => resolvedPolicy.allowedCameraFamilies.includes(id) && !plan.productionFaults?.quarantined?.("camera-family", id)), safe = permitted.length ? permitted : resolvedPolicy.allowedCameraFamilies.slice(0, 1), familyUtility = id => (plan.productionFaults?.penalty?.("camera-family", id) || 0) + (plan.productionPolicy?.adjustment?.(`CAMERA_FAMILY:${id}`, plan.context) || 0), ranked = [...safe].sort((left, right) => familyUtility(right) - familyUtility(left)), audienceFamilies = plan.audienceCamera?.families?.some(item => item.confidence >= .2) ? plan.audienceCamera.families.map(item => item.id).filter(id => ranked.includes(id)) : [], sizes = world ? ["WIDE"] : frame?.outcomes?.[0]?.id === "WIDEN_REQUIRED" ? ["WIDE", "MEDIUM"] : ["MEDIUM", "CLOSE", "WIDE"];
  const allowedClaims = plan.claims.filter(claim => policyAllowsClaim(claim, resolvedPolicy).allowed).slice(0, 32), allowedClaimIds = allowedClaims.map(claim => claim.claimId), evidenceIds = [...new Set(allowedClaims.flatMap(claim => claim.evidenceIds || []))], baseSentences = resolvedPolicy.narrationLength === "short" ? 2 : resolvedPolicy.narrationLength === "extended" ? 6 : 4, narrationDelta = plan.audienceNarration?.density?.confidence >= .25 ? Math.sign(plan.audienceNarration.density.mean) : 0, silence = Boolean(plan.silenceSelected || !resolvedPolicy.narrationEnabled || !allowedClaimIds.length);
  return deepFreeze({ schemaVersion: 2, contractId: `acss-contract-${plan.planId}`, profileRevision: plan.context?.profileRevision || null, policyId: resolvedPolicy.policyId, decision: { decisionId: plan.planId, action: silence ? "REMAIN_SILENT" : plan.action, threadId: plan.thread.threadId, situationId: plan.situation.situationId, satisfierId: plan.satisfierId, methodId: plan.methodId, phase: plan.beat, concernId: plan.concerns[0]?.id, score: plan.score, utility: plan.utility, tick }, sceneId: plan.scene.id, semanticFingerprint: plan.scene.semanticFingerprint || null, situationId: plan.situation.situationId, threadId: plan.thread.threadId, subjectIds: [...plan.participants], subjectRoles: rolesOf(plan.situation), beat: plan.beat, allowedClaimIds, evidenceIds, narration: { mode: silence ? "SILENCE" : "SPEAK", function: ["outcome", "consequence", "reaction"].includes(plan.beat) ? "RESOLUTION" : "EXPLANATION", subjectIds: [...plan.participants], allowedClaimIds, evidenceIds, maximumSentences: Math.max(1, Math.min(8, baseSentences + narrationDelta)), voiceEnabled: resolvedPolicy.voiceEnabled, captionsEnabled: resolvedPolicy.captionsEnabled, requireNewInformation: true, epistemicPolicy: "EVIDENCE_BOUNDED" }, camera: { primarySubjects: plan.participants.slice(0, 1), secondarySubjects: plan.participants.slice(1, 8), highlightSubjectIds: [...plan.participants], relationship: world ? "WORLD_CONTEXT" : plan.participants.length > 1 ? "SEMANTIC_SHARED_FRAME" : "SINGLE_SUBJECT", predictedActionZone: zone ? { x: Number(zone.x || 0), z: Number(zone.z || 0) } : null, trajectory: trajectory?.values?.trajectory || [], preferredShotSizes: sizes, preferredFamilies: audienceFamilies.length ? audienceFamilies : ranked, allowedFamilies: [...resolvedPolicy.allowedCameraFamilies], minimumHoldSeconds: minimumHold, preferredHoldSeconds: preferredHold, continuousRepairOnly: true, breakConditions: ["CRITICAL_IRREVERSIBLE_EVENT", "ALL_SUBJECTS_LOST", "CAMERA_INVALID"], maximumSpeed: world ? 10 : 13, maximumAcceleration: world ? 16 : 22, maximumJerk: world ? 30 : 42, response: world ? 1.7 : 2.2 }, forecasts: plan.ensemble.forecasts, dependencies: plan.ensemble.forecasts.map(item => item.modelId), reconsiderAtTick: Math.min(...plan.ensemble.forecasts.map(item => item.latestTick || tick + 30), tick + 30), valid: Boolean(allowedClaimIds.length || silence), validationErrors: [] });
}
