const clamp = (n, min, max) => Math.max(min, Math.min(max, Number(n)));
const roleFor = p => p.guild === "omnivore" ? "omnivore" : ["carnivore", "scavenger"].includes(p.guild) ? "carnivore" : "herbivore";
export function speciesForRole(role, registry) { const rows = Object.values(registry); return role === "random" ? rows : rows.filter(p => roleFor(p) === role); }
export function ageRangeForStage(s, stage) { const ranges = { dependent: [0, Math.max(0, s.dependency - 1)], juvenile: [s.dependency, Math.max(s.dependency, s.matureAge * .65)], subadult: [s.matureAge * .65, Math.max(s.matureAge * .65, s.matureAge - .01)], adult: [s.matureAge, Math.max(s.matureAge, s.oldAge - .01)], old: [s.oldAge, s.maxAge] }; const r = ranges[stage] || [0, s.maxAge]; return { min: r[0], max: r[1] }; }
export function validReproductiveSetup(request, s) { const pregnant = request?.reproduction?.pregnant; if (!pregnant || pregnant === "random") return { valid: true }; if (request.sex !== "F") return { valid: false, reason: "Pregnancy requires a female organism." }; if (!["adult", "old"].includes(request.lifeStage)) return { valid: false, reason: "Pregnancy requires a mature life stage." }; return { valid: true, gestationProgress: clamp(request.reproduction.gestationProgress ?? .5, 0, 1), gestation: s.gestation }; }
export function normalizeConditionSetup(request = {}, s, stage) { const c = request.condition || {}; return { health: clamp(c.health ?? 100, 1, 100), energy: clamp(c.energy ?? 90, 0, 100), hydration: clamp(100 - (c.thirst ?? 4), 0, 100), stomach: clamp(100 - (c.hunger ?? 20), 0, 100), fatigue: clamp(c.fatigue ?? 0, 0, 100), injuries: Array.isArray(c.injuries) ? c.injuries.slice(0, 8) : [], stage, capacity: s.energyCapacity }; }
export function validateEmbodiedSetup(request, worldSetup, capabilities, registry) { const errors = [], role = request.role || "random", candidates = speciesForRole(role, registry); if (!candidates.length) errors.push(`No ${role} species exist.`); const species = request.speciesId ? registry[request.speciesId] : null; if (species && !candidates.includes(species)) errors.push("Selected species does not match the ecological role."); if (capabilities.entitySetup === "role-only" && [request.speciesId, request.sex, request.lifeStage, request.age].some(v => v != null)) errors.push("This difficulty permits ecological-role selection only."); if (species && request.lifeStage && request.age != null) { const r = ageRangeForStage(species, request.lifeStage); if (request.age < r.min || request.age > r.max) errors.push("Age is outside the selected life stage."); } if (species) { const reproductive = validReproductiveSetup(request, species); if (!reproductive.valid) errors.push(reproductive.reason); } const counts = worldSetup.speciesCounts || {}, available = candidates.reduce((n, p) => n + (counts[p.id] || 0), 0); if (available < 1) errors.push(`The world needs at least one ${role === "random" ? "animal" : role} population slot.`); return { valid: !errors.length, errors, candidates: candidates.map(p => p.id) }; }
export function randomEmbodiedSetup(request, worldSetup, capabilities, registry, rng = Math.random) { const candidates = speciesForRole(request.role || "random", registry).filter(p => (worldSetup.speciesCounts?.[p.id] || 0) > 0), s = candidates[Math.floor(rng() * candidates.length)] || speciesForRole(request.role || "random", registry)[0], stages = ["dependent", "juvenile", "subadult", "adult", "old"], lifeStage = capabilities.entitySetup === "role-only" || !request.lifeStage ? stages[Math.floor(rng() * stages.length)] : request.lifeStage, range = ageRangeForStage(s, lifeStage), sex = capabilities.entitySetup === "role-only" || !request.sex ? (rng() < .5 ? "F" : "M") : request.sex; return { ...request, speciesId: capabilities.entitySetup === "role-only" ? s.id : request.speciesId || s.id, sex, lifeStage, age: request.age ?? range.min + rng() * Math.max(0, range.max - range.min), condition: normalizeConditionSetup(request, s, lifeStage), reproduction: capabilities.entitySetup === "role-only" ? { pregnant: sex === "F" && ["adult", "old"].includes(lifeStage) && rng() < .2 ? true : false, gestationProgress: rng() } : request.reproduction || { pregnant: false } }; }
export function guaranteePopulationSlot(counts, selectedSpeciesId, registry) { const next = { ...counts }; if ((next[selectedSpeciesId] || 0) > 0) return next; const role = roleFor(registry[selectedSpeciesId]), donor = Object.keys(next).find(id => id !== selectedSpeciesId && roleFor(registry[id]) === role && next[id] > 0); if (!donor) throw new Error(`No ${role} population slot can be transferred.`); next[donor]--; next[selectedSpeciesId] = 1; return next; }
export function describeEmbodiedSetup(r) { return `${r.speciesId || "random species"} · ${r.sex || "random sex"} · ${r.lifeStage || "random stage"}`; }
